import type { ConversationSeed } from '../types'

/**
 * Arabic Heritage Seeds — Arab diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Arabic and English, informal spoken register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_AR: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-ar-family-l01',
    title: 'Greeting Teta',
    blurb: 'Practice greeting your grandmother in Arabic',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Teta (grandmother) who greets you with "Ahlan ya habibi!" and pinches your cheeks. She asks if you have eaten and insists you sit down for food. Practice basic Arabic greetings and family terms while mixing in English as you naturally would.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['teta', 'ahlan', 'habibi', 'akl', 'yalla', 'shukran'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-food-l02',
    title: 'Mama\'s Sunday Feast',
    blurb: 'Help prepare a traditional Arabic meal',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-ar-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Mama (mother) is preparing a big Sunday lunch — hummus, tabbouleh, and mansaf. She asks you to help chop parsley and set the table. Learn food vocabulary and kitchen instructions in Arabic while she code-switches with you.',
    targetGrammar: ['imperatives', 'present-simple', 'articles'],
    targetVocab: ['hummus', 'tabbouleh', 'zeit', 'khubz', 'labneh', 'zaatar'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-ramadan-l03',
    title: 'First Day of Ramadan',
    blurb: 'Experience the start of Ramadan with your family',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-ar-food-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'It is the first day of Ramadan. Your family wakes up for suhoor, and Baba reads the dua. After school, you help Mama prepare iftar. Discuss Ramadan routines, what you are cooking, and who is coming for dinner using Arabic with natural English mixing.',
    targetGrammar: ['future-going-to', 'present-continuous', 'prepositions-time'],
    targetVocab: ['ramadan', 'suhoor', 'iftar', 'dua', 'salat', 'tamr'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-video-l04',
    title: 'Video Call to Jiddo',
    blurb: 'Chat with your grandfather overseas',
    level: 4,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-ar-ramadan-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Jiddo (grandfather) calls from Amman. He asks about school, your Arabic homework, and tells you about the olive harvest. Practice maintaining a conversation with an elder who gently corrects your Arabic while being proud of your effort.',
    targetGrammar: ['past-simple', 'questions-wh', 'future-will'],
    targetVocab: ['jiddo', 'madrasa', 'zeitoun', 'balad', 'akhbar', 'watan'],
    difficulty: 'practice',
    culturalContext: { region: 'JO', category: 'family' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-ar-eid-l05',
    title: 'Eid al-Fitr Gathering',
    blurb: 'Navigate a large family Eid celebration',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-ar-video-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'The whole family gathers for Eid al-Fitr. Amto (aunt) gives you eidiyeh, Khalo (uncle) cracks jokes in Arabic, and your little cousins want to play. Navigate greetings with many relatives, accept compliments gracefully, and explain American school life in Arabic.',
    targetGrammar: ['present-perfect', 'modals-should', 'connectors'],
    targetVocab: ['eid-mubarak', 'eidiyeh', 'amto', 'khalo', 'maamoule', 'ziyara'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-respect-l06',
    title: 'Arabic Politeness with Elders',
    blurb: 'Learn formal address and respectful phrases',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-ar-eid-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Baba corrects you for addressing his friend by first name instead of "Ammo" (uncle). Learn the difference between how you speak to peers versus elders in Arabic culture — ya3tik il3afye, tfaddal, Allah ykhaleek. Practice different registers within one family gathering.',
    targetGrammar: ['modals-should', 'questions-indirect', 'subject-pronouns'],
    targetVocab: ['ammo', 'tfaddal', 'inshallah', 'mashallah', 'habibi', 'adab'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-explain-l07',
    title: 'What Is Dabke?',
    blurb: 'Explain Arabic dance traditions to a friend',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-ar-respect-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'After posting a video of your cousin\'s wedding dabke, your friend asks what is happening. Explain the tradition, the music, the steps, and why everyone seems to know the moves. Use Arabic terms for cultural concepts that have no English equivalent.',
    targetGrammar: ['present-simple', 'relative-clauses', 'connectors'],
    targetVocab: ['dabke', 'tabla', 'aroos', 'hafle', 'tarab', 'turath'],
    difficulty: 'practice',
    culturalContext: { region: 'LB', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-ar-stories-l09',
    title: 'Teta\'s Village Stories',
    blurb: 'Listen to your grandmother\'s memories of the old country',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-ar-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Teta shares stories of growing up in her village — the fig trees, the neighbors, the sounds of the muezzin. She speaks in a rich colloquial dialect full of proverbs. Navigate understanding her storytelling, ask about details, and connect her experiences to your own life.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['qarya', 'teen', 'jiiran', 'hikaya', 'mathal', 'zamaan'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-identity-l10',
    title: 'Arab-American Identity',
    blurb: 'Discuss what it means to be Arab in the diaspora',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 6,
    prerequisites: ['heritage-ar-stories-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'A relative visiting from abroad says "You are not really Arab anymore." Engage in a thoughtful discussion about identity, language loss, cultural connection, and what Arab identity means when you grew up far from the homeland. Use elevated Arabic for abstract concepts.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['huwiya', 'watan', 'ightirrab', 'lugha', 'thaqafa', 'intima'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-ar-community-l11',
    title: 'Community Iftar Organization',
    blurb: 'Coordinate a multi-family community iftar event',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-ar-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'You help organize a community iftar at the local masjid. Coordinate food contributions from different families, welcome new members in formal Arabic, and manage logistics. Switch between formal Arabic with community leaders and casual dialect with friends your age.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['masjid', 'jamaa', 'da3wa', 'tandheem', 'taawun', 'mujtama3'],
    difficulty: 'challenge',
    culturalContext: { region: 'EG', category: 'social' },
    heritageMode: true,
  },
]
