import type { ConversationSeed } from '../types'

/**
 * Greek Heritage Seeds — Greek diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Greek and English (Gringlish), informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_EL: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-el-family-l01',
    title: 'Yiayia\'s Kitchen',
    blurb: 'Greet your grandmother and help in the kitchen',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Yiayia who greets you with "Ela, paidi mou!" and immediately starts feeding you. She asks "Peinases?" (Are you hungry?) and starts warming spanakopita. Practice basic Greek greetings and family terms while mixing in English as you naturally would.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['yiayia', 'pappou', 'ela', 'paidi-mou', 'efcharisto', 'agapi'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-food-l02',
    title: 'Making Koulourakia with Yiayia',
    blurb: 'Bake traditional Greek cookies together',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-el-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Yiayia teaches you to make koulourakia (butter cookies) for Easter. She gives instructions in Greek — "Vale to alevri," "Zymose to" — and tells stories of baking with her own mother in the village. Practice cooking vocabulary and follow instructions in Greek.',
    targetGrammar: ['imperatives', 'present-simple', 'quantifiers'],
    targetVocab: ['koulourakia', 'alevri', 'voutiro', 'avga', 'fourno', 'zymi'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-pascha-l03',
    title: 'Getting Ready for Pascha',
    blurb: 'Prepare for Greek Orthodox Easter with family',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-el-food-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family prepares for Pascha (Easter). Mama dyes red eggs, Baba prepares the souvla. You go to midnight liturgy holding candles. Discuss the traditions — cracking eggs, "Christos Anesti" greeting, and the feast that follows. Practice celebration vocabulary.',
    targetGrammar: ['future-going-to', 'present-continuous', 'conjunctions'],
    targetVocab: ['pascha', 'christos-anesti', 'avgo', 'souvla', 'lambada', 'ekklisia'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-nameday-l04',
    title: 'Your Name Day Party',
    blurb: 'Celebrate your name day with family',
    level: 4,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-el-pascha-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'It is your name day — more important than your birthday in Greek culture. Theia (aunt) calls to say "Chronia Polla!", Theio (uncle) brings a gift. Explain to your non-Greek friend what a name day is while receiving well-wishes from relatives in Greek.',
    targetGrammar: ['present-perfect', 'modals-should', 'questions-wh'],
    targetVocab: ['onomastiki', 'chronia-polla', 'theia', 'theio', 'giorti', 'efchi'],
    difficulty: 'practice',
    culturalContext: { region: 'GR', category: 'celebration' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-el-wedding-l05',
    title: 'Cousin\'s Greek Wedding',
    blurb: 'Experience a traditional Greek Orthodox wedding',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-el-nameday-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your cousin is having a big Greek wedding. Experience the stefana (crowns) ceremony, throw rice, dance the kalamatiano, and shout "Opa!" at the reception. Navigate conversations with Greek relatives while explaining traditions to non-Greek friends in attendance.',
    targetGrammar: ['present-continuous', 'modals-must', 'connectors'],
    targetVocab: ['gamos', 'stefana', 'koumbaros', 'glendi', 'kalamatiano', 'opa'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-pappou-l06',
    title: 'Backgammon with Pappou',
    blurb: 'Play tavli and chat with your grandfather',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-el-wedding-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Pappou (grandfather) sets up the tavli (backgammon) board after dinner. While playing, he tells stories about his village in Greece, teaches you game strategy in Greek, and asks about your life. Practice conversational Greek with an elder in a relaxed setting.',
    targetGrammar: ['past-simple', 'modals-could', 'relative-clauses'],
    targetVocab: ['tavli', 'pappou', 'chorio', 'palio', 'zaria', 'nikao'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-explain-l07',
    title: 'Explaining Greek Dance',
    blurb: 'Teach a friend about Greek folk dancing',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-el-pappou-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your friend sees videos from Greek school where you learned syrtos and tsamiko. Explain the different dances, their regional origins, and why every Greek event ends with dancing. Use Greek musical terms and dance vocabulary while explaining significance in English.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['syrtos', 'hasapiko', 'tsamiko', 'zeimbekiko', 'choros', 'mousiki'],
    difficulty: 'practice',
    culturalContext: { region: 'GR', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-el-stories-l09',
    title: 'Pappou\'s Village Stories',
    blurb: 'Hear your grandfather\'s memories of growing up in Greece',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-el-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Pappou shares stories of leaving his village — the journey to a new country, the struggle to build a life, the longing for home. He uses deep Greek with proverbs and village expressions. Navigate emotional storytelling, show empathy, and connect his story to your experience.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['xenitia', 'patrida', 'nostalgia', 'chorio', 'thalassa', 'epistrofi'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-identity-l10',
    title: 'Greek-American Identity',
    blurb: 'Discuss what being Greek abroad means',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-el-stories-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'A cousin visiting from Athens says your Greek sounds "xeno" (foreign). Have a deep conversation about what Hellenism means in the diaspora, whether language defines identity, and how Greek culture transforms when transplanted abroad. Use elevated Greek for philosophical concepts.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['ellinismos', 'taftotita', 'glossa', 'politismos', 'rizes', 'diaspora'],
    difficulty: 'core',
    culturalContext: { region: 'GR', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-el-community-l11',
    title: 'Greek Festival Committee',
    blurb: 'Help organize the annual Greek festival',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 5,
    prerequisites: ['heritage-el-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'The Greek Orthodox church community asks you to help organize the annual Greek Festival. Coordinate with yiayiades about pastries, discuss entertainment with the priest in formal Greek, and manage younger volunteers. Navigate between formal ecclesiastical Greek and casual diaspora speech.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['panigiri', 'ekklisia', 'koinotita', 'organosi', 'paradosi', 'ethelontis'],
    difficulty: 'challenge',
    culturalContext: { region: 'GR', category: 'celebration' },
    heritageMode: true,
  },
]
