import type { ConversationSeed } from '../types'

/**
 * Persian Heritage Seeds — Iranian diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Farsi and English, informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_FA: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-fa-family-l01',
    title: 'Salam Maman Bozorg',
    blurb: 'Greet your grandmother in Farsi',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Maman Bozorg (grandmother) who greets you with "Salam azizam!" and kisses both your cheeks. She asks "Chetori?" and insists you eat something immediately. Practice basic Farsi greetings and family endearments while mixing in English naturally.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['salam', 'maman-bozorg', 'azizam', 'chetori', 'mersi', 'joon'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-food-l02',
    title: 'Making Tahdig with Maman',
    blurb: 'Learn to cook crispy rice with your mother',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-fa-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Maman is making tahdig (crispy rice) and ghormeh sabzi. She gives instructions in Farsi — "beriz," "ham bezan." You help in the kitchen, learning food vocabulary and cooking verbs while she code-switches naturally between Farsi and English.',
    targetGrammar: ['imperatives', 'present-simple', 'quantifiers'],
    targetVocab: ['tahdig', 'berenj', 'sabzi', 'namak', 'piaz', 'goosht'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-nowruz-l03',
    title: 'Setting the Haft-Sin',
    blurb: 'Prepare the Nowruz table with your family',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-fa-food-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family is setting up the Haft-Sin table for Nowruz. Baba explains what each item symbolizes — sabzeh, samanu, senjed. You help arrange items and discuss which relatives are coming for the celebration. Practice Nowruz vocabulary while code-switching naturally.',
    targetGrammar: ['present-continuous', 'conjunctions', 'there-is-are'],
    targetVocab: ['nowruz', 'haft-sin', 'sabzeh', 'senjed', 'samanu', 'eid'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-taarof-l04',
    title: 'The Art of Taarof',
    blurb: 'Navigate Persian politeness rituals with guests',
    level: 4,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-fa-nowruz-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'Guests arrive at your home. Your parents model taarof — insisting guests sit, offering tea multiple times, refusing compliments. You observe and participate, learning when to say "befarmayid," "ghabel nadare," and "lotf darid." Practice the dance of Persian politeness.',
    targetGrammar: ['modals-should', 'imperatives', 'questions-indirect'],
    targetVocab: ['taarof', 'befarmayid', 'ghabel-nadare', 'lotf', 'mehman', 'chai'],
    difficulty: 'practice',
    culturalContext: { region: 'IR', category: 'social' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-fa-sizdah-l05',
    title: 'Sizdah Bedar Picnic',
    blurb: 'Spend the 13th day of Nowruz outdoors with family',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-fa-taarof-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'It is Sizdah Bedar — the 13th day of Nowruz. Your extended family goes to the park for a picnic. Amoo (uncle) plays backgammon, Khaleh (aunt) prepares ash reshteh. You throw your sabzeh in the stream and tie knots for wishes. Navigate family conversations in Farsi.',
    targetGrammar: ['present-continuous', 'modals-must', 'connectors'],
    targetVocab: ['sizdah-bedar', 'sabzeh', 'amoo', 'khaleh', 'gereh', 'arezoo'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-poetry-l06',
    title: 'Baba Reads Hafez',
    blurb: 'Experience faal-e Hafez with your father',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-fa-sizdah-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'After dinner, your Baba opens the Divan of Hafez for a faal (fortune). He reads the poem aloud in beautiful Farsi and explains its meaning. Discuss what the poem might mean for your life, learning poetic vocabulary and the tradition of consulting Hafez.',
    targetGrammar: ['present-perfect', 'relative-clauses', 'connectors'],
    targetVocab: ['hafez', 'faal', 'ghazal', 'divan', 'sher', 'mana'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-explain-l07',
    title: 'Explaining Yalda Night',
    blurb: 'Describe Shab-e Yalda to a non-Iranian friend',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-fa-poetry-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'A friend sees your family\'s Yalda Night photos — pomegranates, watermelon, poetry books. You explain the longest night celebration, why Iranians stay up reading Hafez, and what each food symbolizes. Use Farsi terms for concepts that don\'t translate well to English.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['yalda', 'anar', 'hendevaneh', 'sher-khani', 'ajeel', 'shab'],
    difficulty: 'practice',
    culturalContext: { region: 'IR', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-fa-stories-l09',
    title: 'Pedar Bozorg\'s Tehran',
    blurb: 'Hear your grandfather\'s memories of pre-revolution Iran',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-fa-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Pedar Bozorg (grandfather) reminisces about Tehran in his youth — the bazaar, the mountains, the neighborhoods. He uses rich literary Farsi mixed with nostalgia. Navigate understanding his memories, asking about family history, and connecting past to present.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['bazar', 'kucheh', 'mahalleh', 'khaterat', 'javani', 'vatan'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-identity-l10',
    title: 'Iranian or Persian?',
    blurb: 'Discuss diaspora identity and cultural labels',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 6,
    prerequisites: ['heritage-fa-stories-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'At a family gathering, a debate starts: do you call yourself Iranian or Persian abroad? Your Dayi (uncle) and Maman disagree. Engage in a nuanced discussion about identity, language preservation, and what it means to carry Iranian culture while living elsewhere. Use elevated Farsi.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['hoviyat', 'farhang', 'zaban', 'irani', 'gharb', 'risheh'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-fa-community-l11',
    title: 'Organizing a Nowruz Gala',
    blurb: 'Help plan a community Nowruz celebration event',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-fa-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'The local Iranian community association asks you to help organize their annual Nowruz gala. Coordinate with older community members in formal Farsi, discuss entertainment options, manage budgets, and present plans. Navigate between respectful formal Farsi and casual code-switching with peers.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['jashn', 'barnameh', 'anjoman', 'hamkari', 'ehteram', 'mehmani'],
    difficulty: 'challenge',
    culturalContext: { region: 'IR', category: 'celebration' },
    heritageMode: true,
  },
]
