import type { ConversationSeed } from '../types'

/**
 * Hindi Heritage Seeds — Indian diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Hindi and English (Hinglish), informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_HI: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-hi-family-l01',
    title: 'Namaste Nani-ji',
    blurb: 'Greet your grandmother and ask about her health',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Nani-ji who lives with your family. She greets you with "Arre beta, aa gaye!" and asks if you have eaten. Practice basic Hindi greetings and family terms while mixing in English as you naturally would at home.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['namaste', 'nani-ji', 'beta', 'khana', 'theek', 'paani'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-diwali-l02',
    title: 'Diwali Preparations',
    blurb: 'Help your family get ready for Diwali celebrations',
    level: 2,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-hi-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family is decorating for Diwali. Mummy is making rangoli, Papa is hanging lights. You help arrange diyas and discuss what mithai to buy. Practice Diwali vocabulary and follow instructions in Hindi.',
    targetGrammar: ['imperatives', 'present-continuous', 'conjunctions'],
    targetVocab: ['diya', 'rangoli', 'mithai', 'patakhe', 'puja', 'lakshmi'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-kitchen-l03',
    title: 'Dadaji\'s Secret Recipe',
    blurb: 'Learn a family recipe from your grandfather',
    level: 3,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-hi-diwali-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Dadaji is teaching you how to make his famous dal. He gives instructions in Hindi, naming spices and techniques he learned from his mother. You ask questions, mixing Hindi and English, as he patiently corrects your pronunciation of spice names.',
    targetGrammar: ['imperatives', 'present-simple', 'quantifiers'],
    targetVocab: ['dal', 'haldi', 'jeera', 'mirch', 'tadka', 'namak'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-temple-l04',
    title: 'Sunday at the Mandir',
    blurb: 'Participate in a temple visit with your family',
    level: 4,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-hi-kitchen-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family goes to the local mandir on Sunday. Aunty-ji asks about your studies, Uncle-ji tells a story from the Ramayana. You navigate polite conversation with community elders while your parents nudge you to speak more Hindi.',
    targetGrammar: ['past-simple', 'modals-should', 'questions-wh'],
    targetVocab: ['mandir', 'puja', 'prasad', 'aarti', 'pandit-ji', 'bhagwan'],
    difficulty: 'practice',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-hi-wedding-l05',
    title: 'Bhai\'s Sangeet Night',
    blurb: 'Perform at your brother\'s wedding sangeet',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-hi-temple-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your brother is getting married and it is the sangeet night. Your cousins are choreographing a Bollywood dance number. Bua-ji insists everyone sings. Navigate coordinating with cousins in Hinglish while impressing Dadi with your Hindi film song knowledge.',
    targetGrammar: ['present-continuous', 'modals-must', 'connectors'],
    targetVocab: ['sangeet', 'mehendi', 'dulha', 'baraat', 'shaadi', 'gaana'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-bollywood-l06',
    title: 'Movie Night with Mummy',
    blurb: 'Discuss a Bollywood film with your mother',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-hi-wedding-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'You watch a classic Bollywood film with your Mummy. She explains the cultural references you miss, comments on the dialogues, and shares memories of watching this film as a child in India. Discuss the plot and characters using Hindi film vocabulary.',
    targetGrammar: ['past-simple', 'relative-clauses', 'comparatives'],
    targetVocab: ['film', 'gaana', 'hero', 'heroine', 'dialogue', 'zamana'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-explain-l07',
    title: 'Explaining Holi to Friends',
    blurb: 'Describe the festival of colors to non-Indian friends',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-hi-bollywood-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your friends ask about the colorful photos on your social media from Holi. Explain the significance of the festival, what gujiya is, why people play with colors, and invite them next year. Use Hindi terms naturally when English equivalents feel inadequate.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['holi', 'rang', 'gulal', 'gujiya', 'thandai', 'bura-na-mano'],
    difficulty: 'practice',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-hi-generation-l09',
    title: 'Nana-ji\'s Partition Stories',
    blurb: 'Listen to your grandfather share stories of his childhood',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-hi-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Nana-ji shares stories of his family\'s journey during Partition. He speaks in a mix of literary Hindi and colloquial expressions. Navigate emotional vocabulary, historical references, and show empathy while asking sensitive questions about family history.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['vibhajan', 'desh', 'yaadein', 'ghar', 'safar', 'kismet'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-identity-l10',
    title: 'ABCD and Proud',
    blurb: 'Discuss what it means to be a diasporic Indian',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-hi-generation-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Chacha visiting from India comments on how "American" you have become. Engage in a nuanced conversation about identity, cultural preservation, and what being Indian means when you grew up abroad. Use sophisticated Hindi for abstract concepts.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['sanskriti', 'pehchaan', 'parampara', 'videsh', 'apnapan', 'roots'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-hi-community-l11',
    title: 'Organizing Navratri Garba',
    blurb: 'Help plan a community Navratri event',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 5,
    prerequisites: ['heritage-hi-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'You are helping the Indian community association organize a Navratri Garba night. Coordinate with aunties about food, negotiate with the venue in English, and present the event plan to community elders in formal Hindi. Navigate multiple registers and audiences.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['garba', 'dandiya', 'navratri', 'aayojan', 'samaj', 'yogdaan'],
    difficulty: 'challenge',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },
]
