import type { ConversationSeed } from '../types'

/**
 * Punjabi Heritage Seeds — Punjabi diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Punjabi and English, informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_PA: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-pa-family-l01',
    title: 'Sat Sri Akal, Bebe-ji',
    blurb: 'Greet your grandmother in Punjabi',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Bebe-ji (grandmother) who greets you with "Sat Sri Akal, puttar!" and immediately asks if you are hungry. Practice basic Punjabi greetings and family terms while mixing in English as you naturally would at home.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['sat-sri-akal', 'bebe-ji', 'puttar', 'roti', 'theek', 'kiddan'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-kitchen-l02',
    title: 'Bebe\'s Makki di Roti',
    blurb: 'Learn to make traditional Punjabi bread with grandma',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-pa-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Bebe-ji is making makki di roti and sarson da saag. She insists you learn before you "forget everything." Follow her instructions in Punjabi, ask about ingredients, and practice kitchen vocabulary while she lovingly corrects your pronunciation.',
    targetGrammar: ['imperatives', 'present-simple', 'quantifiers'],
    targetVocab: ['makki', 'sarson', 'saag', 'ghee', 'tawa', 'atta'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-vaisakhi-l03',
    title: 'Vaisakhi at the Gurdwara',
    blurb: 'Celebrate Vaisakhi with your family',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-pa-kitchen-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family goes to the Gurdwara for Vaisakhi. Baba-ji explains the significance of the day, you sit for langar, and meet relatives. Practice discussing the celebration, understanding kirtan lyrics, and greeting community members in Punjabi.',
    targetGrammar: ['past-simple', 'present-continuous', 'conjunctions'],
    targetVocab: ['vaisakhi', 'gurdwara', 'langar', 'kirtan', 'seva', 'ardas'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-bhangra-l04',
    title: 'Bhangra Practice with Cousins',
    blurb: 'Learn bhangra moves from your cousins',
    level: 4,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-pa-vaisakhi-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your cousins are practicing bhangra for a family wedding. They teach you the moves using Punjabi instructions — "pairi pauna," "dhol te nach." Joke around in Punglish (Punjabi-English) while they tease your moves and encourage you to feel the beat.',
    targetGrammar: ['imperatives', 'present-continuous', 'modals-can'],
    targetVocab: ['bhangra', 'dhol', 'gidda', 'nach', 'taali', 'jhoomer'],
    difficulty: 'practice',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-pa-wedding-l05',
    title: 'Maasi\'s Daughter\'s Wedding',
    blurb: 'Navigate a full Punjabi wedding celebration',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-pa-bhangra-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Maasi\'s daughter is getting married. The mehendi, sangeet, and Anand Karaj are happening over three days. Your Taayi gives instructions about what to wear, Chaacha arranges transport. Navigate the wedding chaos in Punjabi with family while explaining things to friends in English.',
    targetGrammar: ['present-continuous', 'modals-must', 'connectors'],
    targetVocab: ['vivaah', 'chunni', 'mehndi', 'doli', 'viah', 'milni'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-farm-l06',
    title: 'Papa\'s Pind Stories',
    blurb: 'Listen to your father talk about village life',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-pa-wedding-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'On a drive, your Papa tells stories about growing up in the pind (village). He describes the khet (fields), his school friends, and how life was different. Ask questions about his childhood in Punjabi, understanding both nostalgic vocabulary and farming terms.',
    targetGrammar: ['past-simple', 'used-to', 'relative-clauses'],
    targetVocab: ['pind', 'khet', 'kisaan', 'vehda', 'kanak', 'zameen'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-explain-l07',
    title: 'Explaining Langar to Friends',
    blurb: 'Describe the Sikh community kitchen tradition',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-pa-farm-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'You bring a friend to langar at the Gurdwara. Explain what langar is, its significance of equality, the seva involved, and proper etiquette — covering your head, sitting on the floor. Use Punjabi terms naturally while explaining in English, showing pride in the tradition.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['langar', 'seva', 'pangat', 'sangat', 'golak', 'barabar'],
    difficulty: 'practice',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-pa-history-l09',
    title: 'Baba-ji\'s Migration Story',
    blurb: 'Hear your great-grandfather\'s journey to a new country',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-pa-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Baba-ji shares the story of how the family left Punjab — the decision, the journey, building a life in a new land. He speaks in deep Punjabi with proverbs and old expressions. Navigate emotional vocabulary and historical references while connecting his story to your present.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['hijrat', 'watan', 'ghar', 'sapne', 'mehnat', 'himmat'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-identity-l10',
    title: 'Punjabi and Proud Abroad',
    blurb: 'Discuss cultural identity with a visiting relative',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-pa-history-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Phuphar visiting from Amritsar comments that young people abroad are "losing their Punjabiyat." Engage in a thoughtful conversation about maintaining language, culture, and identity while building a life in a different country. Use elevated Punjabi for cultural concepts.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['punjabiyat', 'virsa', 'pehchaan', 'maa-boli', 'kaum', 'reet'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-pa-community-l11',
    title: 'Nagar Kirtan Planning',
    blurb: 'Help organize a community Sikh procession',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 5,
    prerequisites: ['heritage-pa-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'The local Gurdwara committee asks you to help coordinate the annual Nagar Kirtan. Speak formally with senior committee members, coordinate with the city council in English, and rally young volunteers in casual Punjabi. Navigate between formal Punjabi, English, and code-switching.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['nagar-kirtan', 'committee', 'prabandh', 'sangat', 'sarbat-da-bhala', 'charhdi-kala'],
    difficulty: 'challenge',
    culturalContext: { region: 'IN', category: 'celebration' },
    heritageMode: true,
  },
]
