import type { ConversationSeed } from '../types'

/**
 * Portuguese Heritage Seeds — Brazilian/Portuguese diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Portuguese and English (Portunglês), informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_PT: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-pt-family-l01',
    title: 'Oi, Vovó!',
    blurb: 'Greet your Brazilian grandmother warmly',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Vovó (grandmother) who greets you with "Oi, meu amor! Tudo bem?" and immediately offers food. She asks about school and your friends. Practice basic Portuguese greetings and family terms while mixing in English as you naturally would at home.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['vovo', 'oi', 'tudo-bem', 'meu-amor', 'obrigado', 'beijo'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-food-l02',
    title: 'Vovó\'s Brigadeiro',
    blurb: 'Make chocolate truffles with your grandmother',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-pt-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Vovó teaches you to make brigadeiro — rolling the chocolate balls in granulado. She gives instructions in Portuguese: "Mexe sem parar," "Tá no ponto." Practice cooking vocabulary and follow her steps while she tells stories of birthday parties in Brazil.',
    targetGrammar: ['imperatives', 'present-simple', 'quantifiers'],
    targetVocab: ['brigadeiro', 'leite-condensado', 'chocolate', 'granulado', 'panela', 'colher'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-festa-l03',
    title: 'Festa Junina at Church',
    blurb: 'Attend a Brazilian June festival celebration',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-pt-food-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'The Brazilian community holds a Festa Junina at the local church. There is forró music, quadrilha dancing, and quentão (hot drink). Tia (auntie) drags you to dance, Tio serves paçoca. Navigate the celebration using Portuguese with family and English with friends.',
    targetGrammar: ['present-continuous', 'past-simple', 'conjunctions'],
    targetVocab: ['festa-junina', 'forro', 'quadrilha', 'pamonha', 'quentao', 'fogueira'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-call-l04',
    title: 'Video Call to Vovô in São Paulo',
    blurb: 'Chat with your grandfather in Brazil',
    level: 4,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-pt-festa-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'You call your Vovô (grandfather) in São Paulo. He asks about your life, tells you about the latest futebol match, and reminds you to "não esquecer o português." Practice maintaining a conversation while he gently encourages more Portuguese and less English.',
    targetGrammar: ['past-simple', 'questions-wh', 'future-will'],
    targetVocab: ['vovo', 'futebol', 'saudade', 'escola', 'ferias', 'visitar'],
    difficulty: 'practice',
    culturalContext: { region: 'BR', category: 'family' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-pt-carnaval-l05',
    title: 'Carnaval at the Community',
    blurb: 'Celebrate Carnaval with the Brazilian diaspora',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-pt-call-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'The local Brazilian community holds a Carnaval party. Tia teaches samba steps, everyone sings marchinhas, and Prima (cousin) explains the blocos tradition. Navigate the celebration, using Portuguese for singing and dancing instructions while explaining the culture to curious friends.',
    targetGrammar: ['present-continuous', 'modals-must', 'connectors'],
    targetVocab: ['carnaval', 'samba', 'marchinha', 'bloco', 'fantasia', 'bateria'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-saudade-l06',
    title: 'Saudade Conversations with Mamãe',
    blurb: 'Discuss missing Brazil with your mother',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-pt-carnaval-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Mamãe looks at old photos from Brazil and gets nostalgic. She describes her childhood — the praia, the vizinhos, the feira on Saturdays. You ask questions about life before immigration. Practice understanding emotional vocabulary and the untranslatable concept of "saudade."',
    targetGrammar: ['past-simple', 'used-to', 'relative-clauses'],
    targetVocab: ['saudade', 'praia', 'vizinhos', 'feira', 'infancia', 'lembranças'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-explain-l07',
    title: 'Explaining Capoeira',
    blurb: 'Describe the art of capoeira to a friend',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-pt-saudade-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'You bring a friend to watch a capoeira roda at the Brazilian cultural center. Explain the history — how it was disguised as dance, the berimbau, the ginga, and the songs. Use Portuguese terms for movements and instruments while giving historical context in English.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['capoeira', 'roda', 'berimbau', 'ginga', 'mestre', 'mandinga'],
    difficulty: 'practice',
    culturalContext: { region: 'BR', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-pt-stories-l09',
    title: 'Vovô\'s Immigration Story',
    blurb: 'Hear your grandfather\'s journey from Brazil',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-pt-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Vovô tells the story of leaving Brazil — the decision, the airplane, arriving with two suitcases and a dream. He uses rich Portuguese with expressions from his era. Navigate emotional storytelling, understand his sacrifices, and connect his journey to your family\'s present.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['imigracao', 'sonho', 'sacrificio', 'coragem', 'destino', 'esperanca'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-identity-l10',
    title: 'Brazilian or American?',
    blurb: 'Discuss diaspora identity with family',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 6,
    prerequisites: ['heritage-pt-stories-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'A primo (cousin) visiting from Rio says "Você não é brasileiro de verdade." Engage in a deep conversation about what makes someone Brazilian, whether language defines identity, the tension between assimilation and preservation, and what "home" means across borders. Use elevated Portuguese.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['identidade', 'raizes', 'pertencimento', 'cultura', 'lingua', 'patria'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-pt-community-l11',
    title: 'Brazilian Independence Day Festival',
    blurb: 'Organize a community celebration of Sete de Setembro',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-pt-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'The Brazilian community association asks you to help organize the Sete de Setembro celebration. Coordinate with older community members in formal Portuguese, arrange food vendors and music, and present plans. Navigate formal Portuguese with elders, Portunglês with peers, and English with local officials.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['independencia', 'comunidade', 'organizacao', 'celebracao', 'uniao', 'patria'],
    difficulty: 'challenge',
    culturalContext: { region: 'BR', category: 'celebration' },
    heritageMode: true,
  },
]
