/**
 * Learner Memory — cross-session AI memory & user note.
 *
 * $0 design:
 * - AI memory = single string field on existing user_preferences doc
 * - User note = single string (~500 chars) on same doc
 * - localStorage fallback for offline resilience
 * - No extra API calls to Gemini — memory flows from existing responses
 */

import { databases } from '../api/appwrite'
import { Permission, Role } from 'appwrite'
import { APPWRITE_DB_ID, COLLECTION_IDS } from '../appwrite-schema'

// ─── Constants ──────────────────────────────────────────────────────────────

const MAX_MEMORY_WORDS = 150
const MAX_NOTE_CHARS = 500
const MEMORY_KEY = (uid: string | null) => `talkingo_lifeline_${uid || 'anon'}`
const NOTE_KEY = (uid: string | null) => `talkingo_usernote_${uid || 'anon'}`

// ─── AI Memory (single paragraph, auto-generated by Gemini) ─────────────────

export function loadLocalLifeline(userId: string | null): string {
  try {
    return localStorage.getItem(MEMORY_KEY(userId)) || ''
  } catch {
    return ''
  }
}

export function saveLocalLifeline(userId: string | null, text: string): void {
  try {
    const compacted = compactMemory(text)
    localStorage.setItem(MEMORY_KEY(userId), compacted)
  } catch {
    // localStorage quota exceeded — silently ignore
  }
}

export function compactMemory(text: string): string {
  const words = text.trim().split(/\s+/)
  if (words.length <= MAX_MEMORY_WORDS) return text.trim()
  return words.slice(0, MAX_MEMORY_WORDS).join(' ') + '.'
}

// ─── User Note (single text, user-written) ─────────────────────────────────

export function loadLocalUserNote(userId: string | null): string {
  try {
    return localStorage.getItem(NOTE_KEY(userId)) || ''
  } catch {
    return ''
  }
}

export function saveLocalUserNote(userId: string | null, text: string): void {
  try {
    const trimmed = text.trim().slice(0, MAX_NOTE_CHARS)
    localStorage.setItem(NOTE_KEY(userId), trimmed)
  } catch {
    // ignore quota errors
  }
}

// ─── Appwrite sync (fields on user_preferences) ────────────────────────────

const DATABASE_ID = APPWRITE_DB_ID
const PREFERENCES_COLLECTION = COLLECTION_IDS.USER_PREFERENCES

/**
 * Save AI memory + user note to Appwrite's user_preferences doc.
 * Fire-and-forget (catches errors silently) — $0 friendly.
 */
export async function syncMemoryToAppwrite(
  userId: string,
  memoryLifeline: string,
  userNote: string
): Promise<void> {
  if (!userId) return
  try {
    await databases.updateDocument(DATABASE_ID, PREFERENCES_COLLECTION, userId, {
      memoryLifeline: compactMemory(memoryLifeline || ''),
      userNote,
      updatedAt: Date.now(),
    })
  } catch (error: any) {
    // Document may not exist yet (user hasn't completed onboarding)
    const status = error?.code ?? error?.status ?? 0
    if (status === 404) {
      try {
        await databases.createDocument(
          DATABASE_ID,
          PREFERENCES_COLLECTION,
          userId,
          {
            userId,
            memoryLifeline: compactMemory(memoryLifeline || ''),
            userNote,
            createdAt: Date.now(),
            updatedAt: Date.now(),
          },
          [
            Permission.read(Role.user(userId)),
            Permission.update(Role.user(userId)),
            Permission.delete(Role.user(userId)),
          ]
        )
      } catch {
        // non-critical — will sync next time
      }
    }
  }
}

/**
 * Load AI memory + user note from Appwrite.
 * Returns { memoryLifeline, userNote } or empty defaults.
 */
export async function loadMemoryFromAppwrite(
  userId: string
): Promise<{ memoryLifeline: string; userNote: string }> {
  if (!userId) return { memoryLifeline: '', userNote: '' }
  try {
    const doc = await databases.getDocument(DATABASE_ID, PREFERENCES_COLLECTION, userId)
    const data = doc as any
    return {
      memoryLifeline: (data.memoryLifeline as string) || '',
      userNote: (data.userNote as string) || '',
    }
  } catch {
    return { memoryLifeline: '', userNote: '' }
  }
}
