/**
 * Cultural scenario seeds for Egyptian Arabic (ar-EG)
 * Covers souks, street food, Nile culture, social customs, and celebrations.
 */
import type { ConversationSeed } from '../types'

export const arEGCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'ar-eg-food-l01',
    title: 'Koshary Corner',
    blurb: 'Order koshary from a busy street vendor',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You stop at a popular koshary cart in downtown Cairo. The vendor asks if you want extra sauce and lentils. You place your order using simple phrases.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['koshary', 'salsa', 'ads', 'shariya', 'makarona'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'food', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-social-l01',
    title: 'Ahwa Morning',
    blurb: 'Greet regulars at a traditional coffee shop',
    level: 1,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You sit at the local ahwa for morning coffee. The waiter knows the regulars by name. You greet him and order your usual.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['ahwa', 'ahlan', 'shay', 'ahwe', 'shisha'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'social', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-market-l02',
    title: 'Khan el-Khalili Souk',
    blurb: 'Bargain for souvenirs in Cairo\'s famous souk',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You browse the colorful alleys of Khan el-Khalili. Merchants display spices, perfume, and copper ware. You inquire about a decorative lantern.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['souk', 'fanoos', 'bakhoor', 'se3r', 'fassaal'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'market', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-transport-l03',
    title: 'Cairo Taxi Ride',
    blurb: 'Give directions to a taxi driver through Cairo traffic',
    level: 3,
    spiralGroup: 'transport-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You hail a taxi and negotiate the fare to Zamalek. The driver chats about football while you navigate through busy intersections together.',
    targetGrammar: ['prepositions-place', 'imperatives'],
    targetVocab: ['taxi', 'agra', 'share3', 'midan', 'zahma'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'social', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-food-l04',
    title: 'Ful and Taamiya Breakfast',
    blurb: 'Chat over a classic Egyptian breakfast',
    level: 4,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['ar-eg-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'At a local fuul shop, you and a friend share plates of ful medames, taamiya, and fresh bread. You discuss morning routines and plans for the day.',
    targetGrammar: ['have-has', 'like-gerund'],
    targetVocab: ['ful', 'taamiya', 'eish', 'zibda', 'torshi'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'food', dialectConstraint: 'ar-EG' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'ar-eg-celebration-l05',
    title: 'Ramadan Iftar Gathering',
    blurb: 'Break fast with neighbors during Ramadan',
    level: 5,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'The cannon fires at sunset and the neighborhood breaks fast together on a table set in the alley. You pass dishes and exchange warm Ramadan greetings.',
    targetGrammar: ['present-perfect', 'future-going-to'],
    targetVocab: ['iftar', 'ramadan', 'midfa3', 'tamr', 'konafa'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'celebration', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-social-l06',
    title: 'Nile Felucca Evening',
    blurb: 'Enjoy a felucca ride and chat with the captain',
    level: 6,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['ar-eg-social-l01'],
    category: 'Social',
    scenarioBrief:
      'You board a felucca at sunset. The captain tells stories of the Nile while maneuvering the sail. You ask about his life on the water.',
    targetGrammar: ['past-simple', 'questions-indirect'],
    targetVocab: ['felucca', 'neel', 'ra2is', 'shira3', 'ghuroob'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'social', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-business-l07',
    title: 'Spice Trade Negotiation',
    blurb: 'Negotiate bulk spice prices with a wholesaler',
    level: 7,
    spiralGroup: 'market-culture',
    spiralOrder: 2,
    prerequisites: ['ar-eg-market-l02'],
    category: 'Work & Study',
    scenarioBrief:
      'In the old spice quarter, you negotiate saffron and cumin prices with a wholesaler. He offers tea while discussing quality grades and delivery terms.',
    targetGrammar: ['conditional-first', 'comparatives'],
    targetVocab: ['baharat', 'za3faran', 'kammoun', 'gomla', 'kamiya'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'market', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-family-l07',
    title: 'Family Friday Lunch',
    blurb: 'Gather with extended family for the weekly lunch',
    level: 7,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'Every Friday, the family gathers at teta\'s apartment. Dishes of molokhiya and mahshi fill the table. Conversations flow between generations.',
    targetGrammar: ['present-perfect-continuous', 'relative-clauses'],
    targetVocab: ['teta', 'molokhiya', 'mahshi', 'el-gom3a', '3ila'],
    difficulty: 'practice',
    culturalContext: { region: 'EG', category: 'family', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-celebration-l08',
    title: 'Moulid Celebration',
    blurb: 'Experience the sights and sounds of a local moulid festival',
    level: 8,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['ar-eg-celebration-l05'],
    category: 'Culture & Deep',
    scenarioBrief:
      'You attend a local moulid with its tents, sweets, and dhikr circles. Neighbors explain traditions and you discuss the cultural significance of the celebration.',
    targetGrammar: ['passive-present', 'gerunds'],
    targetVocab: ['moulid', 'halawa', 'dhikr', 'khaima', 'mawlid'],
    difficulty: 'challenge',
    culturalContext: { region: 'EG', category: 'celebration', dialectConstraint: 'ar-EG' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'ar-eg-social-l09',
    title: 'Cinema Industry Discussion',
    blurb: 'Discuss Egyptian cinema and its golden age',
    level: 9,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'At a film club screening, cinephiles discuss classic Egyptian films. You compare golden age directors with modern filmmakers and debate cultural influence.',
    targetGrammar: ['discourse-markers', 'hedging'],
    targetVocab: ['sinema', 'film', 'mokhrig', '3asr-zahabi', 'naqd'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'social', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-business-l10',
    title: 'Tech Hub Pitch',
    blurb: 'Present a tech solution at a Cairo innovation hub',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'At a Cairo tech incubator, you present your fintech idea to mentors and investors. You explain the market gap and revenue model in Egyptian business language.',
    targetGrammar: ['passive-present', 'conditional-second'],
    targetVocab: ['teknolojya', 'istismar', 'souq', 'mashrou3', 'tamweel'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'business', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-culture-l10',
    title: 'Umm Kulthum Legacy',
    blurb: 'Analyze the musical and cultural legacy of Umm Kulthum',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 2,
    prerequisites: ['ar-eg-social-l09'],
    category: 'Culture & Deep',
    scenarioBrief:
      'Music lovers debate Umm Kulthum\'s influence on Arab culture, her vocal technique, and why her concerts still move millions decades later.',
    targetGrammar: ['subjunctive', 'nominalization'],
    targetVocab: ['tarab', 'musiqa', 'haflah', 'sawt', 'turath'],
    difficulty: 'challenge',
    culturalContext: { region: 'EG', category: 'social', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-social-l11',
    title: 'Youth and Tradition',
    blurb: 'Navigate generational differences in modern Cairo',
    level: 11,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'Young professionals in Cairo discuss balancing traditional family expectations with modern ambitions. You mediate perspectives with nuanced argumentation.',
    targetGrammar: ['reported-speech', 'conditional-mixed'],
    targetVocab: ['shabab', 'taqalid', 'tahaddi', 'mustaqbal', 'hurriya'],
    difficulty: 'core',
    culturalContext: { region: 'EG', category: 'social', dialectConstraint: 'ar-EG' },
  },
  {
    id: 'ar-eg-celebration-l12',
    title: 'Sufi Dhikr Gathering',
    blurb: 'Discuss Sufi traditions and spiritual gatherings in Egypt',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 3,
    prerequisites: ['ar-eg-celebration-l08'],
    category: 'Culture & Deep',
    scenarioBrief:
      'After attending a Sufi dhikr at a Cairo shrine, scholars discuss the philosophy of remembrance, its history in Egypt, and its contemporary relevance.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['tasawwuf', 'dhikr', 'tariqah', 'maqam', 'wilaya'],
    difficulty: 'challenge',
    culturalContext: { region: 'EG', category: 'celebration', dialectConstraint: 'ar-EG' },
  },
]
