/**
 * Cultural scenario seeds for Gulf Arabic (ar-SA)
 * Covers business, hospitality, pearl diving heritage, markets, and celebrations.
 */
import type { ConversationSeed } from '../types'

export const arSACulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'ar-sa-food-l01',
    title: 'Arabic Coffee Ceremony',
    blurb: 'Accept and enjoy Arabic coffee in a traditional majlis',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You are invited to a neighbor\'s majlis. The host pours gahwa from a dallah and offers dates. You accept gracefully and exchange basic pleasantries.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['gahwa', 'dallah', 'tamr', 'majlis', 'tafaddal'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'food', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-social-l02',
    title: 'Souq Al-Zal Visit',
    blurb: 'Browse a traditional market for incense and textiles',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You walk through Souq Al-Zal in Riyadh, examining oud, bakhoor, and bisht fabrics. The vendor explains the quality and origin of each item.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['souq', 'oud', 'bakhoor', 'bisht', 'si3r'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'market', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-social-l02',
    title: 'Greeting at a Gathering',
    blurb: 'Practice formal Gulf greetings at a social event',
    level: 2,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You attend a family gathering where elders are present. You greet each person with the appropriate nose-touch or handshake and inquire about their wellbeing.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['hala', 'keef-halak', 'alhamdulillah', 'mashallah', 'inshallah'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'social', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-food-l03',
    title: 'Kabsa Dinner',
    blurb: 'Enjoy a traditional kabsa meal with family',
    level: 3,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['ar-sa-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'The family gathers around a large tray of kabsa. You eat with your right hand, share the best pieces, and compliment the cook on the spice blend.',
    targetGrammar: ['past-simple', 'adjectives-basic'],
    targetVocab: ['kabsa', 'lahem', 'bahar', 'ruz', 'dayf'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'food', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-family-l04',
    title: 'Weekend Desert Trip',
    blurb: 'Plan a desert camping trip with cousins',
    level: 4,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You plan a kashta with your cousins. Discussion covers where to camp, what food to bring, and who drives the 4x4. Excitement builds.',
    targetGrammar: ['future-going-to', 'have-has'],
    targetVocab: ['kashta', 'sahra', 'khaima', 'hatab', 'naqa'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'family', dialectConstraint: 'ar-SA' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'ar-sa-business-l05',
    title: 'Office Introductions',
    blurb: 'Meet new colleagues in a formal office setting',
    level: 5,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'You start a new position at a company in Riyadh. You introduce yourself to colleagues, exchange business cards, and navigate the formal yet warm Gulf business etiquette.',
    targetGrammar: ['present-perfect', 'modals-should'],
    targetVocab: ['shirkah', 'mudeer', 'maktab', 'tasharrafna', 'zameelk'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'business', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-celebration-l06',
    title: 'Eid Al-Fitr Celebrations',
    blurb: 'Visit relatives and exchange Eid greetings',
    level: 6,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'On Eid morning, you visit relatives in order of seniority. Each home offers sweets and coffee. You exchange eidiyat and well-wishes.',
    targetGrammar: ['present-perfect', 'past-simple'],
    targetVocab: ['eid', 'eidiyah', 'ziyara', 'mubaarak', 'halwa'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'celebration', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-business-l07',
    title: 'Contract Negotiation',
    blurb: 'Negotiate terms of a business deal over coffee',
    level: 7,
    spiralGroup: 'business-culture',
    spiralOrder: 2,
    prerequisites: ['ar-sa-business-l05'],
    category: 'Work & Study',
    scenarioBrief:
      'You meet a potential business partner in a hotel lobby. Over multiple rounds of coffee, you discuss partnership terms, timelines, and expectations — never rushing the process.',
    targetGrammar: ['conditional-first', 'modals-could'],
    targetVocab: ['3aqd', 'sharik', 'shurout', 'muda', 'ittifaq'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'business', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-social-l07',
    title: 'Camel Festival Stories',
    blurb: 'Discuss camel heritage at a festival gathering',
    level: 7,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['ar-sa-social-l02'],
    category: 'Culture & Deep',
    scenarioBrief:
      'At a camel festival, you sit with bedouin elders who share stories about desert navigation, camel breeding, and the old trading routes.',
    targetGrammar: ['past-continuous', 'reported-speech'],
    targetVocab: ['ibil', 'badw', 'sahra', 'qafila', 'nasab'],
    difficulty: 'practice',
    culturalContext: { region: 'SA', category: 'social', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-food-l08',
    title: 'Hosting a Formal Dinner',
    blurb: 'Host a formal majlis dinner for business guests',
    level: 8,
    spiralGroup: 'food-culture',
    spiralOrder: 3,
    prerequisites: ['ar-sa-food-l03'],
    category: 'Social',
    scenarioBrief:
      'You host a formal dinner for business associates. From the incense at the door to the serving order, you navigate Gulf hospitality protocols flawlessly.',
    targetGrammar: ['modals-must', 'passive-present'],
    targetVocab: ['dayfa', 'mathbakh', 'bakhoor', 'muqabbilat', 'karam'],
    difficulty: 'challenge',
    culturalContext: { region: 'SA', category: 'food', dialectConstraint: 'ar-SA' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'ar-sa-business-l09',
    title: 'Vision 2030 Discussion',
    blurb: 'Discuss economic diversification and modernization',
    level: 9,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'Colleagues discuss how Vision 2030 is changing work culture, entertainment, and opportunities. You share opinions about balancing tradition with modernization.',
    targetGrammar: ['discourse-markers', 'hedging'],
    targetVocab: ['ru2ya', 'tanawwu3', 'iqtisad', 'tatweer', 'fursa'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'business', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-culture-l10',
    title: 'Pearl Diving Heritage',
    blurb: 'Discuss the lost art of pearl diving with an elder',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'An elderly relative remembers when Gulf economies ran on pearls. He describes the diving seasons, the songs, and the social structure of the dhow crews.',
    targetGrammar: ['past-perfect', 'passive-past'],
    targetVocab: ['lu2lu2', 'ghaws', 'nawkhidha', 'dhow', 'firedj'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'social', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-social-l10',
    title: 'Nabati Poetry Circle',
    blurb: 'Appreciate and discuss traditional Nabati poetry',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 2,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'At a cultural event, poets recite nabati verses about honor, the desert, and love. You discuss the imagery and compare classical and modern styles.',
    targetGrammar: ['subjunctive', 'nominalization'],
    targetVocab: ['nabati', 'shi3r', 'qaseeda', 'ghazal', 'badia'],
    difficulty: 'challenge',
    culturalContext: { region: 'SA', category: 'social', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-business-l11',
    title: 'Cross-Border Investment',
    blurb: 'Discuss international investment opportunities',
    level: 11,
    spiralGroup: 'business-culture',
    spiralOrder: 3,
    prerequisites: ['ar-sa-business-l09'],
    category: 'Work & Study',
    scenarioBrief:
      'In a high-level meeting, you discuss cross-border investment strategies with partners from multiple Gulf states. The conversation demands diplomatic precision.',
    targetGrammar: ['conditional-mixed', 'reported-speech'],
    targetVocab: ['istismar', 'duwaliy', 'sandouq', 'makhater', 'a2id'],
    difficulty: 'core',
    culturalContext: { region: 'SA', category: 'business', dialectConstraint: 'ar-SA' },
  },
  {
    id: 'ar-sa-celebration-l12',
    title: 'Janadriyah Cultural Debate',
    blurb: 'Debate cultural identity at a heritage festival',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'At the Janadriyah heritage festival, intellectuals debate how to preserve Bedouin culture while embracing globalization. You present sophisticated arguments on both sides.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['turath', 'hawiya', '3awlama', 'asala', 'mu3asara'],
    difficulty: 'challenge',
    culturalContext: { region: 'SA', category: 'celebration', dialectConstraint: 'ar-SA' },
  },
]
