/**
 * Cultural scenario seeds for Swahili (East Africa)
 * Covers markets, community, safari, coast life, and celebrations.
 */
import type { ConversationSeed } from '../types'

export const swCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'sw-food-l01',
    title: 'Ordering at a Mama Ntilie',
    blurb: 'Order a meal at a local street food vendor',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You approach a popular mama ntilie stall at lunchtime. She has ugali, beans, and grilled fish. You greet her and place your order.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['ugali', 'maharagwe', 'samaki', 'chakula', 'karibu'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'food' },
  },
  {
    id: 'sw-social-l01',
    title: 'Morning Greetings',
    blurb: 'Exchange extended Swahili greetings with a neighbor',
    level: 1,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You meet your neighbor on the way to work. In Swahili culture, greetings are long and sincere — you ask about family, health, and the morning.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['habari', 'mambo', 'salama', 'familia', 'shikamoo'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'social' },
  },
  {
    id: 'sw-market-l02',
    title: 'Soko Bargaining',
    blurb: 'Negotiate prices for fruits and vegetables at the market',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'At the local soko, vendors display colorful fruits. You browse the stalls, ask prices, and negotiate friendly deals for mangoes and avocados.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['soko', 'bei', 'embe', 'parachichi', 'punguzo'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'market' },
  },
  {
    id: 'sw-transport-l03',
    title: 'Dala Dala Ride',
    blurb: 'Navigate public transport in Dar es Salaam',
    level: 3,
    spiralGroup: 'transport-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You board a crowded dala dala minibus. The conductor calls out stops and collects fares. You ask where to get off for the central market.',
    targetGrammar: ['prepositions-place', 'imperatives'],
    targetVocab: ['dala-dala', 'nauli', 'kituo', 'shuka', 'kondakta'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'social' },
  },
  {
    id: 'sw-family-l04',
    title: 'Visiting Bibi',
    blurb: 'Visit your grandmother in the village and help around the house',
    level: 4,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You travel to the village to visit bibi. She is happy to see you and tells stories while you help prepare the evening meal over a charcoal stove.',
    targetGrammar: ['past-simple', 'have-has'],
    targetVocab: ['bibi', 'kijiji', 'jiko', 'hadithi', 'msaada'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'family' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'sw-celebration-l05',
    title: 'Eid Festival in Zanzibar',
    blurb: 'Celebrate Eid with neighbors on the Swahili coast',
    level: 5,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'It is Eid morning in Stone Town. Neighbors exchange greetings and plates of pilau and mandazi. You join the festivities and visit multiple homes.',
    targetGrammar: ['present-perfect', 'future-going-to'],
    targetVocab: ['Eid', 'pilau', 'mandazi', 'sherehe', 'jirani'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'celebration' },
  },
  {
    id: 'sw-business-l06',
    title: 'Biashara Talk',
    blurb: 'Discuss a small business venture with a friend',
    level: 6,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'A friend proposes starting a phone accessories kiosk together. You discuss costs, location, and profit-sharing over afternoon tea at a local cafe.',
    targetGrammar: ['conditional-first', 'modals-should'],
    targetVocab: ['biashara', 'mtaji', 'faida', 'duka', 'mshirika'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'business' },
  },
  {
    id: 'sw-social-l06',
    title: 'Bao Game Afternoon',
    blurb: 'Play the traditional board game bao with a neighbor',
    level: 6,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['sw-social-l01'],
    category: 'Social',
    scenarioBrief:
      'Under a mango tree, elders play bao while younger neighbors watch and learn strategy. You challenge someone to a game and discuss tactics.',
    targetGrammar: ['modals-can', 'past-simple'],
    targetVocab: ['bao', 'mchezo', 'mbegu', 'kushinda', 'mkakati'],
    difficulty: 'practice',
    culturalContext: { region: 'TZ', category: 'social' },
  },
  {
    id: 'sw-food-l07',
    title: 'Zanzibar Spice Tour',
    blurb: 'Discuss spices and their uses during a farm visit',
    level: 7,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['sw-food-l01'],
    category: 'Culture & Deep',
    scenarioBrief:
      'A guide leads you through a spice farm in Zanzibar, explaining cloves, cardamom, and vanilla. You ask about cultivation, history, and cooking uses.',
    targetGrammar: ['passive-present', 'relative-clauses'],
    targetVocab: ['karafuu', 'iliki', 'vanila', 'viungo', 'shamba'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'food' },
  },
  {
    id: 'sw-family-l08',
    title: 'Harusi Planning',
    blurb: 'Help plan a traditional Swahili wedding ceremony',
    level: 8,
    spiralGroup: 'family-culture',
    spiralOrder: 2,
    prerequisites: ['sw-family-l04'],
    category: 'Social',
    scenarioBrief:
      'A cousin is getting married and the family gathers to plan the harusi. Discussion covers the nikah, henna night, and food for three hundred guests.',
    targetGrammar: ['future-will', 'quantifiers'],
    targetVocab: ['harusi', 'nikah', 'hina', 'ngoma', 'wageni'],
    difficulty: 'challenge',
    culturalContext: { region: 'TZ', category: 'celebration' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'sw-social-l09',
    title: 'Community Meeting',
    blurb: 'Participate in a village baraza to discuss local issues',
    level: 9,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'The village elder calls a baraza to discuss water access. Community members present their views. You contribute a proposal using persuasive and respectful language.',
    targetGrammar: ['discourse-markers', 'hedging'],
    targetVocab: ['baraza', 'mzee', 'jamii', 'maji', 'pendekezo'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'social' },
  },
  {
    id: 'sw-business-l10',
    title: 'Safari Lodge Partnership',
    blurb: 'Negotiate a community tourism partnership',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 2,
    prerequisites: ['sw-business-l06'],
    category: 'Work & Study',
    scenarioBrief:
      'A lodge owner approaches your village about a partnership for cultural tourism. You discuss terms ensuring the community benefits while preserving traditions.',
    targetGrammar: ['conditional-second', 'passive-past'],
    targetVocab: ['utalii', 'ushirikiano', 'mapato', 'mila', 'mazingira'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'business' },
  },
  {
    id: 'sw-culture-l10',
    title: 'Taarab Music Discussion',
    blurb: 'Discuss the poetry and tradition of taarab music',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'After a taarab performance, musicians and fans discuss the poetic metaphors in the lyrics. You share your interpretation of a popular song.',
    targetGrammar: ['subjunctive', 'nominalization'],
    targetVocab: ['taarab', 'mashairi', 'wimbo', 'mapenzi', 'sitara'],
    difficulty: 'challenge',
    culturalContext: { region: 'TZ', category: 'social' },
  },
  {
    id: 'sw-social-l11',
    title: 'Swahili Proverb Exchange',
    blurb: 'Use and interpret Swahili proverbs in conversation',
    level: 11,
    spiralGroup: 'discourse-culture',
    spiralOrder: 2,
    prerequisites: ['sw-social-l09'],
    category: 'Ideas & Stories',
    scenarioBrief:
      'An elder shares wisdom through methali. Each proverb sparks discussion about its deeper meaning and modern relevance. You respond with proverbs of your own.',
    targetGrammar: ['reported-speech', 'conditional-mixed'],
    targetVocab: ['methali', 'hekima', 'maana', 'mfano', 'busara'],
    difficulty: 'core',
    culturalContext: { region: 'TZ', category: 'social' },
  },
  {
    id: 'sw-celebration-l12',
    title: 'Mwaka Kogwa Festival',
    blurb: 'Describe and discuss the Zanzibar new year festival',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['sw-celebration-l05'],
    category: 'Culture & Deep',
    scenarioBrief:
      'During Mwaka Kogwa, you watch the banana-stalk fights and bonfire rituals. An elder explains the Shirazi origins of the festival and you discuss cultural preservation.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['Mwaka-Kogwa', 'moto', 'desturi', 'Washirazi', 'uhifadhi'],
    difficulty: 'challenge',
    culturalContext: { region: 'TZ', category: 'celebration' },
  },
]
