/**
 * Cultural scenario seeds for Urdu (Pakistan/India)
 * Covers chai stalls, bazaars, family gatherings, celebrations, and business contexts.
 */
import type { ConversationSeed } from '../types'

export const urCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'ur-food-l01',
    title: 'Chai at the Dhaba',
    blurb: 'Order tea and snacks at a roadside tea stall',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You stop at a bustling roadside dhaba for afternoon chai. The owner greets you warmly and asks what you would like. Other customers chat nearby.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['chai', 'dhaba', 'paratha', 'doodh', 'cheeni'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'food' },
  },
  {
    id: 'ur-market-l02',
    title: 'Bazaar Bargaining',
    blurb: 'Navigate a busy bazaar and ask for prices',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You are walking through a crowded bazaar looking for fabric. Shopkeepers call out to you offering deals. You need to ask about prices and quality.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['bazaar', 'kapra', 'qeemat', 'rang', 'meter'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'market' },
  },
  {
    id: 'ur-family-l02',
    title: 'Greeting Elders',
    blurb: 'Practice respectful greetings with older family members',
    level: 2,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You arrive at your grandparents\' home for a weekend visit. You greet your dada and dadi with proper respect and ask about their health.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['assalam-o-alaikum', 'dada', 'dadi', 'tabiyat', 'khairiyat'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'family' },
  },
  {
    id: 'ur-transport-l03',
    title: 'Rickshaw Ride',
    blurb: 'Negotiate a fare and give directions to a rickshaw driver',
    level: 3,
    spiralGroup: 'transport-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You need to get to the main market. A rickshaw driver pulls up and you negotiate the fare before giving directions through narrow streets.',
    targetGrammar: ['imperatives', 'prepositions-place'],
    targetVocab: ['rickshaw', 'kiraya', 'seedha', 'mohr', 'chowk'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'social' },
  },
  {
    id: 'ur-food-l04',
    title: 'Biryani Night',
    blurb: 'Help plan and discuss a family biryani dinner',
    level: 4,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['ur-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'Your family is preparing biryani for a special Friday dinner. You discuss the ingredients needed and offer to help with the cooking.',
    targetGrammar: ['quantifiers', 'have-has'],
    targetVocab: ['biryani', 'masala', 'chawal', 'gosht', 'pyaaz'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'food' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'ur-celebration-l05',
    title: 'Eid Preparations',
    blurb: 'Discuss Eid plans and gift shopping with family',
    level: 5,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'Eid is approaching and your family discusses preparations — new clothes, sweets to make, and relatives to visit. You share your plans enthusiastically.',
    targetGrammar: ['future-going-to', 'present-perfect'],
    targetVocab: ['Eid', 'eidi', 'seviyan', 'kapray', 'mehman'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'celebration' },
  },
  {
    id: 'ur-social-l06',
    title: 'Mehfil Evening',
    blurb: 'Participate in a poetry and music gathering',
    level: 6,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'You attend a mehfil where friends recite poetry and discuss literature. Someone asks your opinion on a ghazal and you share your thoughts.',
    targetGrammar: ['present-perfect', 'gerunds'],
    targetVocab: ['mehfil', 'ghazal', 'shayari', 'mushaira', 'alfaaz'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'social' },
  },
  {
    id: 'ur-business-l06',
    title: 'Office Chai Break',
    blurb: 'Small talk with colleagues during an office tea break',
    level: 6,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'During the afternoon chai break at work, colleagues discuss weekend plans and recent cricket matches. You join the conversation naturally.',
    targetGrammar: ['past-simple', 'questions-indirect'],
    targetVocab: ['daftar', 'sahib', 'cricket', 'chutti', 'kaam'],
    difficulty: 'practice',
    culturalContext: { region: 'PK', category: 'business' },
  },
  {
    id: 'ur-family-l07',
    title: 'Wedding Planning',
    blurb: 'Discuss wedding arrangements with family members',
    level: 7,
    spiralGroup: 'family-culture',
    spiralOrder: 2,
    prerequisites: ['ur-family-l02'],
    category: 'Social',
    scenarioBrief:
      'A cousin\'s wedding is coming up and the family gathers to discuss mehndi preparations, the venue, and guest lists. Opinions fly from all sides.',
    targetGrammar: ['modals-should', 'conditional-first'],
    targetVocab: ['shaadi', 'mehndi', 'baraat', 'daawat', 'rishtedaar'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'celebration' },
  },
  {
    id: 'ur-market-l08',
    title: 'Wholesale Fabric Deal',
    blurb: 'Negotiate a bulk purchase at a wholesale market',
    level: 8,
    spiralGroup: 'market-culture',
    spiralOrder: 2,
    prerequisites: ['ur-market-l02'],
    category: 'Daily Life',
    scenarioBrief:
      'You visit a wholesale fabric market to buy material for family clothes. The trader offers different rates for bulk purchases and you negotiate terms.',
    targetGrammar: ['conditional-second', 'comparatives'],
    targetVocab: ['thaan', 'thouk', 'nafa', 'karobaar', 'saudaa'],
    difficulty: 'challenge',
    culturalContext: { region: 'PK', category: 'market' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'ur-social-l09',
    title: 'Political Discussion at Chai',
    blurb: 'Engage in a nuanced political discussion at a tea shop',
    level: 9,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'At a local chai spot, regulars discuss current affairs and governance. You express opinions carefully, using diplomatic language to navigate different viewpoints.',
    targetGrammar: ['hedging', 'discourse-markers'],
    targetVocab: ['siyasat', 'hukumat', 'raye', 'insaaf', 'awaam'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'social' },
  },
  {
    id: 'ur-business-l10',
    title: 'Startup Pitch Meeting',
    blurb: 'Present a business idea to potential investors in Lahore',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 2,
    prerequisites: ['ur-business-l06'],
    category: 'Work & Study',
    scenarioBrief:
      'You present your tech startup idea to a group of investors in a Lahore co-working space. You explain your vision mixing English tech terms with Urdu persuasion.',
    targetGrammar: ['passive-present', 'conditional-third'],
    targetVocab: ['sarmaya', 'karobaar', 'munafa', 'tajwees', 'market'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'business' },
  },
  {
    id: 'ur-culture-l10',
    title: 'Sufi Poetry Analysis',
    blurb: 'Discuss the deeper meaning of a Sufi poem',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 2,
    prerequisites: ['ur-social-l06'],
    category: 'Culture & Deep',
    scenarioBrief:
      'A friend shares a verse from Bulleh Shah and asks for your interpretation. You discuss the layers of mystical meaning and how it applies to life today.',
    targetGrammar: ['subjunctive', 'nominalization'],
    targetVocab: ['tasawwuf', 'kalam', 'ishq', 'fana', 'murshid'],
    difficulty: 'challenge',
    culturalContext: { region: 'PK', category: 'social' },
  },
  {
    id: 'ur-family-l11',
    title: 'Inheritance Discussion',
    blurb: 'Navigate a sensitive family conversation about property',
    level: 11,
    spiralGroup: 'family-culture',
    spiralOrder: 3,
    prerequisites: ['ur-family-l07'],
    category: 'Social',
    scenarioBrief:
      'After a family elder passes, relatives gather to discuss property distribution. You mediate diplomatically between differing opinions about fairness and tradition.',
    targetGrammar: ['conditional-mixed', 'reported-speech'],
    targetVocab: ['jaidad', 'hissa', 'wirasat', 'insaaf', 'faisla'],
    difficulty: 'challenge',
    culturalContext: { region: 'PK', category: 'family' },
  },
  {
    id: 'ur-celebration-l12',
    title: 'Qawwali Night Debate',
    blurb: 'Debate the role of music in spiritual practice',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['ur-celebration-l05'],
    category: 'Ideas & Stories',
    scenarioBrief:
      'After attending a qawwali, friends debate whether music is a valid spiritual path. You present complex arguments weaving tradition, theology, and personal experience.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['qawwali', 'sama', 'rohaniyat', 'rivayat', 'bida'],
    difficulty: 'challenge',
    culturalContext: { region: 'PK', category: 'celebration' },
  },
]
