import type { ConversationSeed } from '../types'

/**
 * Hebrew Heritage Seeds — Jewish diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Hebrew and English (Hebrish), informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_HE: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-he-family-l01',
    title: 'Shabbat Shalom, Savta',
    blurb: 'Greet your grandmother on Friday evening',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'It is Friday evening and you arrive at Savta\'s (grandmother) house for Shabbat dinner. She greets you with "Shabbat Shalom, motek!" and asks you to help set the table. Practice basic Hebrew greetings, family terms, and Shabbat vocabulary while mixing in English.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['shabbat-shalom', 'savta', 'saba', 'motek', 'toda', 'bevakasha'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-food-l02',
    title: 'Savta\'s Challah',
    blurb: 'Help your grandmother braid challah',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-he-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Savta teaches you to braid challah for Shabbat. She gives instructions in Hebrew — "Laguz et habatzek," "Tiklei et ze" — and explains how she learned from her Ima in Israel. Practice baking vocabulary and follow instructions while she code-switches with you.',
    targetGrammar: ['imperatives', 'present-simple', 'quantifiers'],
    targetVocab: ['challah', 'batzek', 'kemach', 'beitzim', 'sukar', 'shemen'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-pesach-l03',
    title: 'Preparing the Seder',
    blurb: 'Help set up the Passover Seder plate',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-he-food-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family prepares for the Pesach Seder. Ima explains each item on the Seder plate — maror, charoset, karpas. You help arrange things while Abba hides the afikoman. Discuss the traditions and what each symbol means, using Hebrew terms with English explanations.',
    targetGrammar: ['present-continuous', 'conjunctions', 'there-is-are'],
    targetVocab: ['pesach', 'seder', 'matzah', 'maror', 'charoset', 'haggadah'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-call-l04',
    title: 'Calling Saba in Israel',
    blurb: 'Video call your grandfather in Israel',
    level: 4,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-he-pesach-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'You call your Saba (grandfather) in Tel Aviv. He asks about school using Hebrew, tells you about the weather in Israel, and reminds you to practice your Hebrew. Navigate the conversation, responding in Hebrew when you can and switching to English when you get stuck.',
    targetGrammar: ['past-simple', 'questions-wh', 'future-will'],
    targetVocab: ['saba', 'bet-sefer', 'chofesh', 'chom', 'ivrit', 'mishpacha'],
    difficulty: 'practice',
    culturalContext: { region: 'IL', category: 'family' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-he-chanukah-l05',
    title: 'Lighting the Chanukiah',
    blurb: 'Celebrate Chanukah with extended family',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-he-call-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'The whole family gathers to light the chanukiah on the fifth night. Dod (uncle) tells the Chanukah story, Dodah (aunt) fries sufganiyot. You play dreidel with cousins while Savta watches proudly. Navigate family conversations in Hebrew and explain traditions to a visiting friend.',
    targetGrammar: ['present-perfect', 'modals-must', 'connectors'],
    targetVocab: ['chanukah', 'chanukiah', 'sufganiyot', 'sevivon', 'nes', 'shamash'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-slang-l06',
    title: 'Israeli Slang from Cousin',
    blurb: 'Learn modern Hebrew slang from your Israeli cousin',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-he-chanukah-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your cousin from Israel visits and teases you for speaking "textbook Hebrew." They teach you modern slang — "sababa," "achla," "stam" — and laugh at your formal expressions. Practice casual Israeli Hebrew while they explain the difference between "Hebrew school Hebrew" and real street Hebrew.',
    targetGrammar: ['present-simple', 'modals-could', 'questions-indirect'],
    targetVocab: ['sababa', 'achla', 'stam', 'yalla', 'balagan', 'chaval'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-explain-l07',
    title: 'Explaining Sukkot to a Neighbor',
    blurb: 'Describe the harvest festival to someone unfamiliar',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-he-slang-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your neighbor asks about the structure your family built in the backyard. Explain what a sukkah is, why you eat meals in it, what the lulav and etrog are, and the significance of the harvest festival. Use Hebrew terms for ritual objects while giving context in English.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['sukkot', 'sukkah', 'lulav', 'etrog', 'chag', 'ushpizin'],
    difficulty: 'practice',
    culturalContext: { region: 'IL', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-he-stories-l09',
    title: 'Saba\'s Aliyah Story',
    blurb: 'Hear your grandfather\'s story of moving to Israel',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-he-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Saba shares his story of making aliyah — leaving his home country, arriving in Israel, learning Hebrew from scratch, and building a new life. He uses rich Hebrew with emotional expressions. Navigate understanding his story, asking deep questions, and connecting it to your own relationship with Israel.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['aliyah', 'moledet', 'chalutziut', 'tikvah', 'zikaron', 'shorashim'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-identity-l10',
    title: 'Diaspora vs. Israeli Identity',
    blurb: 'Discuss Jewish identity across borders',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 6,
    prerequisites: ['heritage-he-stories-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'A relative from Israel says "You should make aliyah — that\'s where real Jewish life is." Engage in a thoughtful discussion about diaspora identity, what connects Jews worldwide, whether Hebrew defines Jewishness, and what it means to maintain tradition far from Israel. Use elevated Hebrew.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['zehut', 'tfutzot', 'am-yisrael', 'masoret', 'kehila', 'galut'],
    difficulty: 'core',
    culturalContext: { region: 'IL', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-he-community-l11',
    title: 'Purim Carnival Planning',
    blurb: 'Organize a community Purim celebration',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-he-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'The synagogue asks you to help plan the annual Purim carnival and megillah reading. Coordinate with the rabbi in formal Hebrew, organize costumes and hamantaschen baking with families, and manage the spiel performance. Navigate between formal religious Hebrew and casual community interaction.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['purim', 'megillah', 'mishloach-manot', 'tachposet', 'simcha', 'kehila'],
    difficulty: 'challenge',
    culturalContext: { region: 'IL', category: 'celebration' },
    heritageMode: true,
  },
]
