import type { ConversationSeed } from '../types'

/**
 * Filipino Heritage Seeds — Filipino diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Filipino/Tagalog and English (Taglish), informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_TL: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-tl-family-l01',
    title: 'Mano Po, Lola',
    blurb: 'Show respect to your grandmother the Filipino way',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your Lola (grandmother) and do "mano po" — pressing her hand to your forehead. She says "Kumusta ka, anak?" and asks if you have eaten. Practice basic Filipino greetings, family terms, and the "po/opo" respect system while mixing in English naturally.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'possessives'],
    targetVocab: ['mano-po', 'lola', 'anak', 'kumusta', 'opo', 'salamat'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-food-l02',
    title: 'Lola\'s Adobo Secret',
    blurb: 'Learn your grandmother\'s adobo recipe',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-tl-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Lola teaches you her adobo recipe — the family\'s version. She gives instructions in Tagalog: "Lagyan mo ng suka," "Haluin mo." Practice cooking vocabulary and follow instructions while she tells stories about cooking for your Lolo back in the Philippines.',
    targetGrammar: ['imperatives', 'present-simple', 'articles'],
    targetVocab: ['adobo', 'suka', 'toyo', 'bawang', 'sibuyas', 'kawali'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-fiesta-l03',
    title: 'Barrio Fiesta at the Community Center',
    blurb: 'Attend a Filipino community celebration',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-tl-food-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family attends a barrio fiesta at the Filipino community center. Tita (auntie) asks about school, Tito (uncle) tells jokes in Taglish. You eat lechon and pancit while navigating conversations with relatives who mix Filipino and English seamlessly.',
    targetGrammar: ['present-continuous', 'past-simple', 'conjunctions'],
    targetVocab: ['fiesta', 'lechon', 'pancit', 'tita', 'tito', 'kapatid'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-balikbayan-l04',
    title: 'Packing the Balikbayan Box',
    blurb: 'Help your family send a care package to the Philippines',
    level: 4,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-tl-fiesta-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Nanay (mother) is packing a balikbayan box to send to relatives in the Philippines. She lists items — chocolates, vitamins, clothes — and tells you who each gift is for. Practice discussing family connections, gift-giving vocabulary, and expressing care in Filipino.',
    targetGrammar: ['present-continuous', 'questions-wh', 'future-going-to'],
    targetVocab: ['balikbayan', 'padala', 'pasalubong', 'kamag-anak', 'regalo', 'pamilya'],
    difficulty: 'practice',
    culturalContext: { region: 'PH', category: 'family' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-tl-christmas-l05',
    title: 'Noche Buena Feast',
    blurb: 'Celebrate Christmas Eve the Filipino way',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-tl-balikbayan-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'It is Noche Buena — Filipino Christmas Eve. The whole family gathers after Simbang Gabi for a midnight feast. Tita prepares bibingka and puto bumbong. Everyone exchanges gifts and sings karaoke. Navigate the festive family gathering using Taglish.',
    targetGrammar: ['present-perfect', 'modals-must', 'connectors'],
    targetVocab: ['noche-buena', 'simbang-gabi', 'bibingka', 'parol', 'aguinaldo', 'ninong'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-respect-l06',
    title: 'Po, Opo, and Ate',
    blurb: 'Practice Filipino respect language with relatives',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-tl-christmas-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Tatay (father) reminds you to use "po" and "opo" with elders and "Ate/Kuya" with older cousins. At a family dinner, practice switching between casual talk with younger cousins and respectful address with Lolo, Lola, and other elders. Learn why these honorifics matter.',
    targetGrammar: ['modals-should', 'questions-indirect', 'subject-pronouns'],
    targetVocab: ['po', 'opo', 'ate', 'kuya', 'lolo', 'galang'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-explain-l07',
    title: 'Explaining Simbang Gabi',
    blurb: 'Describe Filipino Christmas traditions to a friend',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-tl-respect-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'A friend asks why your family starts Christmas celebrations in September. Explain Simbang Gabi (9 dawn masses), the parol tradition, and why Christmas is so important in Filipino culture. Use Tagalog terms naturally while explaining the deep cultural significance in English.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['simbang-gabi', 'parol', 'misa', 'panalangin', 'tradisyon', 'diwa'],
    difficulty: 'practice',
    culturalContext: { region: 'PH', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-tl-stories-l09',
    title: 'Lolo\'s Probinsya Days',
    blurb: 'Listen to your grandfather\'s stories of life in the province',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-tl-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Lolo tells stories of growing up in the probinsya — fishing, farming, and community fiestas. He uses deeper Filipino with regional expressions and old-fashioned phrases. Navigate understanding his stories, asking for clarification, and connecting his experiences to Filipino identity.',
    targetGrammar: ['past-perfect', 'reported-speech', 'discourse-markers'],
    targetVocab: ['probinsya', 'bukid', 'dagat', 'kasaysayan', 'kwento', 'ugali'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-identity-l10',
    title: 'Fil-Am Identity',
    blurb: 'Discuss what it means to be Filipino-American',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 6,
    prerequisites: ['heritage-tl-stories-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'A relative from Manila visits and says your Tagalog sounds "Americanized." Engage in a deep conversation about identity, the "colonial mentality" debate, preserving language across generations, and what bayanihan means in the diaspora. Use sophisticated Filipino for complex ideas.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['pagkakakilanlan', 'bayanihan', 'kapwa', 'kultura', 'wika', 'ugat'],
    difficulty: 'core',
    culturalContext: { region: 'PH', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-tl-community-l11',
    title: 'Filipino Heritage Month Event',
    blurb: 'Organize a community cultural celebration',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-tl-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'You help organize a Filipino Heritage Month event at your community center. Coordinate food vendors, cultural performances (tinikling dance, folk songs), and guest speakers. Navigate formal Filipino with community elders, English with venue staff, and Taglish with fellow organizers.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['pamana', 'kultura', 'pagdiriwang', 'komunidad', 'programa', 'pagkakaisa'],
    difficulty: 'challenge',
    culturalContext: { region: 'PH', category: 'celebration' },
    heritageMode: true,
  },
]
