import type { ConversationSeed } from '../types'

/**
 * Urdu Heritage Seeds — Pakistani diaspora
 *
 * Focus: Family interactions, cultural celebrations, intergenerational communication,
 * code-switching between Urdu and English, informal register.
 * Minimum 3 seeds per level bracket (Beginner 1-4, Intermediate 5-8, Advanced 9-12).
 */

export const HERITAGE_SEEDS_UR: ConversationSeed[] = [
  // ── Beginner (Levels 1-4) ────────────────────────────────────────────────
  {
    id: 'heritage-ur-family-l01',
    title: 'Greeting Nani',
    blurb: 'Practice greeting your grandmother in Urdu',
    level: 1,
    spiralGroup: 'heritage-family',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'You visit your grandmother (Nani) who speaks mostly Urdu. She greets you warmly with "Assalamu Alaikum, beta!" and asks about your day. Practice responding with basic Urdu greetings and family terms while mixing in English naturally.',
    targetGrammar: ['present-simple-to-be', 'questions-wh', 'possessives'],
    targetVocab: ['nani', 'salam', 'kaise-ho', 'beta', 'theek-hai'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-family-l02',
    title: 'Helping Dadi in the Kitchen',
    blurb: 'Learn kitchen vocabulary while cooking with your grandmother',
    level: 2,
    spiralGroup: 'heritage-family',
    spiralOrder: 2,
    prerequisites: ['heritage-ur-family-l01'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your paternal grandmother (Dadi) is making chai and parathas. She asks you to pass her ingredients and teaches you how she makes things. Practice food and kitchen terms in Urdu while she code-switches naturally with you.',
    targetGrammar: ['imperatives', 'present-simple', 'articles'],
    targetVocab: ['chai', 'paratha', 'masala', 'doodh', 'cheeni', 'roti'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'food' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-eid-l03',
    title: 'Getting Ready for Eid',
    blurb: 'Talk about Eid preparations with your family',
    level: 3,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 1,
    prerequisites: ['heritage-ur-family-l02'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your family is preparing for Eid. Ammi is ironing new clothes, Abu is arranging the car for mosque. You discuss what to wear, who is coming over, and what sweets to make. Code-switch between Urdu and English as your family naturally does.',
    targetGrammar: ['future-going-to', 'present-continuous', 'questions-yesno'],
    targetVocab: ['eid-mubarak', 'namaz', 'mithai', 'kapray', 'mosque', 'eidi'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-phone-l04',
    title: 'Phone Call to Pakistan',
    blurb: 'Speak with relatives back home on a video call',
    level: 4,
    spiralGroup: 'heritage-family',
    spiralOrder: 3,
    prerequisites: ['heritage-ur-eid-l03'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your parents set up a WhatsApp call with Taya Abu and Phupho in Lahore. They ask about your studies, the weather, and when you are visiting next. Practice maintaining a conversation with relatives who expect more Urdu from you.',
    targetGrammar: ['present-perfect', 'questions-wh', 'future-will'],
    targetVocab: ['taya', 'phupho', 'parhai', 'garmi', 'wapis-aana'],
    difficulty: 'practice',
    culturalContext: { region: 'PK', category: 'family' },
    heritageMode: true,
  },

  // ── Intermediate (Levels 5-8) ────────────────────────────────────────────
  {
    id: 'heritage-ur-wedding-l05',
    title: 'Cousin\'s Mehndi Night',
    blurb: 'Navigate a Pakistani wedding celebration',
    level: 5,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 2,
    prerequisites: ['heritage-ur-phone-l04'],
    category: 'Culture & Deep',
    scenarioBrief: 'You are at your cousin\'s Mehndi ceremony. Aunties are singing dholki songs, everyone is dancing. Your Khala asks you to join in and explain to your non-Pakistani friend what is happening. Switch between Urdu with family and English with your friend.',
    targetGrammar: ['present-continuous', 'imperatives', 'connectors'],
    targetVocab: ['mehndi', 'dholki', 'khala', 'dulhan', 'barat', 'nikkah'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'celebration' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-respect-l06',
    title: 'Aap vs Tum',
    blurb: 'Practice formal and informal address with elders',
    level: 6,
    spiralGroup: 'heritage-family',
    spiralOrder: 4,
    prerequisites: ['heritage-ur-wedding-l05'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Nana corrects you for using "tum" instead of "aap" when speaking to him. Your mother explains the importance of respectful address in Urdu. Practice switching between formal (aap) with elders and informal (tum/tu) with cousins.',
    targetGrammar: ['subject-pronouns', 'modals-should', 'questions-indirect'],
    targetVocab: ['aap', 'tum', 'adab', 'izzat', 'buzurg', 'tehzeeb'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-explain-l07',
    title: 'Explaining Ramadan to a Classmate',
    blurb: 'Describe your family\'s Ramadan traditions to a non-Muslim friend',
    level: 7,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 3,
    prerequisites: ['heritage-ur-respect-l06'],
    category: 'Culture & Deep',
    scenarioBrief: 'A school friend asks why you are fasting. You explain Ramadan, sehri, iftari, and taraweeh using a mix of Urdu terms and English explanations. Then you invite them to your house for iftar dinner, describing what your Ammi will cook.',
    targetGrammar: ['present-simple', 'connectors', 'relative-clauses'],
    targetVocab: ['roza', 'sehri', 'iftari', 'taraweeh', 'dua', 'khajoor'],
    difficulty: 'practice',
    culturalContext: { region: 'PK', category: 'celebration' },
    heritageMode: true,
  },

  // ── Advanced (Levels 9-12) ───────────────────────────────────────────────
  {
    id: 'heritage-ur-poetry-l09',
    title: 'Dada\'s Urdu Poetry',
    blurb: 'Discuss Urdu poetry and ghazals with your grandfather',
    level: 9,
    spiralGroup: 'heritage-family',
    spiralOrder: 5,
    prerequisites: ['heritage-ur-explain-l07'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your Dada recites a couplet from Faiz Ahmed Faiz and asks if you understand the meaning. Discuss the poetry, its emotional depth, and its historical context. Navigate between appreciating the beauty of Urdu literature and asking for explanations when you don\'t fully understand.',
    targetGrammar: ['subjunctive', 'passive-past', 'discourse-markers'],
    targetVocab: ['shayari', 'ghazal', 'misra', 'sher', 'alfaaz', 'maani'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'family' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-identity-l10',
    title: 'Between Two Worlds',
    blurb: 'Discuss diaspora identity with an older cousin',
    level: 10,
    spiralGroup: 'heritage-family',
    spiralOrder: 6,
    prerequisites: ['heritage-ur-poetry-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'Your older cousin who grew up in Pakistan visits and teases you about your "angrezi" Urdu accent. Have a deep conversation about identity, belonging, feeling caught between cultures, and what it means to be Pakistani abroad. Use sophisticated Urdu mixed with English for complex ideas.',
    targetGrammar: ['conditional-second', 'hedging', 'emphasis'],
    targetVocab: ['pehchaan', 'watan', 'ghar', 'pardes', 'apnapan', 'rishta'],
    difficulty: 'core',
    culturalContext: { region: 'PK', category: 'social' },
    heritageMode: true,
  },
  {
    id: 'heritage-ur-community-l11',
    title: 'Community Mosque Fundraiser',
    blurb: 'Help organize a community event using formal Urdu',
    level: 11,
    spiralGroup: 'heritage-celebrations',
    spiralOrder: 4,
    prerequisites: ['heritage-ur-identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'You volunteer at the local Pakistani community center to help organize a fundraiser. Navigate formal conversations with community elders who expect proper Urdu, coordinate with younger volunteers in casual Urdu-English mix, and present plans to the committee using respectful language.',
    targetGrammar: ['passive-present', 'reported-speech', 'modals-hedging'],
    targetVocab: ['jamaat', 'muashi', 'chanda', 'ijlaas', 'ittehad', 'khidmat'],
    difficulty: 'challenge',
    culturalContext: { region: 'PK', category: 'social' },
    heritageMode: true,
  },
]
