import type { ConversationSeed } from '../types'

/**
 * Level 1 — First Words (Absolute Beginner)
 * AI: 70% native language, 30% target. Single words, repeated phrases.
 * 25 seeds: Self & Identity (7), Daily Life (7), Social (3), Places (2), Commerce (2), Ideas (2), Numbers (2)
 */

export const SEEDS_L01: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l01',
    title: 'Hello! Who Are You?',
    blurb: 'Introduce yourself — say your name and where you\'re from.',
    level: 1, spiralGroup: 'identity', spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief: 'A warm first meeting. Greet the user, introduce yourself, and ask their name and where they are from. Keep sentences very short. Use simple present of "to be". Celebrate every response.',
    targetGrammar: ['present-simple-to-be', 'subject-pronouns', 'questions-wh'],
    targetVocab: ['greetings', 'names', 'countries', 'basic-introductions'],
    difficulty: 'core',
  },
  {
    id: 'whoami-l01b',
    title: 'Who Are They?',
    blurb: 'Ask and answer simple questions about people.',
    level: 1, spiralGroup: 'identity', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Continue getting to know each other. Ask about their friends or family members. Use "he/she is", "they are". Keep it simple — one piece of information at a time. Model correct forms naturally.',
    targetGrammar: ['present-simple-to-be', 'subject-pronouns', 'questions-yesno'],
    targetVocab: ['names', 'relationships', 'nationalities'],
    difficulty: 'practice',
  },
  {
    id: 'family-l01',
    title: 'Meet My Family',
    blurb: 'Name your family members and say something about each.',
    level: 1, spiralGroup: 'family', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about their family. "Do you have a brother? A sister?" Introduce possessive adjectives (my, your, his, her) and basic adjectives (big, small, tall). Share made-up details about your own family to model the language.',
    targetGrammar: ['present-simple-to-be', 'possessives', 'adjectives-basic'],
    targetVocab: ['family-members', 'basic-adjectives', 'ages'],
    difficulty: 'core',
  },
  {
    id: 'home-l01',
    title: 'My Little Room',
    blurb: 'Describe your room and what\'s in it.',
    level: 1, spiralGroup: 'home', spiralOrder: 1,
    prerequisites: ['family-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about their room or home. Use "there is / there are". Describe a simple room — a bed, a table, a chair. Ask them to describe theirs. Point at things: "this" and "that".',
    targetGrammar: ['there-is-are', 'prepositions-place', 'adjectives-basic'],
    targetVocab: ['furniture', 'rooms', 'household-objects', 'prepositions'],
    difficulty: 'core',
  },
  {
    id: 'home-l01b',
    title: 'What\'s in Your Bag?',
    blurb: 'Talk about things you carry with you.',
    level: 1, spiralGroup: 'home', spiralOrder: 1,
    prerequisites: ['home-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask what\'s in their bag or pockets. Use "I have" and "you have". Name simple objects — phone, keys, wallet, book. A playful guessing game creates anticipation and keeps it fun.',
    targetGrammar: ['have-has', 'articles', 'plurals'],
    targetVocab: ['everyday-objects', 'colors', 'sizes'],
    difficulty: 'practice',
  },
  {
    id: 'appearance-l01',
    title: 'What Do I Look Like?',
    blurb: 'Describe how you look using simple words.',
    level: 1, spiralGroup: 'appearance', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Describe your own (avatar\'s) appearance — hair color, eye color, height. Ask them to describe themselves. Use "I have", "you have" with basic adjectives. Keep turns very short. Model and celebrate.',
    targetGrammar: ['have-has', 'adjectives-basic', 'questions-wh'],
    targetVocab: ['body-parts', 'colors', 'physical-description'],
    difficulty: 'practice',
  },
  {
    id: 'feelings-l01',
    title: 'How Are You Today?',
    blurb: 'Say how you feel — happy, tired, hungry.',
    level: 1, spiralGroup: 'feelings', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask how they feel today. Use "I am + adjective". Teach basic emotions — happy, sad, tired, hungry, thirsty. Ask "Are you happy?" for yes/no answers. Share your own feelings to model.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'adjectives-basic'],
    targetVocab: ['emotions-basic', 'feelings', 'physical-states'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'food-l01',
    title: 'My First Café',
    blurb: 'Order a simple drink and something to eat.',
    level: 1, spiralGroup: 'food', spiralOrder: 1,
    prerequisites: ['feelings-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Roleplay a café scenario very simply. You are the server. Greet them and ask what they want. Use "I want" / "I would like". Respond to their choice. Keep it to one item at a time.',
    targetGrammar: ['imperatives', 'polite-requests', 'numbers-time'],
    targetVocab: ['drinks', 'simple-food', 'polite-phrases', 'basic-prices'],
    difficulty: 'core',
  },
  {
    id: 'food-l01b',
    title: 'I Like Apples',
    blurb: 'Say what foods you like and don\'t like.',
    level: 1, spiralGroup: 'food', spiralOrder: 1,
    prerequisites: ['food-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about foods they like. Model "I like...", "I don\'t like...". Name simple foods — apple, bread, milk, rice, egg. Ask "Do you like...?" and celebrate their answers. Share your own preferences.',
    targetGrammar: ['present-simple', 'like-gerund', 'conjunctions'],
    targetVocab: ['basic-foods', 'like-dislike', 'simple-adjectives-good-bad'],
    difficulty: 'core',
  },
  {
    id: 'routines-l01',
    title: 'My Morning',
    blurb: 'Talk about what you do every morning.',
    level: 1, spiralGroup: 'routines', spiralOrder: 1,
    prerequisites: ['time-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about their morning routine. Use present simple — "I wake up", "I eat breakfast". Keep verbs to 3-4 common ones. Use "first", "then". Ask simple questions and model the correct answers.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'conjunctions'],
    targetVocab: ['daily-routines', 'morning-activities', 'time-words'],
    difficulty: 'core',
  },
  {
    id: 'routines-l01b',
    title: 'What Do You Do Every Day?',
    blurb: 'Describe your daily activities step by step.',
    level: 1, spiralGroup: 'routines', spiralOrder: 1,
    prerequisites: ['routines-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Continue about daily routines. Ask about afternoon and evening. Use "I go to...", "I watch...", "I read...". Simple present for habits. Keep it flowing like a natural chat, not an interview.',
    targetGrammar: ['present-simple', 'prepositions-time', 'questions-wh'],
    targetVocab: ['daily-activities', 'places-at-home', 'evening-routines'],
    difficulty: 'practice',
  },
  {
    id: 'weather-l01',
    title: 'Is It Cold Outside?',
    blurb: 'Describe the weather using simple words.',
    level: 1, spiralGroup: 'weather', spiralOrder: 1,
    prerequisites: ['feelings-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about today\'s weather. Use "it is + adjective" — hot, cold, rainy, sunny, windy. Ask "Is it cold?" for yes/no. Simple short sentences. Share made-up weather where you are.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'adjectives-basic'],
    targetVocab: ['weather-words', 'seasons-basic', 'temperature-basic'],
    difficulty: 'practice',
  },
  {
    id: 'hobbies-l01',
    title: 'What Do You Like to Do?',
    blurb: 'Talk about what you enjoy doing for fun.',
    level: 1, spiralGroup: 'hobbies', spiralOrder: 1,
    prerequisites: ['feelings-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about things they enjoy. Use "I like to..." and "I like + noun". Simple hobbies — reading, drawing, singing, running, playing. Ask "Do you like to...?" Model with your own examples.',
    targetGrammar: ['present-simple', 'like-gerund', 'questions-yesno'],
    targetVocab: ['basic-hobbies', 'action-verbs', 'fun-activities'],
    difficulty: 'core',
  },
  {
    id: 'hobbies-l01b',
    title: 'Let\'s Play Outside!',
    blurb: 'Talk about sports and outdoor games you enjoy.',
    level: 1, spiralGroup: 'hobbies', spiralOrder: 1,
    prerequisites: ['hobbies-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Chat about sports and outdoor play. Use "I play", "you play". Name simple sports — football, tennis, swimming. Use "can you...?" for ability. Keep it light and playful like a friendly chat.',
    targetGrammar: ['modals-can', 'present-simple', 'questions-yesno'],
    targetVocab: ['sports-basic', 'outdoor-activities', 'play-verbs'],
    difficulty: 'practice',
  },
  {
    id: 'time-l01',
    title: 'What Time Is It?',
    blurb: 'Tell the time and talk about hours of the day.',
    level: 1, spiralGroup: 'time', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Talk about time. Ask "What time is it?" Teach hours — one o\'clock, two o\'clock. Ask what time they do things — "I eat at 7 o\'clock". Use numbers 1-12. Very simple. Celebrate every attempt.',
    targetGrammar: ['numbers-time', 'questions-wh', 'present-simple'],
    targetVocab: ['numbers-1-12', 'time-expressions', 'clock-basic'],
    difficulty: 'core',
  },
  {
    id: 'time-l01b',
    title: 'My Day by the Clock',
    blurb: 'Say what you do at different times of day.',
    level: 1, spiralGroup: 'time', spiralOrder: 1,
    prerequisites: ['time-l01', 'routines-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Combine time and activities. Ask "What do you do at 7 o\'clock?" Model "At 8 o\'clock I go to school." Practice 3-4 time-based sentences. Keep it simple with the target language woven in naturally.',
    targetGrammar: ['prepositions-time', 'present-simple', 'numbers-time'],
    targetVocab: ['time-expressions', 'daily-routines', 'daily-activities'],
    difficulty: 'challenge',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'meeting-l01',
    title: 'Nice to Meet You',
    blurb: 'Greet someone new and say a few words.',
    level: 1, spiralGroup: 'meeting-people', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Social',
    scenarioBrief: 'Meet for the first time. Use greetings — "hello", "hi", "nice to meet you". Ask "How are you?" Teach the response "I\'m fine, thanks". Simple polite exchange. Keep it warm and natural.',
    targetGrammar: ['present-simple-to-be', 'greetings', 'questions-wh'],
    targetVocab: ['greetings', 'politeness', 'basic-responses'],
    difficulty: 'core',
  },
  {
    id: 'meeting-l01b',
    title: 'How Are You?',
    blurb: 'Ask and answer about how someone is doing.',
    level: 1, spiralGroup: 'meeting-people', spiralOrder: 1,
    prerequisites: ['meeting-l01'],
    category: 'Social',
    scenarioBrief: 'Continue the conversation. Ask "How are you?" in different ways. Teach responses — "I\'m good", "I\'m okay", "not bad". Use simple emotion words. Keep the exchange natural and friendly.',
    targetGrammar: ['present-simple-to-be', 'questions-yesno', 'adjectives-basic'],
    targetVocab: ['greetings', 'emotions-basic', 'polite-phrases'],
    difficulty: 'practice',
  },
  {
    id: 'celebration-l01',
    title: 'Happy Birthday!',
    blurb: 'Wish someone well and talk about birthdays.',
    level: 1, spiralGroup: 'celebrations', spiralOrder: 1,
    prerequisites: ['numbers-l01'],
    category: 'Social',
    scenarioBrief: 'Talk about birthdays. Ask "How old are you?" Teach "I am [number]". Wish them "Happy Birthday!" Use numbers for age. Use "happy", "fun", "good". Keep it simple and celebratory.',
    targetGrammar: ['present-simple-to-be', 'numbers-time', 'adjectives-basic'],
    targetVocab: ['age', 'birthday', 'numbers-1-100', 'celebration-basic'],
    difficulty: 'practice',
  },

  // ── Places & Travel ───────────────────────────────────────────────────
  {
    id: 'city-l01',
    title: 'Places Near Me',
    blurb: 'Name places in your neighborhood.',
    level: 1, spiralGroup: 'city', spiralOrder: 1,
    prerequisites: ['home-l01'],
    category: 'Travel',
    scenarioBrief: 'Ask about places near their home. Use "there is a...". Name places — park, shop, school, hospital. Use "next to", "near". Simple location words. Describe your own imaginary neighborhood.',
    targetGrammar: ['there-is-are', 'prepositions-place', 'articles'],
    targetVocab: ['city-places', 'neighborhood', 'shops', 'public-places'],
    difficulty: 'core',
  },
  {
    id: 'city-l01b',
    title: 'Where Is the Park?',
    blurb: 'Ask and answer where places are located.',
    level: 1, spiralGroup: 'city', spiralOrder: 1,
    prerequisites: ['city-l01'],
    category: 'Travel',
    scenarioBrief: 'Play a simple "where is" game. Ask "Where is the park?" Teach "here", "there", "near", "far". Point to imaginary places. Keep directions to one word answers. Practice through repetition in context.',
    targetGrammar: ['there-is-are', 'prepositions-place', 'questions-wh'],
    targetVocab: ['directions-basic', 'city-places', 'location-words'],
    difficulty: 'practice',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'cafe-l01',
    title: 'Ordering a Drink',
    blurb: 'Order a drink at a cafe and pay.',
    level: 1, spiralGroup: 'cafe', spiralOrder: 1,
    prerequisites: ['food-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Simple cafe order. You\'re the server. Ask "What do you want?" Teach "I want...", "please", "thank you". Give a price, accept payment. One drink only. Short and sweet interaction.',
    targetGrammar: ['imperatives', 'polite-requests', 'numbers-time'],
    targetVocab: ['drinks', 'polite-phrases', 'basic-prices', 'simple-order'],
    difficulty: 'core',
  },
  {
    id: 'shopping-l01',
    title: 'At the Store',
    blurb: 'Buy something simple and say what you want.',
    level: 1, spiralGroup: 'shopping', spiralOrder: 1,
    prerequisites: ['numbers-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Simple shop roleplay. You are the shopkeeper. Ask "What do you want?" Teach "I want...", "how much?" Use numbers for prices. Simple items — water, bread, fruit. Keep it to one item.',
    targetGrammar: ['imperatives', 'polite-requests', 'numbers-time'],
    targetVocab: ['simple-items', 'prices', 'buying-phrases', 'polite-phrases'],
    difficulty: 'core',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'opinion-l01',
    title: 'I Like It!',
    blurb: 'Say what you like and don\'t like.',
    level: 1, spiralGroup: 'opinions', spiralOrder: 1,
    prerequisites: ['food-l01b'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask about likes. "Do you like cats? Dogs?" Teach "I like", "I don\'t like". Use simple nouns — animals, colors, foods. Ask "You?" to invite them to ask back. Keep it light and playful.',
    targetGrammar: ['present-simple', 'like-gerund', 'conjunctions'],
    targetVocab: ['like-dislike', 'basic-nouns', 'animals', 'colors'],
    difficulty: 'core',
  },

  // ── Numbers (extra) ──────────────────────────────────────────────────
  {
    id: 'numbers-l01',
    title: 'Let\'s Count!',
    blurb: 'Count objects and use numbers 1-20.',
    level: 1, spiralGroup: 'numbers', spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief: 'Play a counting game. Ask "How many?" Show fingers or imaginary objects. Count 1-20 together. Ask "How many books?" "How many cats?" Use plurals naturally. Celebrate every correct count.',
    targetGrammar: ['numbers-time', 'plurals', 'questions-wh'],
    targetVocab: ['numbers-1-20', 'counting', 'basic-nouns-plural'],
    difficulty: 'core',
  },
  {
    id: 'numbers-l01b',
    title: 'How Many?',
    blurb: 'Ask and answer "how many" questions about everyday things.',
    level: 1, spiralGroup: 'numbers', spiralOrder: 1,
    prerequisites: ['numbers-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Continue counting practice. Ask "How many windows in your room?" "How many people in your family?" Use numbers up to 20. Practice plural nouns. Keep it like a curious conversation, not a test.',
    targetGrammar: ['numbers-time', 'plurals', 'questions-wh'],
    targetVocab: ['numbers-1-20', 'household-items', 'family-members'],
    difficulty: 'practice',
  },
]
