import type { ConversationSeed } from '../types'

/**
 * Level 2 — Building Blocks
 * AI: 60% native, 40% target. 2-4 word phrases, memorized chunks.
 * 25 seeds: Self & Story (4), Daily Life (7), Social (4), Travel (4), Commerce (2), Work (2), Ideas (2)
 */

export const SEEDS_L02: ConversationSeed[] = [
  // ── Self & Story ────────────────────────────────────────────────────────
  {
    id: 'mystory-l02',
    title: 'Where I Grew Up',
    blurb: 'Talk about where you lived as a child.',
    level: 2, spiralGroup: 'story', spiralOrder: 1,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about their childhood home and town. Use "I lived in...", "I was born in...". Simple past with "was/were". Keep it to one fact at a time. Share a simple made-up memory to model.',
    targetGrammar: ['past-simple-to-be', 'prepositions-place', 'there-is-are'],
    targetVocab: ['places', 'childhood', 'nature', 'town-words'],
    difficulty: 'core',
  },
  {
    id: 'mystory-l02b',
    title: 'When I Was Little',
    blurb: 'Describe what you were like as a child.',
    level: 2, spiralGroup: 'story', spiralOrder: 1,
    prerequisites: ['mystory-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about childhood personality and appearance. Use "I was...", "you were..." with adjectives. "Were you shy?" "I was small." Keep all verbs in past with was/were. Warm and nostalgic tone.',
    targetGrammar: ['past-simple-to-be', 'questions-yesno', 'adjectives-basic'],
    targetVocab: ['personality-basic', 'childhood', 'physical-description'],
    difficulty: 'practice',
  },
  {
    id: 'family-l02',
    title: 'What Does Your Family Do?',
    blurb: 'Talk about family members and what they do.',
    level: 2, spiralGroup: 'family', spiralOrder: 2,
    prerequisites: ['family-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about what family members do — jobs, hobbies, where they live. Use "he works", "she lives", "they have". Introduce present simple for third person. Share made-up family details naturally.',
    targetGrammar: ['present-simple', 'possessives', 'questions-wh'],
    targetVocab: ['family-members', 'simple-jobs', 'activities'],
    difficulty: 'practice',
  },
  {
    id: 'clothes-l02',
    title: 'What Are You Wearing?',
    blurb: 'Describe what you and others are wearing.',
    level: 2, spiralGroup: 'appearance', spiralOrder: 2,
    prerequisites: ['appearance-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about clothes. Use "I\'m wearing", "you\'re wearing". Name clothing — shirt, pants, shoes, hat, jacket. Use colors and sizes. Describe your own outfit first to model. Keep it light and observational.',
    targetGrammar: ['present-continuous', 'adjectives-basic', 'have-has'],
    targetVocab: ['clothing', 'colors', 'materials-basic', 'fashion-basic'],
    difficulty: 'practice',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'health-l02',
    title: 'How Do You Feel?',
    blurb: 'Talk about your health and how your body feels.',
    level: 2, spiralGroup: 'health', spiralOrder: 1,
    prerequisites: ['feelings-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about health. "How do you feel?" "My head hurts." "I have a cold." Use "have + noun" and "feel + adjective". Name body parts — head, stomach, arm, leg. Simple check-in conversation.',
    targetGrammar: ['have-has', 'adjectives-basic', 'present-simple'],
    targetVocab: ['body-parts', 'health-basic', 'symptoms', 'feelings'],
    difficulty: 'core',
  },
  {
    id: 'fitness-l02',
    title: 'Let\'s Move!',
    blurb: 'Talk about exercise and staying active.',
    level: 2, spiralGroup: 'health', spiralOrder: 1,
    prerequisites: ['health-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss exercise. "Do you run?" "I walk every day." "I can swim." Use "can" for ability. Name activities — walk, run, dance, swim. Ask about frequency — "every day", "sometimes".',
    targetGrammar: ['modals-can', 'adverbs-frequency', 'present-simple'],
    targetVocab: ['exercise', 'sports-basic', 'frequency-words', 'movement-verbs'],
    difficulty: 'practice',
  },
  {
    id: 'tech-l02',
    title: 'My Phone & Me',
    blurb: 'Talk about your phone and how you use it.',
    level: 2, spiralGroup: 'technology', spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief: 'Ask about phone usage. "Do you have a phone?" "What apps do you use?" Use present simple. Keep tech vocabulary simple — phone, computer, game, photo. Share your own digital habits casually.',
    targetGrammar: ['present-simple', 'have-has', 'questions-wh'],
    targetVocab: ['technology-basic', 'phone-words', 'apps', 'digital-life'],
    difficulty: 'core',
  },
  {
    id: 'money-l02',
    title: 'Do You Save Money?',
    blurb: 'Talk about saving, spending, and what things cost.',
    level: 2, spiralGroup: 'money', spiralOrder: 1,
    prerequisites: ['numbers-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Talk about spending habits. "How much does [item] cost?" "I save money." Use numbers and prices. Ask about what they buy. Keep it simple — candy, toys, snacks. Relatable to everyday life.',
    targetGrammar: ['present-simple', 'numbers-time', 'quantifiers'],
    targetVocab: ['money-basic', 'prices', 'saving-spending', 'everyday-items'],
    difficulty: 'practice',
  },
  {
    id: 'weather-l02',
    title: 'Four Seasons',
    blurb: 'Talk about each season and what you do in them.',
    level: 2, spiralGroup: 'weather', spiralOrder: 2,
    prerequisites: ['weather-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss seasons. "Spring is warm." "In summer I swim." Use present simple for seasonal activities. Name the four seasons and one activity for each. Ask "What do you do in winter?"',
    targetGrammar: ['present-simple', 'prepositions-time', 'conjunctions'],
    targetVocab: ['seasons', 'seasonal-activities', 'weather-adjectives'],
    difficulty: 'practice',
  },
  {
    id: 'nature-l02',
    title: 'Animals Around Us',
    blurb: 'Name animals and describe them simply.',
    level: 2, spiralGroup: 'nature', spiralOrder: 1,
    prerequisites: ['home-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Talk about animals. "I have a cat." "Dogs are friendly." "Birds can fly." Name common animals — cat, dog, bird, fish, rabbit. Use "can" for abilities. Ask about pets. Friendly and curious tone.',
    targetGrammar: ['modals-can', 'present-simple', 'adjectives-basic', 'plurals'],
    targetVocab: ['animals', 'pets', 'animal-actions', 'nature-basic'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'friends-l02',
    title: 'My Best Friend',
    blurb: 'Describe your friend and what you do together.',
    level: 2, spiralGroup: 'friendships', spiralOrder: 1,
    prerequisites: ['meeting-l01'],
    category: 'Social',
    scenarioBrief: 'Ask about their best friend. "Who is your best friend?" "What do you do together?" Use present simple for shared activities. Teach "we play", "we go", "we talk". Keep it warm and personal.',
    targetGrammar: ['present-simple', 'adjectives-basic', 'conjunctions'],
    targetVocab: ['friendship', 'shared-activities', 'personality-basic'],
    difficulty: 'core',
  },
  {
    id: 'friends-l02b',
    title: 'Making New Friends',
    blurb: 'Talk about how to meet and make friends.',
    level: 2, spiralGroup: 'friendships', spiralOrder: 1,
    prerequisites: ['friends-l02'],
    category: 'Social',
    scenarioBrief: 'Discuss making friends. "How do you meet people?" "I say hello." Use simple advice phrases — "you can...", "I like to...". Keep it natural. Share your own tips. Encourage them to share theirs.',
    targetGrammar: ['modals-can', 'imperatives', 'present-simple'],
    targetVocab: ['meeting-people', 'social-actions', 'personality-basic'],
    difficulty: 'practice',
  },
  {
    id: 'celebrate-l02',
    title: 'Let\'s Celebrate!',
    blurb: 'Talk about your favorite holidays and traditions.',
    level: 2, spiralGroup: 'celebrations', spiralOrder: 2,
    prerequisites: [],
    category: 'Social',
    scenarioBrief: 'Ask about celebrations. "What is your favorite holiday?" "How do you celebrate?" Use present simple for traditions. Teach "we eat", "we give gifts", "we visit family". Keep it cultural and curious.',
    targetGrammar: ['present-simple', 'conjunctions', 'questions-wh'],
    targetVocab: ['holidays', 'traditions-basic', 'celebrations', 'family-gatherings'],
    difficulty: 'core',
  },
  {
    id: 'phone-l02',
    title: 'Can I Call You?',
    blurb: 'Make a simple phone call and leave a message.',
    level: 2, spiralGroup: 'communication', spiralOrder: 1,
    prerequisites: ['meeting-l01'],
    category: 'Social',
    scenarioBrief: 'Simple phone conversation. "Hello?" "Can I speak to...?" "Call me later." Use polite requests. Keep it short — just opening and closing a call. Roleplay both sides naturally.',
    targetGrammar: ['modals-can', 'imperatives', 'polite-requests'],
    targetVocab: ['phone-phrases', 'greetings', 'polite-phrases', 'time-words'],
    difficulty: 'core',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'transport-l02',
    title: 'How Do You Get to School?',
    blurb: 'Talk about how you travel from place to place.',
    level: 2, spiralGroup: 'transport', spiralOrder: 1,
    prerequisites: ['city-l01'],
    category: 'Travel',
    scenarioBrief: 'Ask about transport. "I go by bus." "I walk to school." Use "by + vehicle" — car, bus, bike, train. Ask "How do you get to...?" Keep routes simple — home to school, home to work.',
    targetGrammar: ['prepositions-movement', 'present-simple', 'questions-wh'],
    targetVocab: ['transport-types', 'travel-verbs', 'places', 'commuting'],
    difficulty: 'core',
  },
  {
    id: 'hotel-l02',
    title: 'Checking In',
    blurb: 'Check into a hotel and ask for your room.',
    level: 2, spiralGroup: 'hotels', spiralOrder: 1,
    prerequisites: ['numbers-l01'],
    category: 'Travel',
    scenarioBrief: 'Hotel check-in roleplay. "I have a reservation." "Room 205." "Here is your key." Use numbers for room numbers. Simple requests — "I need a towel." Keep the interaction brief and friendly.',
    targetGrammar: ['imperatives', 'have-has', 'numbers-time', 'polite-requests'],
    targetVocab: ['hotel-basic', 'room-items', 'check-in-phrases', 'rooms'],
    difficulty: 'practice',
  },
  {
    id: 'transport-l02b',
    title: 'Buying a Ticket',
    blurb: 'Buy a ticket and ask about departures.',
    level: 2, spiralGroup: 'transport', spiralOrder: 1,
    prerequisites: ['transport-l02'],
    category: 'Travel',
    scenarioBrief: 'Buy a ticket. "One ticket to..." "How much?" "When does it leave?" Use numbers for times and prices. Name destinations. Keep it to one simple transaction. You are the ticket seller.',
    targetGrammar: ['polite-requests', 'numbers-time', 'questions-wh'],
    targetVocab: ['tickets', 'prices', 'destinations', 'time-expressions'],
    difficulty: 'challenge',
  },
  {
    id: 'nature-l02b',
    title: 'A Walk in the Park',
    blurb: 'Describe a park or natural place you enjoy.',
    level: 2, spiralGroup: 'nature', spiralOrder: 1,
    prerequisites: ['city-l01'],
    category: 'Travel',
    scenarioBrief: 'Describe a park or natural area. "There are trees." "I see birds." "The flowers are pretty." Use there-is-are for nature vocabulary. Ask about their favorite natural spot. Create a peaceful scene.',
    targetGrammar: ['there-is-are', 'adjectives-basic', 'present-continuous'],
    targetVocab: ['nature-words', 'parks', 'trees-plants', 'animals-basic'],
    difficulty: 'practice',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'restaurant-l02',
    title: 'Ordering a Meal',
    blurb: 'Order a full meal at a simple restaurant.',
    level: 2, spiralGroup: 'restaurant', spiralOrder: 1,
    prerequisites: ['cafe-l01', 'food-l01b'],
    category: 'Daily Life',
    scenarioBrief: 'Restaurant roleplay. You are the server. The user orders a meal — starter, main, drink. Use "I would like..." Full but simple. Ask about preferences — "with rice or bread?" Keep it flowing.',
    targetGrammar: ['polite-requests', 'would-like', 'conjunctions'],
    targetVocab: ['menu-items', 'meal-words', 'order-phrases', 'food-adjectives'],
    difficulty: 'core',
  },
  {
    id: 'services-l02',
    title: 'At the Post Office',
    blurb: 'Send a package and ask about prices.',
    level: 2, spiralGroup: 'services', spiralOrder: 1,
    prerequisites: ['numbers-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Post office roleplay. "I want to send this." "How much?" "To [country]." Use numbers for prices. Simple transaction. Name countries. You are the postal worker. Friendly and helpful tone.',
    targetGrammar: ['imperatives', 'numbers-time', 'polite-requests', 'questions-wh'],
    targetVocab: ['post-office', 'countries', 'prices', 'sending-items'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'school-l02',
    title: 'My School Day',
    blurb: 'Describe a typical day at school.',
    level: 2, spiralGroup: 'school', spiralOrder: 1,
    prerequisites: ['routines-l01'],
    category: 'Work & Study',
    scenarioBrief: 'Talk about school or studies. "I study math." "My teacher is nice." "I have class at 9." Use present simple for subjects and schedules. Ask about favorite subjects. Share made-up school memories.',
    targetGrammar: ['present-simple', 'prepositions-time', 'adjectives-basic', 'have-has'],
    targetVocab: ['school-subjects', 'classroom-words', 'teachers', 'homework'],
    difficulty: 'core',
  },
  {
    id: 'school-l02b',
    title: 'My Favorite Subject',
    blurb: 'Talk about subjects you enjoy and why.',
    level: 2, spiralGroup: 'school', spiralOrder: 1,
    prerequisites: ['school-l02'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss favorite school subjects. "I like art because it\'s fun." "I don\'t like math." Use because to give reasons. Teach subject names — science, history, art, music, English. Keep it conversational.',
    targetGrammar: ['present-simple', 'like-gerund', 'conjunctions', 'adjectives-basic'],
    targetVocab: ['school-subjects', 'like-dislike', 'opinion-basic', 'reasons'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'memories-l02',
    title: 'Last Weekend',
    blurb: 'Talk about what you did last weekend.',
    level: 2, spiralGroup: 'memories', spiralOrder: 1,
    prerequisites: ['routines-l01'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask about last weekend. Use simple past with common verbs — "I played", "I watched", "I visited". Keep irregular verbs to a minimum (went, ate, saw). Ask "What did you do?" Follow up with "Did you like it?"',
    targetGrammar: ['past-simple', 'questions-wh', 'questions-yesno'],
    targetVocab: ['weekend-activities', 'past-verbs-basic', 'time-expressions'],
    difficulty: 'core',
  },
  {
    id: 'memories-l02b',
    title: 'A Fun Day Out',
    blurb: 'Describe a fun day you remember.',
    level: 2, spiralGroup: 'memories', spiralOrder: 1,
    prerequisites: ['memories-l02'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask about a memorable fun day. Use simple past. "Where did you go?" "Who was with you?" "What did you do?" Prompt for 2-3 details. Share a simple made-up story. Celebrate their sharing.',
    targetGrammar: ['past-simple', 'past-simple-to-be', 'questions-wh', 'conjunctions'],
    targetVocab: ['fun-activities', 'places', 'people', 'time-expressions'],
    difficulty: 'practice',
  },
]
