import type { ConversationSeed } from '../types'

/**
 * Level 3 — Survival Mode
 * AI: 40% native, 60% target. Simple sentences (5-8 words), present tense + some past.
 * 25 seeds: Self (5), Daily (7), Social (4), Travel (3), Commerce (4), Work (1), Ideas (1)
 */

export const SEEDS_L03: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l03',
    title: 'Tell Me About Yourself',
    blurb: 'Introduce yourself in more detail — job, hobbies, where you live.',
    level: 3, spiralGroup: 'identity', spiralOrder: 2,
    prerequisites: ['whoami-l01'],
    category: 'Daily Life',
    scenarioBrief: 'A deeper introduction. Ask about their life — job, where they live, what they do. Use full sentences. Push for 2-3 details. Share about yourself. Model simple sentences with "and" and "but".',
    targetGrammar: ['present-simple', 'conjunctions', 'questions-wh'],
    targetVocab: ['introductions', 'jobs-basic', 'hobbies', 'daily-life'],
    difficulty: 'core',
  },
  {
    id: 'family-l03',
    title: 'A Story About My Family',
    blurb: 'Tell a short story about something your family did together.',
    level: 3, spiralGroup: 'family', spiralOrder: 2,
    prerequisites: ['family-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about a family memory or activity. "We went to the beach." "My mom cooked dinner." Use simple past for a short narrative. Push for 2-3 connected sentences. Share a simple family story too.',
    targetGrammar: ['past-simple', 'conjunctions', 'prepositions-time'],
    targetVocab: ['family-members', 'past-actions', 'places', 'food'],
    difficulty: 'core',
  },
  {
    id: 'home-l03',
    title: 'My Dream Home',
    blurb: 'Describe your ideal home and what it would have.',
    level: 3, spiralGroup: 'home', spiralOrder: 2,
    prerequisites: ['home-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about their dream home. "I want a big kitchen." "There are three bedrooms." Use "I want", "there is/are", "I like". Push for 3-4 details. Use descriptive adjectives. Keep it imaginative and fun.',
    targetGrammar: ['there-is-are', 'would-like', 'adjectives-basic', 'comparatives'],
    targetVocab: ['rooms', 'furniture', 'house-adjectives', 'dream-home'],
    difficulty: 'practice',
  },
  {
    id: 'style-l03',
    title: 'My Style',
    blurb: 'Describe your fashion style and what you like to wear.',
    level: 3, spiralGroup: 'appearance', spiralOrder: 2,
    prerequisites: ['clothes-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss fashion preferences. "I like casual clothes." "I wear jeans and t-shirts." Use present simple for habits. Introduce "usually", "often". Ask about colors and styles they prefer.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'adjectives-basic', 'like-gerund'],
    targetVocab: ['clothing', 'styles', 'fashion-adjectives', 'colors'],
    difficulty: 'practice',
  },
  {
    id: 'feelings-l03',
    title: 'What Makes You Happy?',
    blurb: 'Talk about things that affect your mood.',
    level: 3, spiralGroup: 'feelings', spiralOrder: 2,
    prerequisites: ['feelings-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Explore emotions more deeply. "Sunny weather makes me happy." "I feel nervous before tests." Use "makes me + adjective" and "I feel + adjective when...". Push for reasons. Empathetic tone.',
    targetGrammar: ['present-simple', 'conjunctions', 'adjectives-basic', 'gerunds'],
    targetVocab: ['emotions-extended', 'causes', 'reactions', 'daily-situations'],
    difficulty: 'practice',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'food-l03',
    title: 'Let\'s Cook Together',
    blurb: 'Describe how to make a simple dish.',
    level: 3, spiralGroup: 'food', spiralOrder: 2,
    prerequisites: ['food-l01b'],
    category: 'Daily Life',
    scenarioBrief: 'Ask them to explain a simple recipe. "First, cut the vegetables. Then, cook them." Use imperatives and sequence words — first, then, after that. Teach cooking verbs — chop, mix, boil, fry.',
    targetGrammar: ['imperatives', 'conjunctions', 'prepositions-time'],
    targetVocab: ['cooking-verbs', 'food-ingredients', 'kitchen-tools', 'sequence-words'],
    difficulty: 'core',
  },
  {
    id: 'food-l03b',
    title: 'At the Market',
    blurb: 'Shop for ingredients at a market.',
    level: 3, spiralGroup: 'food', spiralOrder: 2,
    prerequisites: ['food-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Market roleplay. You are a vendor. The user buys ingredients. "How much are the apples?" "I need two kilos." Use numbers, quantities, and prices. Introduce "some", "a kilo of", "a bag of".',
    targetGrammar: ['quantifiers', 'numbers-time', 'polite-requests', 'plurals'],
    targetVocab: ['food-items', 'quantities', 'prices', 'market-phrases'],
    difficulty: 'practice',
  },
  {
    id: 'routines-l03',
    title: 'A Day in My Life',
    blurb: 'Describe your entire day from morning to night.',
    level: 3, spiralGroup: 'routines', spiralOrder: 2,
    prerequisites: ['routines-l01b'],
    category: 'Daily Life',
    scenarioBrief: 'Full daily routine. From waking up to going to bed. Use sequence words — first, then, after that, finally. Push for 5-6 connected sentences. Use time expressions — "at 7", "in the morning", "at night".',
    targetGrammar: ['present-simple', 'prepositions-time', 'adverbs-frequency'],
    targetVocab: ['daily-routines', 'time-expressions', 'daily-activities', 'sequence-words'],
    difficulty: 'core',
  },
  {
    id: 'hobbies-l03',
    title: 'My Favorite Hobby',
    blurb: 'Describe a hobby you enjoy in detail.',
    level: 3, spiralGroup: 'hobbies', spiralOrder: 2,
    prerequisites: ['hobbies-l01b'],
    category: 'Daily Life',
    scenarioBrief: 'Deep dive into a hobby. Ask "when did you start?", "how often do you do it?", "why do you like it?" Use present simple with frequency. Push for 3-4 sentences. Share your own hobby to keep it conversational.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'questions-wh', 'conjunctions'],
    targetVocab: ['hobbies', 'frequency-words', 'opinion-phrases', 'activity-verbs'],
    difficulty: 'core',
  },
  {
    id: 'hobbies-l03b',
    title: 'Weekend Fun',
    blurb: 'Talk about what you usually do on weekends.',
    level: 3, spiralGroup: 'hobbies', spiralOrder: 2,
    prerequisites: ['hobbies-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss weekend routines. "On Saturdays I play football." "I usually visit my grandmother." Use adverbs of frequency — always, usually, sometimes, never. Push for weekend schedule details.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'prepositions-time'],
    targetVocab: ['weekend-activities', 'frequency-words', 'leisure', 'family-time'],
    difficulty: 'practice',
  },
  {
    id: 'weather-l03',
    title: 'What\'s the Weather Like?',
    blurb: 'Describe today\'s weather and what you can do in it.',
    level: 3, spiralGroup: 'weather', spiralOrder: 2,
    prerequisites: ['weather-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss current weather. "It\'s raining today." "You need an umbrella." Use present continuous for current weather. Connect weather to activities — "when it\'s sunny, I go to the beach." Push for 3 sentences.',
    targetGrammar: ['present-continuous', 'conjunctions', 'modals-can'],
    targetVocab: ['weather-extended', 'weather-activities', 'clothing-weather'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'meeting-l03',
    title: 'Introducing a Friend',
    blurb: 'Introduce someone and say a few things about them.',
    level: 3, spiralGroup: 'meeting-people', spiralOrder: 2,
    prerequisites: ['meeting-l01b'],
    category: 'Social',
    scenarioBrief: 'Practice three-way introductions. "This is my friend, Anna." "She likes music." Use third person present simple. Introduce someone and describe them in 2-3 sentences. Roleplay with the AI as a third person.',
    targetGrammar: ['present-simple', 'possessives', 'adjectives-basic', 'conjunctions'],
    targetVocab: ['introductions', 'personality-basic', 'relationships', 'hobbies'],
    difficulty: 'practice',
  },
  {
    id: 'relationships-l03',
    title: 'People in My Life',
    blurb: 'Talk about important people and your relationship with them.',
    level: 3, spiralGroup: 'relationships', spiralOrder: 1,
    prerequisites: ['family-l03'],
    category: 'Social',
    scenarioBrief: 'Ask about important people. "My best friend is kind." "My sister is funny." Use present simple for descriptions. Describe 2-3 people with 2 details each. Push for reasons — "I like her because..."',
    targetGrammar: ['present-simple', 'conjunctions', 'adjectives-basic', 'possessives'],
    targetVocab: ['relationships', 'personality-adjectives', 'family', 'friends'],
    difficulty: 'core',
  },
  {
    id: 'social-l03',
    title: 'At a Party',
    blurb: 'Chat with people at a social gathering.',
    level: 3, spiralGroup: 'social-situations', spiralOrder: 1,
    prerequisites: ['meeting-l03'],
    category: 'Social',
    scenarioBrief: 'Party small talk. "Great party!" "Have you tried the food?" Use simple social phrases. Ask about their day, compliment something, say goodbye. Keep it natural. You are a friendly guest at the same party.',
    targetGrammar: ['present-simple', 'questions-wh', 'imperatives', 'modals-can'],
    targetVocab: ['party-phrases', 'small-talk', 'compliments', 'social-greetings'],
    difficulty: 'practice',
  },
  {
    id: 'social-l03b',
    title: 'Asking for Help',
    blurb: 'Politely ask for help in different situations.',
    level: 3, spiralGroup: 'social-situations', spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief: 'Practice polite requests. "Can you help me?" "Could you open the door?" Use modals for polite requests. Different scenarios — at a store, at work, on the street. Teach "please" and "thank you" naturally.',
    targetGrammar: ['modals-can', 'modals-could', 'imperatives', 'polite-requests'],
    targetVocab: ['help-phrases', 'polite-requests', 'everyday-situations'],
    difficulty: 'practice',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'city-l03',
    title: 'Giving Directions',
    blurb: 'Give simple directions to places in a city.',
    level: 3, spiralGroup: 'city', spiralOrder: 2,
    prerequisites: ['city-l01b'],
    category: 'Travel',
    scenarioBrief: 'Give directions. "Go straight." "Turn left." "It\'s on your right." Use imperatives for directions. Teach place vocabulary — corner, block, traffic light, crossing. Practice giving a 3-step route.',
    targetGrammar: ['imperatives', 'prepositions-place', 'prepositions-movement'],
    targetVocab: ['directions', 'city-places', 'street-words', 'landmarks'],
    difficulty: 'core',
  },
  {
    id: 'travel-l03',
    title: 'Planning a Trip',
    blurb: 'Plan a simple trip to a nearby place.',
    level: 3, spiralGroup: 'travel-planning', spiralOrder: 1,
    prerequisites: ['transport-l02b'],
    category: 'Travel',
    scenarioBrief: 'Plan a day trip. "Let\'s go to the beach." "We can take the train." "It takes two hours." Use "let\'s", "we can", "we need". Plan step by step. Push for 3-4 details about the trip.',
    targetGrammar: ['modals-can', 'future-going-to', 'conjunctions', 'imperatives'],
    targetVocab: ['travel-plans', 'destinations', 'transport', 'time-estimates'],
    difficulty: 'core',
  },
  {
    id: 'travel-l03b',
    title: 'Asking for Directions',
    blurb: 'Ask for directions when you\'re lost.',
    level: 3, spiralGroup: 'travel-planning', spiralOrder: 1,
    prerequisites: ['city-l03'],
    category: 'Travel',
    scenarioBrief: 'You are lost. Ask for directions. "Excuse me, where is the museum?" "How do I get to the station?" Use polite question forms. You are the lost traveler; the AI is a local. Practice 2-3 different scenarios.',
    targetGrammar: ['questions-wh', 'polite-requests', 'imperatives', 'prepositions-place'],
    targetVocab: ['directions', 'polite-phrases', 'city-places', 'landmarks'],
    difficulty: 'practice',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'cafe-l03',
    title: 'Coffee Shop Chat',
    blurb: 'Order at a coffee shop and make small talk with the barista.',
    level: 3, spiralGroup: 'cafe', spiralOrder: 2,
    prerequisites: ['cafe-l01'],
    category: 'Daily Life',
    scenarioBrief: 'Coffee shop interaction. Order a drink plus food. Make small talk — "busy day?" "The weather is nice." Use polite requests. Push for a 4-turn exchange. You are the barista. Warm and friendly.',
    targetGrammar: ['polite-requests', 'present-simple', 'questions-wh', 'conjunctions'],
    targetVocab: ['coffee-shop', 'drinks-extended', 'snacks', 'small-talk'],
    difficulty: 'core',
  },
  {
    id: 'restaurant-l03',
    title: 'Dinner Out',
    blurb: 'Order a full meal at a restaurant with preferences.',
    level: 3, spiralGroup: 'restaurant', spiralOrder: 2,
    prerequisites: ['restaurant-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Full restaurant experience. Reserve a table, order, ask about the menu, pay. "Could I have the menu?" "What do you recommend?" "The steak, please." Push for a complete dining interaction.',
    targetGrammar: ['modals-could', 'polite-requests', 'would-like', 'comparatives'],
    targetVocab: ['restaurant', 'menu-items', 'food-adjectives', 'dining-phrases'],
    difficulty: 'core',
  },
  {
    id: 'shopping-l03',
    title: 'Clothes Shopping',
    blurb: 'Try on clothes, ask about sizes and prices.',
    level: 3, spiralGroup: 'shopping', spiralOrder: 2,
    prerequisites: ['style-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Clothes store roleplay. You are the shop assistant. The user wants to buy clothes. "Do you have this in blue?" "Can I try it on?" "It\'s too small." Use comparatives — bigger, smaller, cheaper.',
    targetGrammar: ['comparatives', 'modals-can', 'questions-yesno', 'adjectives-basic'],
    targetVocab: ['clothing', 'sizes', 'colors', 'shopping-phrases', 'prices'],
    difficulty: 'core',
  },
  {
    id: 'bargain-l03',
    title: 'At the Flea Market',
    blurb: 'Negotiate a price for an item at a market.',
    level: 3, spiralGroup: 'bargaining', spiralOrder: 1,
    prerequisites: ['shopping-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Market bargaining. "How much is this?" "Too expensive!" "Can you lower the price?" Use numbers, comparatives, and polite disagreement. Roleplay back and forth 3-4 rounds. Keep it playful.',
    targetGrammar: ['comparatives', 'modals-can', 'polite-requests', 'questions-wh'],
    targetVocab: ['bargaining', 'prices', 'quality-adjectives', 'money-phrases'],
    difficulty: 'challenge',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'jobs-l03',
    title: 'What Do You Want to Be?',
    blurb: 'Talk about jobs you admire and career dreams.',
    level: 3, spiralGroup: 'jobs', spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief: 'Discuss careers. "What do you want to be?" "I want to be a teacher." "A doctor helps people." Use "want to be" and present simple for job descriptions. Name 5-6 jobs. Ask for reasons.',
    targetGrammar: ['want-to', 'present-simple', 'questions-wh', 'conjunctions'],
    targetVocab: ['job-names', 'careers', 'professions', 'job-actions'],
    difficulty: 'core',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'opinion-l03',
    title: 'My Opinion',
    blurb: 'Give your opinion on everyday topics.',
    level: 3, spiralGroup: 'opinions', spiralOrder: 2,
    prerequisites: ['opinion-l01'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask for opinions on everyday topics. "I think cats are better than dogs." "In my opinion, summer is the best season." Use "I think", "in my opinion". Push for reasons with "because". Light debate.',
    targetGrammar: ['present-simple', 'conjunctions', 'comparatives', 'like-gerund'],
    targetVocab: ['opinion-phrases', 'comparison', 'reasons', 'everyday-topics'],
    difficulty: 'core',
  },
]
