import type { ConversationSeed } from '../types'

/**
 * Level 4 — Getting Comfortable
 * AI: 25% native, 75% target. 1-2 sentences, past + present tenses.
 * 25 seeds: Story (4), Daily (7), Social (4), Travel (4), Commerce (2), Work (2), Ideas (2)
 */

export const SEEDS_L04: ConversationSeed[] = [
  // ── Story & Self ────────────────────────────────────────────────────────
  {
    id: 'mystory-l04',
    title: 'A Big Change',
    blurb: 'Talk about a big change in your life.',
    level: 4, spiralGroup: 'story', spiralOrder: 2,
    prerequisites: ['mystory-l02'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask about a life change — moving, new school, new job. "Before, I lived in..." "Then I moved to..." Use past simple and "used to". Push for a short narrative of 3-4 sentences. Empathetic tone.',
    targetGrammar: ['past-simple', 'used-to', 'conjunctions', 'prepositions-time'],
    targetVocab: ['life-changes', 'moving', 'past-habits', 'adaptation'],
    difficulty: 'core',
  },
  {
    id: 'memories-l04',
    title: 'My Best Memory',
    blurb: 'Share a happy memory and describe it in detail.',
    level: 4, spiralGroup: 'memories', spiralOrder: 2,
    prerequisites: ['memories-l02b'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask for a detailed happy memory. "Where were you?" "Who was there?" "What happened?" Use past tenses. Push for descriptive details — sounds, smells, feelings. 4-5 sentence narrative expected.',
    targetGrammar: ['past-simple', 'past-continuous', 'conjunctions', 'questions-wh'],
    targetVocab: ['memories', 'emotions', 'sensory-words', 'past-events'],
    difficulty: 'core',
  },
  {
    id: 'memories-l04b',
    title: 'A Funny Story',
    blurb: 'Tell a funny or embarrassing story from your past.',
    level: 4, spiralGroup: 'memories', spiralOrder: 2,
    prerequisites: ['memories-l04'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Share a funny anecdote. "Once, I..." "I was laughing so hard!" Use past continuous for background + past simple for events. Push for narrative structure — beginning, middle, end. Light and fun.',
    targetGrammar: ['past-simple', 'past-continuous', 'conjunctions', 'time-connectors'],
    targetVocab: ['comedy', 'reactions', 'story-verbs', 'time-markers'],
    difficulty: 'practice',
  },
  {
    id: 'health-l04',
    title: 'Staying Healthy',
    blurb: 'Talk about your healthy (or unhealthy) habits.',
    level: 4, spiralGroup: 'health', spiralOrder: 2,
    prerequisites: ['health-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss health habits. "I exercise three times a week." "I should eat more vegetables." Use should/shouldn\'t for advice. Adverbs of frequency. Push for comparison — "I should... but I..."',
    targetGrammar: ['modals-should', 'adverbs-frequency', 'present-simple', 'conjunctions'],
    targetVocab: ['health-habits', 'exercise', 'food', 'wellness-phrases'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'tech-l04',
    title: 'How Tech Changed My Life',
    blurb: 'Discuss how technology has changed daily life.',
    level: 4, spiralGroup: 'technology', spiralOrder: 2,
    prerequisites: ['tech-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss tech\'s impact. "Before smartphones, I used a map." "Now I use GPS." Use used-to vs present. Compare past and present habits. Push for 3-4 comparison sentences. Natural conversational tone.',
    targetGrammar: ['used-to', 'present-simple', 'comparatives', 'conjunctions'],
    targetVocab: ['technology', 'past-vs-present', 'digital-habits', 'comparison'],
    difficulty: 'core',
  },
  {
    id: 'money-l04',
    title: 'Saving for Something Special',
    blurb: 'Talk about saving money for a goal.',
    level: 4, spiralGroup: 'money', spiralOrder: 2,
    prerequisites: ['money-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss financial goals. "I\'m saving for a trip." "I need to save $500." Use present continuous for current plans. "Need to" for obligations. Push for plan details — how much, by when, why.',
    targetGrammar: ['present-continuous', 'need-to', 'future-going-to', 'numbers-time'],
    targetVocab: ['money', 'saving', 'goals', 'plans', 'numbers-extended'],
    difficulty: 'practice',
  },
  {
    id: 'routines-l04',
    title: 'My Weekly Routine',
    blurb: 'Describe a full week of your life.',
    level: 4, spiralGroup: 'routines', spiralOrder: 3,
    prerequisites: ['routines-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Describe weekly activities. "On Mondays I have class." "I usually go out on Fridays." Use days of the week, frequency, and varied time expressions. Push for a full week overview in 5-6 sentences.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'prepositions-time', 'conjunctions'],
    targetVocab: ['days-of-week', 'weekly-routines', 'activities', 'frequency'],
    difficulty: 'practice',
  },
  {
    id: 'food-l04',
    title: 'My Favorite Meal',
    blurb: 'Describe your favorite meal and why you love it.',
    level: 4, spiralGroup: 'food', spiralOrder: 3,
    prerequisites: ['food-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Describe a favorite meal in detail. "My grandmother makes the best pasta." Use present simple for facts, past for memories of the first time. Push for sensory description — taste, smell, texture.',
    targetGrammar: ['present-simple', 'past-simple', 'superlatives', 'adjectives-basic'],
    targetVocab: ['food-extended', 'taste-adjectives', 'cooking', 'family-recipes'],
    difficulty: 'practice',
  },
  {
    id: 'food-l04b',
    title: 'Eating Out vs Home Cooking',
    blurb: 'Compare eating out with cooking at home.',
    level: 4, spiralGroup: 'food', spiralOrder: 3,
    prerequisites: ['food-l04'],
    category: 'Daily Life',
    scenarioBrief: 'Compare. "Restaurant food is more expensive." "Home cooking is healthier." Use comparatives and contrasting connectors — but, however, while. Push for 3 comparison points. Natural conversational debate.',
    targetGrammar: ['comparatives', 'conjunctions', 'present-simple', 'quantifiers'],
    targetVocab: ['comparison', 'food-adjectives', 'restaurant-vs-home', 'opinions'],
    difficulty: 'challenge',
  },
  {
    id: 'hobbies-l04',
    title: 'Learning Something New',
    blurb: 'Talk about a skill you\'re learning or want to learn.',
    level: 4, spiralGroup: 'hobbies', spiralOrder: 3,
    prerequisites: ['hobbies-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss learning new skills. "I\'m learning to play guitar." "I want to learn cooking." Use present continuous for current learning. "Want to" for desires. Push for reasons and progress updates.',
    targetGrammar: ['present-continuous', 'want-to', 'conjunctions', 'questions-wh'],
    targetVocab: ['skills', 'learning', 'hobbies-extended', 'progress-words'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'friends-l04',
    title: 'What Makes a Good Friend?',
    blurb: 'Describe qualities you value in a friend.',
    level: 4, spiralGroup: 'friendships', spiralOrder: 2,
    prerequisites: ['friends-l02b'],
    category: 'Social',
    scenarioBrief: 'Discuss friendship qualities. "A good friend is honest." "They listen when I\'m sad." Use present simple for general truths. Push for 3-4 qualities with examples. "I like friends who..."',
    targetGrammar: ['present-simple', 'relative-pronouns', 'adjectives-basic', 'conjunctions'],
    targetVocab: ['friendship-qualities', 'personality', 'values', 'relationships'],
    difficulty: 'core',
  },
  {
    id: 'celebrate-l04',
    title: 'How We Celebrate',
    blurb: 'Describe your culture\'s unique celebrations.',
    level: 4, spiralGroup: 'celebrations', spiralOrder: 2,
    prerequisites: ['celebrate-l02'],
    category: 'Social',
    scenarioBrief: 'Discuss cultural celebrations. "In my country, we eat special food." "We visit family." Use "we" for cultural customs. Present simple for traditions. Push for 3-4 details. Encourage cultural pride.',
    targetGrammar: ['present-simple', 'conjunctions', 'prepositions-time'],
    targetVocab: ['traditions', 'celebrations', 'cultural-customs', 'food-traditions'],
    difficulty: 'practice',
  },
  {
    id: 'phone-l04',
    title: 'Texting vs Calling',
    blurb: 'Compare texting and phone calls — which do you prefer?',
    level: 4, spiralGroup: 'communication', spiralOrder: 2,
    prerequisites: ['phone-l02'],
    category: 'Social',
    scenarioBrief: 'Compare communication styles. "I prefer texting because it\'s faster." "Calls are more personal." Use comparatives and reasons. Push for opinion with justification. Natural conversation about daily habits.',
    targetGrammar: ['comparatives', 'present-simple', 'conjunctions', 'preference-phrases'],
    targetVocab: ['communication', 'phone', 'texting', 'preferences', 'comparison'],
    difficulty: 'practice',
  },
  {
    id: 'friends-l04b',
    title: 'Resolving a Misunderstanding',
    blurb: 'Talk about how to fix a small problem with a friend.',
    level: 4, spiralGroup: 'friendships', spiralOrder: 2,
    prerequisites: ['friends-l04'],
    category: 'Social',
    scenarioBrief: 'Discuss resolving conflicts. "I said something wrong." "We talked and I apologized." Use past simple for the event. "Should" for advice. Introduce apology phrases. Push for a short resolution narrative.',
    targetGrammar: ['past-simple', 'modals-should', 'conjunctions', 'reported-speech-light'],
    targetVocab: ['conflict', 'apology', 'resolution', 'feelings-extended'],
    difficulty: 'challenge',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'transport-l04',
    title: 'My Commute',
    blurb: 'Describe your daily commute or journey to school.',
    level: 4, spiralGroup: 'transport', spiralOrder: 2,
    prerequisites: ['transport-l02'],
    category: 'Travel',
    scenarioBrief: 'Describe commute. "I take the bus for 20 minutes." "I walk to the station." Use present simple, time expressions, and transport vocabulary. Push for 4-5 sentences with details about the journey.',
    targetGrammar: ['present-simple', 'prepositions-movement', 'prepositions-time', 'quantifiers'],
    targetVocab: ['commute', 'transport-types', 'time', 'route-details'],
    difficulty: 'practice',
  },
  {
    id: 'hotel-l04',
    title: 'Hotel Problems',
    blurb: 'Handle a small problem at a hotel.',
    level: 4, spiralGroup: 'hotels', spiralOrder: 2,
    prerequisites: ['hotel-l02'],
    category: 'Travel',
    scenarioBrief: 'Hotel issue roleplay. "The AC doesn\'t work." "There\'s no hot water." Use simple complaints. Teach polite complaint phrases — "I\'m afraid...", "Could you please..." Practice 2-3 issue resolutions.',
    targetGrammar: ['present-simple', 'modals-could', 'polite-requests', 'there-is-are'],
    targetVocab: ['hotel-problems', 'complaints', 'polite-phrases', 'room-features'],
    difficulty: 'practice',
  },
  {
    id: 'culture-l04',
    title: 'Visiting a Museum',
    blurb: 'Talk about visiting a museum and what you saw.',
    level: 4, spiralGroup: 'cultural-experiences', spiralOrder: 1,
    prerequisites: ['travel-l03'],
    category: 'Travel',
    scenarioBrief: 'Discuss a museum visit. "I saw ancient paintings." "The exhibit was fascinating." Use past simple for what you saw. Adjectives for reactions. Push for 3-4 descriptive sentences. Share your own made-up visit.',
    targetGrammar: ['past-simple', 'adjectives-basic', 'there-is-are', 'conjunctions'],
    targetVocab: ['museum', 'art', 'history-basic', 'exhibits', 'reactions'],
    difficulty: 'core',
  },
  {
    id: 'nature-l04',
    title: 'Exploring the Outdoors',
    blurb: 'Describe a hike or outdoor adventure.',
    level: 4, spiralGroup: 'nature', spiralOrder: 2,
    prerequisites: ['nature-l02'],
    category: 'Travel',
    scenarioBrief: 'Describe an outdoor experience. "We hiked up a mountain." "The view was amazing!" Use past simple for narrative. Push for sensory details — what they saw, heard, felt. 4-5 sentence story.',
    targetGrammar: ['past-simple', 'past-continuous', 'adjectives-basic', 'prepositions-place'],
    targetVocab: ['nature-extended', 'landscape', 'outdoor-activities', 'sensory-words'],
    difficulty: 'core',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'restaurant-l04',
    title: 'Complaining at a Restaurant',
    blurb: 'Politely complain about food or service.',
    level: 4, spiralGroup: 'restaurant', spiralOrder: 3,
    prerequisites: ['restaurant-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Restaurant complaint. "The soup is cold." "I ordered steak, not fish." Use polite complaint phrases. Practice getting a resolution — new dish, discount, apology. 4-5 turn exchange. Stay polite.',
    targetGrammar: ['present-simple', 'modals-could', 'polite-requests', 'past-simple'],
    targetVocab: ['complaints', 'restaurant', 'food-issues', 'resolution-phrases'],
    difficulty: 'challenge',
  },
  {
    id: 'services-l04',
    title: 'At the Pharmacy',
    blurb: 'Ask for medicine and describe symptoms.',
    level: 4, spiralGroup: 'services', spiralOrder: 2,
    prerequisites: ['health-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Pharmacy roleplay. "I have a headache." "Do you have medicine for..." Use "I have + symptom", "I need". Describe symptoms in 1-2 sentences. You are the customer; AI is the pharmacist.',
    targetGrammar: ['have-has', 'modals-can', 'present-simple', 'questions-wh'],
    targetVocab: ['symptoms', 'medicine', 'pharmacy', 'health-extended'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'school-l04',
    title: 'School Then vs Now',
    blurb: 'Compare your school experience in the past and present.',
    level: 4, spiralGroup: 'school', spiralOrder: 2,
    prerequisites: ['school-l02b'],
    category: 'Work & Study',
    scenarioBrief: 'Compare school experiences. "I used to hate math, but now I like it." "My teachers were strict." Use used-to vs present. Push for 3 comparison points. Natural nostalgic conversation.',
    targetGrammar: ['used-to', 'present-simple', 'comparatives', 'conjunctions'],
    targetVocab: ['school-memories', 'subjects', 'teachers', 'comparing-past-present'],
    difficulty: 'core',
  },
  {
    id: 'skills-l04',
    title: 'Things I\'m Good At',
    blurb: 'Talk about your talents and abilities.',
    level: 4, spiralGroup: 'skills', spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief: 'Discuss talents and abilities. "I\'m good at drawing." "I can speak two languages." Use "be good at", "can", "know how to". Push for 3-4 strengths. Ask "How did you learn?" for past tense practice.',
    targetGrammar: ['modals-can', 'present-simple', 'past-simple', 'questions-wh'],
    targetVocab: ['talents', 'abilities', 'skills', 'learning-verbs'],
    difficulty: 'core',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'goals-l04',
    title: 'My Goals This Year',
    blurb: 'Talk about your goals for the current year.',
    level: 4, spiralGroup: 'dreams-goals', spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss yearly goals. "I want to learn Japanese." "I\'m going to exercise more." Use "want to" and "going to". Push for 3 goals with reasons and plans. Share your own goals. Encouraging tone.',
    targetGrammar: ['future-going-to', 'want-to', 'present-continuous', 'conjunctions'],
    targetVocab: ['goals', 'plans', 'aspirations', 'self-improvement'],
    difficulty: 'core',
  },
  {
    id: 'advice-l04',
    title: 'What Should I Do?',
    blurb: 'Give advice for common everyday problems.',
    level: 4, spiralGroup: 'advice', spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief: 'Give advice. "I\'m tired all the time." "You should sleep more." Present a problem, ask for their advice. Use "should/shouldn\'t", "why don\'t you", "you could". Practice 2-3 different problems.',
    targetGrammar: ['modals-should', 'modals-could', 'imperatives', 'second-person'],
    targetVocab: ['advice', 'problems', 'solutions', 'health', 'daily-issues'],
    difficulty: 'core',
  },
]
