import type { ConversationSeed } from '../types'

/**
 * Level 5 — Conversation Ready
 * AI: 15% native, 85% target. Multiple sentences, present/past/future.
 * 25 seeds: Self (4), Daily (6), Social (4), Travel (4), Commerce (3), Work (2), Ideas (2)
 */

export const SEEDS_L05: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l05',
    title: 'Who I Am Now',
    blurb: 'Give a fuller introduction about your life and personality.',
    level: 5, spiralGroup: 'identity', spiralOrder: 3,
    prerequisites: ['whoami-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Ask for a complete self-introduction. Job, home, hobbies, personality. "I\'m a teacher who loves hiking." Use relative clauses. Push for 4-5 connected sentences. Model with your own introduction.',
    targetGrammar: ['present-simple', 'relative-pronouns', 'conjunctions', 'discourse-markers'],
    targetVocab: ['personality-extended', 'roles', 'identity', 'life-situation'],
    difficulty: 'core',
  },
  {
    id: 'family-l05',
    title: 'Family Traditions',
    blurb: 'Describe traditions your family has.',
    level: 5, spiralGroup: 'family', spiralOrder: 3,
    prerequisites: ['family-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss family traditions. "Every Sunday we have dinner together." "My grandmother always cooks for holidays." Use present simple for recurring traditions. Push for 3-4 traditions with details.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'conjunctions', 'prepositions-time'],
    targetVocab: ['traditions', 'family-customs', 'holidays', 'food-traditions'],
    difficulty: 'core',
  },
  {
    id: 'home-l05',
    title: 'My Ideal Neighborhood',
    blurb: 'Describe your perfect neighborhood and why.',
    level: 5, spiralGroup: 'home', spiralOrder: 3,
    prerequisites: ['home-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Describe an ideal neighborhood. "There should be parks and cafes." "I want my neighbors to be friendly." Use modals (should, would, could). Push for 4-5 details about the area and lifestyle.',
    targetGrammar: ['modals-should', 'modals-could', 'there-is-are', 'conditional-zero'],
    targetVocab: ['neighborhood', 'community', 'amenities', 'lifestyle'],
    difficulty: 'practice',
  },
  {
    id: 'feelings-l05',
    title: 'Managing Emotions',
    blurb: 'Talk about how you handle difficult emotions.',
    level: 5, spiralGroup: 'feelings', spiralOrder: 3,
    prerequisites: ['feelings-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss emotional management. "When I\'m stressed, I go for a walk." "I feel anxious before presentations." Use zero conditional and advice structures. Push for coping strategies. Empathetic tone.',
    targetGrammar: ['conditional-zero', 'modals-should', 'conjunctions', 'gerunds'],
    targetVocab: ['emotions-complex', 'coping-strategies', 'stress-management', 'wellbeing'],
    difficulty: 'practice',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'food-l05',
    title: 'Restaurant Review',
    blurb: 'Review a restaurant you\'ve been to recently.',
    level: 5, spiralGroup: 'food', spiralOrder: 4,
    prerequisites: ['food-l04b'],
    category: 'Daily Life',
    scenarioBrief: 'Ask about a recent restaurant visit. "The food was excellent." "The service was slow." Use past simple for the experience, present for opinions. Push for a structured review — food, service, atmosphere, price.',
    targetGrammar: ['past-simple', 'superlatives', 'comparatives', 'conjunctions'],
    targetVocab: ['restaurant-review', 'food-adjectives', 'service-words', 'opinion-phrases'],
    difficulty: 'practice',
  },
  {
    id: 'routines-l05',
    title: 'My Workday',
    blurb: 'Describe a typical work or study day in detail.',
    level: 5, spiralGroup: 'routines', spiralOrder: 4,
    prerequisites: ['routines-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Detailed workday routine. "I start work at 9, check emails, then have a meeting at 10." Use varied time expressions. Push for a full day timeline (morning, afternoon, evening). Aim for 6+ sentences.',
    targetGrammar: ['present-simple', 'prepositions-time', 'connectors', 'adverbs-frequency'],
    targetVocab: ['work-routines', 'office-life', 'time-management', 'daily-tasks'],
    difficulty: 'core',
  },
  {
    id: 'hobbies-l05',
    title: 'My Creative Side',
    blurb: 'Talk about creative hobbies you enjoy.',
    level: 5, spiralGroup: 'hobbies', spiralOrder: 4,
    prerequisites: ['hobbies-l03b'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss creative hobbies. "I paint in my free time." "I\'ve been learning guitar for a year." Use present perfect for duration. Push for depth — why this hobby, how they started, what they\'ve created.',
    targetGrammar: ['present-perfect', 'for-since', 'present-simple', 'conjunctions'],
    targetVocab: ['creative-hobbies', 'arts', 'music', 'crafts', 'self-expression'],
    difficulty: 'practice',
  },
  {
    id: 'time-l05',
    title: 'Time Management',
    blurb: 'Discuss how you manage your time and schedule.',
    level: 5, spiralGroup: 'time', spiralOrder: 3,
    prerequisites: ['time-l01b'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss time management. "I plan my week on Sunday." "I always arrive early." Use frequency and sequencing language. Push for strategies and habits. Ask what they\'d like to improve about their schedule.',
    targetGrammar: ['present-simple', 'adverbs-frequency', 'should-shouldnt', 'connectors'],
    targetVocab: ['time-management', 'planning', 'scheduling', 'productivity'],
    difficulty: 'challenge',
  },
  {
    id: 'health-l05',
    title: 'Staying Fit',
    blurb: 'Discuss your fitness routine and health goals.',
    level: 5, spiralGroup: 'health', spiralOrder: 3,
    prerequisites: ['fitness-l02'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss fitness. "I go to the gym three times a week." "I\'m training for a 5K." Use present simple for habits, present continuous for current training. Push for specific goals and progress updates.',
    targetGrammar: ['present-simple', 'present-continuous', 'adverbs-frequency', 'future-going-to'],
    targetVocab: ['fitness', 'exercise-routine', 'goals', 'progress'],
    difficulty: 'practice',
  },
  {
    id: 'weather-l05',
    title: 'Climate & Seasons',
    blurb: 'Compare the climate in different places you know.',
    level: 5, spiralGroup: 'weather', spiralOrder: 3,
    prerequisites: ['weather-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Compare climates. "My city is colder than yours." "Summer here is humid but winter is dry." Use comparatives and contrast connectors. Push for a detailed comparison with 4-5 points.',
    targetGrammar: ['comparatives', 'superlatives', 'conjunctions', 'present-simple'],
    targetVocab: ['climate', 'weather-comparison', 'seasons-extended', 'geography'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'meeting-l05',
    title: 'Networking',
    blurb: 'Practice meeting new people in professional settings.',
    level: 5, spiralGroup: 'meeting-people', spiralOrder: 3,
    prerequisites: ['meeting-l03'],
    category: 'Social',
    scenarioBrief: 'Professional networking. "What do you do?" "I work in marketing." "Let me give you my card." Introduce yourself, ask about their work, find common ground. Push for a 6-turn exchange. Professional tone.',
    targetGrammar: ['present-simple', 'questions-wh', 'polite-requests', 'discourse-markers'],
    targetVocab: ['networking', 'professional-introductions', 'work-phrases', 'small-talk'],
    difficulty: 'core',
  },
  {
    id: 'relationships-l05',
    title: 'What Makes Relationships Work',
    blurb: 'Discuss what makes good relationships with others.',
    level: 5, spiralGroup: 'relationships', spiralOrder: 2,
    prerequisites: ['relationships-l03'],
    category: 'Social',
    scenarioBrief: 'Discuss healthy relationships. "Trust is the most important thing." "Communication is key." Use abstract nouns and zero conditionals. Push for advice and personal views. Reflective conversation.',
    targetGrammar: ['conditional-zero', 'modals-should', 'superlatives', 'gerunds'],
    targetVocab: ['relationships-extended', 'trust', 'communication', 'values'],
    difficulty: 'core',
  },
  {
    id: 'celebrate-l05',
    title: 'A Memorable Celebration',
    blurb: 'Describe the best celebration you\'ve ever been to.',
    level: 5, spiralGroup: 'celebrations', spiralOrder: 3,
    prerequisites: ['celebrate-l04'],
    category: 'Social',
    scenarioBrief: 'Describe a memorable celebration. Use past tenses. "It was my cousin\'s wedding." "Everyone danced until midnight." Push for vivid details — music, food, decorations, feelings. 5+ sentence story.',
    targetGrammar: ['past-simple', 'past-continuous', 'superlatives', 'adjectives-basic'],
    targetVocab: ['celebrations', 'events', 'emotions', 'sensory-description'],
    difficulty: 'practice',
  },
  {
    id: 'social-l05',
    title: 'Dinner Party Etiquette',
    blurb: 'Talk about social etiquette at dinner parties.',
    level: 5, spiralGroup: 'social-situations', spiralOrder: 2,
    prerequisites: ['social-l03'],
    category: 'Social',
    scenarioBrief: 'Discuss party etiquette. "You should bring a gift." "It\'s polite to compliment the host." Use should/shouldn\'t, it\'s polite to / it\'s rude to. Push for a list of 3-4 rules. Compare cultural differences.',
    targetGrammar: ['modals-should', 'infinitives', 'impersonal-phrases', 'conditional-zero'],
    targetVocab: ['etiquette', 'manners', 'social-rules', 'politeness'],
    difficulty: 'practice',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'city-l05',
    title: 'My Favorite City',
    blurb: 'Describe a city you love and what makes it special.',
    level: 5, spiralGroup: 'city', spiralOrder: 3,
    prerequisites: ['city-l03'],
    category: 'Travel',
    scenarioBrief: 'Describe a favorite city. "Paris is beautiful because of its architecture." Use comparatives and superlatives. Push for 4-5 sentences covering atmosphere, food, people, and attractions.',
    targetGrammar: ['superlatives', 'present-simple', 'conjunctions', 'relative-pronouns'],
    targetVocab: ['city-description', 'attractions', 'atmosphere', 'travel-opinions'],
    difficulty: 'core',
  },
  {
    id: 'travel-l05',
    title: 'Booking a Trip',
    blurb: 'Plan and book a complete trip with flights and hotels.',
    level: 5, spiralGroup: 'travel-planning', spiralOrder: 2,
    prerequisites: ['travel-l03b'],
    category: 'Travel',
    scenarioBrief: 'Plan a trip. You are a travel agent. The user books flights, hotel, and activities. "I\'d like to fly to Tokyo on March 15." "What hotels do you recommend?" Push for a detailed 6-turn booking interaction.',
    targetGrammar: ['future-going-to', 'modals-could', 'polite-requests', 'conditional-first'],
    targetVocab: ['travel-booking', 'flights', 'hotels', 'itinerary'],
    difficulty: 'core',
  },
  {
    id: 'hotel-l05',
    title: 'Hotel Service',
    blurb: 'Request services and handle issues at a hotel.',
    level: 5, spiralGroup: 'hotels', spiralOrder: 3,
    prerequisites: ['hotel-l04'],
    category: 'Travel',
    scenarioBrief: 'Hotel service requests. "Could I get extra towels?" "The WiFi isn\'t working." Use polite requests and present perfect for problems. Push for 4-5 different requests/issues. You are the front desk clerk.',
    targetGrammar: ['modals-could', 'present-perfect', 'polite-requests', 'indirect-questions'],
    targetVocab: ['hotel-services', 'room-amenities', 'complaints', 'requests'],
    difficulty: 'practice',
  },
  {
    id: 'culture-l05',
    title: 'Cultural Comparison',
    blurb: 'Compare customs between your culture and another.',
    level: 5, spiralGroup: 'cultural-experiences', spiralOrder: 2,
    prerequisites: ['culture-l04'],
    category: 'Travel',
    scenarioBrief: 'Compare cultural customs. "In my country, we eat dinner late." "Here, people greet with a kiss." Use present simple for customs. Introduce cultural comparison vocabulary. Push for 4-5 interesting contrasts.',
    targetGrammar: ['present-simple', 'comparatives', 'conjunctions', 'quantifiers'],
    targetVocab: ['culture-comparison', 'customs', 'traditions-extended', 'social-norms'],
    difficulty: 'core',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'cafe-l05',
    title: 'Coffee Connoisseur',
    blurb: 'Order specialty coffee and discuss preferences.',
    level: 5, spiralGroup: 'cafe', spiralOrder: 3,
    prerequisites: ['cafe-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Specialty coffee order. "I\'d like a flat white with oat milk." "What beans do you use?" Use extended ordering vocabulary. Push for detailed preferences. You are a knowledgeable barista.',
    targetGrammar: ['would-like', 'questions-wh', 'present-simple', 'adjectives-basic'],
    targetVocab: ['specialty-coffee', 'coffee-types', 'milk-options', 'taste-adjectives'],
    difficulty: 'practice',
  },
  {
    id: 'shopping-l05',
    title: 'Shopping for Electronics',
    blurb: 'Compare and buy an electronic device.',
    level: 5, spiralGroup: 'shopping', spiralOrder: 3,
    prerequisites: ['shopping-l03'],
    category: 'Daily Life',
    scenarioBrief: 'Electronics shopping. "This phone has more storage." "That one is cheaper." Use comparatives and superlatives. Push for a decision based on comparing 3-4 features. You are a helpful salesperson.',
    targetGrammar: ['comparatives', 'superlatives', 'modals-should', 'relative-pronouns'],
    targetVocab: ['electronics', 'features', 'comparison', 'specifications'],
    difficulty: 'practice',
  },
  {
    id: 'restaurant-l05',
    title: 'Fine Dining Experience',
    blurb: 'Have a formal dinner at an upscale restaurant.',
    level: 5, spiralGroup: 'restaurant', spiralOrder: 4,
    prerequisites: ['restaurant-l04'],
    category: 'Daily Life',
    scenarioBrief: 'Fine dining. Reserve, order multiple courses, ask about wine, give compliments. "The tasting menu looks interesting." "Could you recommend a wine pairing?" Formal register. Push for complete dining interaction.',
    targetGrammar: ['modals-would', 'polite-requests', 'indirect-questions', 'discourse-markers'],
    targetVocab: ['fine-dining', 'wine', 'gourmet-food', 'formal-dining'],
    difficulty: 'challenge',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'jobs-l05',
    title: 'Career Goals',
    blurb: 'Discuss your career aspirations and plans.',
    level: 5, spiralGroup: 'jobs', spiralOrder: 2,
    prerequisites: ['jobs-l03'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss career ambitions. "I want to become a manager in two years." Use future forms — going to, will, want to. Push for a 5-year plan. Ask about skills they need to develop. Supportive and encouraging.',
    targetGrammar: ['future-going-to', 'future-will', 'want-to', 'conditional-first'],
    targetVocab: ['career-ambitions', 'professional-growth', 'skills', 'planning'],
    difficulty: 'core',
  },
  {
    id: 'school-l05',
    title: 'Learning Styles',
    blurb: 'Discuss how you learn best and your study habits.',
    level: 5, spiralGroup: 'school', spiralOrder: 3,
    prerequisites: ['school-l04'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss learning preferences. "I learn best by practicing." "I need to write things down." Use gerunds after prepositions. Push for specific strategies. Ask what they find difficult about learning languages.',
    targetGrammar: ['gerunds', 'need-to', 'present-simple', 'conditional-zero'],
    targetVocab: ['learning-strategies', 'study-habits', 'education-extended', 'language-learning'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'dreams-l05',
    title: 'My Big Dreams',
    blurb: 'Share your biggest dreams and aspirations.',
    level: 5, spiralGroup: 'dreams-goals', spiralOrder: 2,
    prerequisites: ['goals-l04'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss big life dreams. "I dream of starting my own business." "One day I want to travel the world." Use "dream of", "hope to", "wish". Push for reasons and plans. Inspiring and supportive conversation.',
    targetGrammar: ['infinitives', 'future-will', 'conjunctions', 'conditional-first'],
    targetVocab: ['dreams', 'aspirations', 'life-goals', 'ambition'],
    difficulty: 'core',
  },
  {
    id: 'opinion-l05',
    title: 'Agree to Disagree',
    blurb: 'Express and defend your opinion on a topic.',
    level: 5, spiralGroup: 'opinions', spiralOrder: 3,
    prerequisites: ['opinion-l03'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Express opinions on a debatable topic. "In my opinion, remote work is better." Push back gently. "That\'s interesting, but what about..." Use concession phrases — "I see your point, but..." Push for reasoned argument.',
    targetGrammar: ['conjunctions', 'discourse-markers', 'modals-might', 'conditional-first'],
    targetVocab: ['opinion-phrases-extended', 'argumentation', 'concession', 'persuasion'],
    difficulty: 'challenge',
  },
]
