import type { ConversationSeed } from '../types'

/**
 * Level 6 — Confident Talker
 * AI: 5% native, 95% target. Paragraph-length responses, all tenses.
 * 25 seeds: Story (3), Daily (6), Social (3), Travel (3), Commerce (2), Work (4), Ideas (4)
 */

export const SEEDS_L06: ConversationSeed[] = [
  // ── Story & Self ────────────────────────────────────────────────────────
  {
    id: 'story-l06',
    title: 'A Life Lesson',
    blurb: 'Tell a story about something important you learned.',
    level: 6, spiralGroup: 'story', spiralOrder: 3,
    prerequisites: ['mystory-l04'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask about a life lesson learned from experience. "I learned that hard work pays off." Use past tenses for narrative, present for the lesson. Push for a 6+ sentence story with reflection. Empathetic and supportive.',
    targetGrammar: ['past-simple', 'past-continuous', 'reported-speech', 'conditional-zero'],
    targetVocab: ['life-lessons', 'wisdom', 'reflection', 'experience'],
    difficulty: 'core',
  },
  {
    id: 'health-l06',
    title: 'Healthcare Experiences',
    blurb: 'Describe an experience at a doctor or hospital.',
    level: 6, spiralGroup: 'health', spiralOrder: 4,
    prerequisites: ['health-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss healthcare. "I went to the doctor for a checkup." "They prescribed antibiotics." Use past tenses for narrative. Push for details — symptoms, diagnosis, treatment. Compare healthcare systems if relevant.',
    targetGrammar: ['past-simple', 'past-continuous', 'passive-present', 'conjunctions'],
    targetVocab: ['healthcare', 'medical-terms', 'symptoms-extended', 'treatment'],
    difficulty: 'practice',
  },
  {
    id: 'tech-l06',
    title: 'Digital Life',
    blurb: 'Discuss how technology shapes your daily life.',
    level: 6, spiralGroup: 'technology', spiralOrder: 3,
    prerequisites: ['tech-l04'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss tech\'s role in daily life. "I check my phone 50 times a day." "Social media affects my mood." Use present perfect for experiences, present simple for habits. Push for balanced opinion with examples.',
    targetGrammar: ['present-perfect', 'present-simple', 'adverbs-frequency', 'discourse-markers'],
    targetVocab: ['digital-habits', 'social-media', 'screen-time', 'tech-impact'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'money-l06',
    title: 'Financial Planning',
    blurb: 'Discuss saving, investing, and financial goals.',
    level: 6, spiralGroup: 'money', spiralOrder: 3,
    prerequisites: ['money-l04'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss finances. "I save 20% of my income." "I\'m investing in stocks." Use present simple for habits, present continuous for current strategies. Push for specific advice and future plans. Supportive tone.',
    targetGrammar: ['present-simple', 'present-continuous', 'future-going-to', 'should-shouldnt'],
    targetVocab: ['finance', 'saving', 'investing', 'budgeting', 'goals'],
    difficulty: 'core',
  },
  {
    id: 'routines-l06',
    title: 'Productivity Habits',
    blurb: 'Discuss strategies for being productive.',
    level: 6, spiralGroup: 'routines', spiralOrder: 5,
    prerequisites: ['routines-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss productivity. "I use the Pomodoro technique." "I make a to-do list every morning." Use varied tenses. Push for detailed strategies and what works/doesn\'t. Compare past and present habits.',
    targetGrammar: ['present-simple', 'present-perfect', 'comparatives', 'conditional-first'],
    targetVocab: ['productivity', 'habits', 'strategies', 'work-ethic'],
    difficulty: 'practice',
  },
  {
    id: 'hobbies-l06',
    title: 'Collections & Passions',
    blurb: 'Talk about things you collect or are passionate about.',
    level: 6, spiralGroup: 'hobbies', spiralOrder: 5,
    prerequisites: ['hobbies-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss collections or deep passions. "I collect vinyl records." "I\'ve been passionate about photography for years." Use present perfect for duration. Push for depth — why this passion, what makes it special.',
    targetGrammar: ['present-perfect', 'present-perfect-continuous', 'conjunctions', 'relative-pronouns'],
    targetVocab: ['collections', 'passions-extended', 'special-interests', 'commitment'],
    difficulty: 'practice',
  },
  {
    id: 'nature-l06',
    title: 'Environmental Issues',
    blurb: 'Discuss environmental challenges and solutions.',
    level: 6, spiralGroup: 'nature', spiralOrder: 3,
    prerequisites: ['nature-l04'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss environmental issues. "Plastic pollution is a serious problem." Use passive voice for processes — "recycling is done..." Push for opinions and solutions. Balanced, thoughtful conversation.',
    targetGrammar: ['passive-present', 'modals-should', 'conditional-first', 'discourse-markers'],
    targetVocab: ['environment', 'pollution', 'conservation', 'sustainability'],
    difficulty: 'core',
  },
  {
    id: 'food-l06',
    title: 'Food & Culture',
    blurb: 'Discuss how food reflects culture and identity.',
    level: 6, spiralGroup: 'food', spiralOrder: 5,
    prerequisites: ['food-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Explore food-culture connection. "Street food is a big part of Thai culture." Use present simple for cultural facts. Push for detailed connections between food, history, and identity. Compare with user\'s culture.',
    targetGrammar: ['present-simple', 'passive-present', 'relative-pronouns', 'discourse-markers'],
    targetVocab: ['food-culture', 'cuisine', 'street-food', 'food-identity'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'friends-l06',
    title: 'Long-Distance Friendships',
    blurb: 'Discuss how to maintain friendships across distances.',
    level: 6, spiralGroup: 'friendships', spiralOrder: 3,
    prerequisites: ['friends-l04b'],
    category: 'Social',
    scenarioBrief: 'Discuss long-distance friendships. "We video call every week." "I miss my old friends." Use present simple for strategies, present perfect for duration. Push for advice and personal experience.',
    targetGrammar: ['present-simple', 'present-perfect', 'should-shouldnt', 'conditional-first'],
    targetVocab: ['friendship-extended', 'distance', 'communication-habits', 'connection'],
    difficulty: 'practice',
  },
  {
    id: 'communication-l06',
    title: 'The Art of Conversation',
    blurb: 'Discuss what makes a good conversation.',
    level: 6, spiralGroup: 'communication', spiralOrder: 3,
    prerequisites: ['phone-l04'],
    category: 'Social',
    scenarioBrief: 'Discuss conversational skills. "A good listener is rare." "I try to ask open questions." Use discourse markers and sophisticated connectors. Push for observations and tips about effective communication.',
    targetGrammar: ['discourse-markers', 'gerunds', 'conditional-zero', 'relative-pronouns'],
    targetVocab: ['conversation-skills', 'listening', 'communication-extended', 'social-awareness'],
    difficulty: 'core',
  },
  {
    id: 'social-l06',
    title: 'Cultural Misunderstandings',
    blurb: 'Discuss times when cultures misunderstand each other.',
    level: 6, spiralGroup: 'social-situations', spiralOrder: 3,
    prerequisites: ['social-l05'],
    category: 'Social',
    scenarioBrief: 'Discuss cross-cultural misunderstandings. "In my country, it\'s rude to point." Use hedging for cultural sensitivity. Push for real examples. Reflective and educational conversation about cultural awareness.',
    targetGrammar: ['hedging', 'conditional-first', 'discourse-markers', 'conjunctions'],
    targetVocab: ['cultural-awareness', 'misunderstandings', 'sensitivity', 'cross-cultural'],
    difficulty: 'challenge',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'transport-l06',
    title: 'Comparing Transport',
    blurb: 'Compare different ways of getting around.',
    level: 6, spiralGroup: 'transport', spiralOrder: 3,
    prerequisites: ['transport-l04'],
    category: 'Travel',
    scenarioBrief: 'Compare transport options. "Trains are more reliable than buses." "Driving is faster but stressful." Use comparative structures and contrast connectors. Push for a detailed comparison with pros and cons.',
    targetGrammar: ['comparatives', 'superlatives', 'conjunctions', 'discourse-markers'],
    targetVocab: ['transport-comparison', 'commuting', 'public-transport', 'infrastructure'],
    difficulty: 'practice',
  },
  {
    id: 'hotel-l06',
    title: 'Hotel Comparisons',
    blurb: 'Compare different types of accommodation.',
    level: 6, spiralGroup: 'hotels', spiralOrder: 4,
    prerequisites: ['hotel-l05'],
    category: 'Travel',
    scenarioBrief: 'Compare accommodation. "Hostels are cheaper but noisier." "A hotel is more comfortable." Use comparatives and contrast. Push for a detailed comparison of pros and cons. Give recommendations.',
    targetGrammar: ['comparatives', 'superlatives', 'modals-should', 'conditional-first'],
    targetVocab: ['accommodation', 'hostels', 'hotels', 'airbnb', 'comparison'],
    difficulty: 'practice',
  },
  {
    id: 'culture-l06',
    title: 'Festivals Around the World',
    blurb: 'Describe and compare unique festivals.',
    level: 6, spiralGroup: 'cultural-experiences', spiralOrder: 3,
    prerequisites: ['culture-l05'],
    category: 'Travel',
    scenarioBrief: 'Describe festivals. "The lantern festival is spectacular." "Carnival in Rio is the biggest party in the world." Use superlatives and descriptive adjectives. Push for vivid sensory descriptions. 5+ sentences.',
    targetGrammar: ['superlatives', 'present-simple', 'adjectives-basic', 'discourse-markers'],
    targetVocab: ['festivals', 'celebrations', 'cultural-events', 'sensory-language'],
    difficulty: 'core',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'business-l06',
    title: 'Teamwork & Collaboration',
    blurb: 'Discuss working in a team and collaboration.',
    level: 6, spiralGroup: 'business', spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief: 'Discuss teamwork. "Good communication is essential for teamwork." "I prefer working in teams because..." Use gerunds and abstract nouns. Push for personal experiences. Give examples of good and bad teamwork.',
    targetGrammar: ['gerunds', 'modals-should', 'conditional-zero', 'discourse-markers'],
    targetVocab: ['teamwork', 'collaboration', 'leadership', 'workplace-dynamics'],
    difficulty: 'core',
  },
  {
    id: 'skills-l06',
    title: 'Mastering a Skill',
    blurb: 'Discuss the process of mastering a skill.',
    level: 6, spiralGroup: 'skills', spiralOrder: 2,
    prerequisites: ['skills-l04'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss skill mastery. "It takes 10,000 hours to master something." Use zero conditional for general truths, past for personal experience. Push for details about a skill they\'ve worked hard to develop.',
    targetGrammar: ['conditional-zero', 'present-perfect', 'past-simple', 'infinitives'],
    targetVocab: ['skill-mastery', 'practice', 'improvement', 'dedication'],
    difficulty: 'core',
  },
  {
    id: 'school-l06',
    title: 'Education Systems Compared',
    blurb: 'Compare different education systems.',
    level: 6, spiralGroup: 'school', spiralOrder: 4,
    prerequisites: ['school-l05'],
    category: 'Work & Study',
    scenarioBrief: 'Compare education. "In Finland, students have less homework." Use present simple for facts, comparatives for contrasts. Push for a structured comparison of 2 systems. Encourage personal opinion on what works best.',
    targetGrammar: ['comparatives', 'passive-present', 'discourse-markers', 'conjunctions'],
    targetVocab: ['education-systems', 'school-comparison', 'pedagogy', 'learning-environments'],
    difficulty: 'challenge',
  },
  {
    id: 'meetings-l06',
    title: 'Running a Meeting',
    blurb: 'Discuss how to lead and participate in meetings.',
    level: 6, spiralGroup: 'business', spiralOrder: 1,
    prerequisites: ['business-l06'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss meetings. "Agendas should be sent in advance." "I hate meetings that go too long." Use passive for recommendations, should/shouldn\'t. Push for best practices and personal pet peeves.',
    targetGrammar: ['passive-present', 'modals-should', 'discourse-markers', 'relative-pronouns'],
    targetVocab: ['meetings', 'agenda', 'presentation', 'workplace-professional'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'memories-l06',
    title: 'Nostalgia',
    blurb: 'Discuss nostalgic memories and why they matter.',
    level: 6, spiralGroup: 'memories', spiralOrder: 3,
    prerequisites: ['memories-l04b'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore nostalgia. "I miss the music from the 90s." "That smell reminds me of my grandmother\'s kitchen." Use "reminds me of", "I miss". Push for sensory details. Reflective, warm conversation.',
    targetGrammar: ['past-simple', 'used-to', 'remind-of', 'sensory-verbs'],
    targetVocab: ['nostalgia', 'sensory-memories', 'past-comparison', 'emotions-extended'],
    difficulty: 'core',
  },
  {
    id: 'advice-l06',
    title: 'Life Advice',
    blurb: 'Give thoughtful advice on life situations.',
    level: 6, spiralGroup: 'advice', spiralOrder: 2,
    prerequisites: ['advice-l04'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Present complex life situations for advice. "My friend wants to change careers but is scared." Use second conditional for hypotheticals. Push for nuanced advice with reasons. Practice diplomatic language.',
    targetGrammar: ['conditional-second', 'modals-should', 'discourse-markers', 'hedging'],
    targetVocab: ['life-advice', 'diplomacy', 'support', 'options'],
    difficulty: 'practice',
  },
  {
    id: 'ideals-l06',
    title: 'Idioms & Expressions',
    blurb: 'Learn and use common idioms in conversation.',
    level: 6, spiralGroup: 'idioms', spiralOrder: 1,
    prerequisites: [],
    category: 'Expression',
    scenarioBrief: 'Introduce 3-4 common idioms naturally in conversation — "break the ice", "hit the nail on the head", "piece of cake", "cost an arm and a leg". Use each in context, check understanding, encourage re-use.',
    targetGrammar: ['idiomatic-expressions', 'discourse-markers', 'phrasal-verbs'],
    targetVocab: ['idioms', 'expressions', 'colloquial-language', 'phrasal-verbs'],
    difficulty: 'core',
  },
  {
    id: 'goals-l06',
    title: 'Five-Year Plan',
    blurb: 'Describe where you see yourself in five years.',
    level: 6, spiralGroup: 'dreams-goals', spiralOrder: 3,
    prerequisites: ['dreams-l05'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss 5-year plans. "In 5 years, I\'ll have finished my degree." Use future perfect and future continuous. Push for specific, detailed plans across career, personal life, and skills. Encouraging and forward-looking.',
    targetGrammar: ['future-perfect', 'future-continuous', 'conditional-first', 'discourse-markers'],
    targetVocab: ['future-plans', 'long-term-goals', 'milestones', 'ambition-extended'],
    difficulty: 'challenge',
  },
]
