import type { ConversationSeed } from '../types'

/**
 * Level 7 — Confident Speaker
 * AI: 0% native, 100% target. Paragraphs, nuanced expression.
 * 25 seeds: Self (4), Daily (5), Social (3), Travel (4), Commerce (2), Work (2), Ideas (5)
 */

export const SEEDS_L07: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l07',
    title: 'My Life Story',
    blurb: 'Tell the story of your life — past, present, and future.',
    level: 7, spiralGroup: 'identity', spiralOrder: 4,
    prerequisites: ['whoami-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Life story narrative. Where you started, where you are, where you\'re going. Use a mix of past, present, and future tenses. Push for a structured mini-autobiography of 8-10 sentences. Supportive and engaged tone.',
    targetGrammar: ['past-simple', 'present-perfect', 'future-will', 'discourse-markers'],
    targetVocab: ['life-story', 'background', 'achievements', 'identity-complex'],
    difficulty: 'core',
  },
  {
    id: 'family-l07',
    title: 'Generational Differences',
    blurb: 'Compare your generation with your parents\' or grandparents\'.',
    level: 7, spiralGroup: 'family', spiralOrder: 4,
    prerequisites: ['family-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Compare generations. "My grandparents didn\'t have smartphones." "Our generation is more open about mental health." Use used-to, comparatives. Push for 4-5 meaningful contrasts. Reflective conversation.',
    targetGrammar: ['used-to', 'comparatives', 'past-simple', 'discourse-markers'],
    targetVocab: ['generations', 'social-change', 'values', 'technology-comparison'],
    difficulty: 'practice',
  },
  {
    id: 'home-l07',
    title: 'Home & Memories',
    blurb: 'Describe the home(s) you\'ve lived in and what they meant.',
    level: 7, spiralGroup: 'home', spiralOrder: 4,
    prerequisites: ['home-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Reflect on past homes. "My childhood home had a big garden." Use past tenses. Push for emotional connection — what made each home special. Compare different homes. Nostalgic and personal conversation.',
    targetGrammar: ['past-simple', 'used-to', 'past-perfect', 'adjectives-extended'],
    targetVocab: ['home-memories', 'childhood-home', 'neighborhood', 'belonging'],
    difficulty: 'practice',
  },
  {
    id: 'feelings-l07',
    title: 'Emotional Intelligence',
    blurb: 'Discuss understanding and managing emotions.',
    level: 7, spiralGroup: 'feelings', spiralOrder: 4,
    prerequisites: ['feelings-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss emotional intelligence. "I try to understand why I feel angry." "Empathy is the ability to feel what others feel." Use abstract nouns and complex sentences. Push for personal growth insights.',
    targetGrammar: ['gerunds', 'nominalization', 'discourse-markers', 'passive-present'],
    targetVocab: ['emotional-intelligence', 'empathy', 'self-awareness', 'growth-mindset'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'food-l07',
    title: 'Street Food Tour',
    blurb: 'Describe a street food experience and why it\'s special.',
    level: 7, spiralGroup: 'food', spiralOrder: 6,
    prerequisites: ['food-l06'],
    category: 'Daily Life',
    scenarioBrief: 'Describe a street food experience vividly. "The sizzling sound, the smell of spices..." Use sensory language and present tenses for immediacy. Push for a rich, immersive description. Make them hungry!',
    targetGrammar: ['present-simple', 'present-continuous', 'sensory-verbs', 'adjectives-sensory'],
    targetVocab: ['street-food', 'sensory-description', 'food-culture', 'cooking-techniques'],
    difficulty: 'practice',
  },
  {
    id: 'routines-l07',
    title: 'Work-Life Balance',
    blurb: 'Discuss how you balance work and personal life.',
    level: 7, spiralGroup: 'routines', spiralOrder: 6,
    prerequisites: ['routines-l06'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss work-life balance. "I try to leave work at 6 every day." "Weekends are for family." Use should/shouldn\'t for advice. Push for strategies and what they struggle with. Relatable conversation.',
    targetGrammar: ['modals-should', 'conditional-first', 'discourse-markers', 'comparatives'],
    targetVocab: ['balance', 'work-life', 'priorities', 'stress-management', 'wellbeing'],
    difficulty: 'core',
  },
  {
    id: 'hobbies-l07',
    title: 'The Value of Hobbies',
    blurb: 'Discuss why hobbies matter for wellbeing.',
    level: 7, spiralGroup: 'hobbies', spiralOrder: 6,
    prerequisites: ['hobbies-l06'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss the importance of hobbies. "Hobbies help me disconnect from work." Use gerunds as subjects. Push for deeper reflections on why hobbies enrich life. Compare past and present hobbies.',
    targetGrammar: ['gerunds', 'conditional-zero', 'discourse-markers', 'present-simple'],
    targetVocab: ['wellbeing', 'hobbies-value', 'mental-health', 'leisure-complex'],
    difficulty: 'practice',
  },
  {
    id: 'health-l07',
    title: 'Mental Health Awareness',
    blurb: 'Discuss mental health and wellbeing openly.',
    level: 7, spiralGroup: 'health', spiralOrder: 5,
    prerequisites: ['health-l06'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss mental health sensitively. "It\'s important to talk about mental health." "I practice mindfulness to stay grounded." Use hedging for sensitivity. Push for awareness and self-care strategies. Supportive.',
    targetGrammar: ['hedging', 'nominalization', 'modals-should', 'conditional-first'],
    targetVocab: ['mental-health', 'mindfulness', 'self-care', 'therapy', 'wellbeing-extended'],
    difficulty: 'core',
  },
  {
    id: 'tech-l07',
    title: 'AI & The Future',
    blurb: 'Discuss AI and how it might change our lives.',
    level: 7, spiralGroup: 'technology', spiralOrder: 4,
    prerequisites: ['tech-l06'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss AI and automation. "AI will change how we work." "I worry about job automation." Use future tenses and conditionals. Push for balanced opinion with examples. Engage with their hopes and concerns.',
    targetGrammar: ['future-will', 'future-perfect', 'conditional-first', 'modal-speculation'],
    targetVocab: ['AI', 'automation', 'technology-impact', 'future-predictions'],
    difficulty: 'challenge',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'meeting-l07',
    title: 'First Impressions',
    blurb: 'Discuss how first impressions shape relationships.',
    level: 7, spiralGroup: 'meeting-people', spiralOrder: 4,
    prerequisites: ['meeting-l05'],
    category: 'Social',
    scenarioBrief: 'Discuss first impressions. "You never get a second chance to make a first impression." Use present perfect for experiences. Push for personal stories and reflections. What do they notice about new people?',
    targetGrammar: ['present-perfect', 'conditional-zero', 'discourse-markers', 'hedging'],
    targetVocab: ['first-impressions', 'judgment', 'body-language', 'social-perception'],
    difficulty: 'core',
  },
  {
    id: 'relationships-l07',
    title: 'Love & Relationships',
    blurb: 'Discuss romantic relationships and what makes them work.',
    level: 7, spiralGroup: 'relationships', spiralOrder: 3,
    prerequisites: ['relationships-l05'],
    category: 'Social',
    scenarioBrief: 'Discuss romantic relationships. "Communication is the foundation of any relationship." Use abstract vocabulary and second conditionals for hypotheticals. Push for thoughtful opinions. Respectful and mature.',
    targetGrammar: ['conditional-second', 'nominalization', 'discourse-markers', 'subjunctive'],
    targetVocab: ['relationships-complex', 'love', 'commitment', 'partnership'],
    difficulty: 'challenge',
  },
  {
    id: 'celebrate-l07',
    title: 'Wedding Traditions',
    blurb: 'Compare wedding traditions across cultures.',
    level: 7, spiralGroup: 'celebrations', spiralOrder: 4,
    prerequisites: ['celebrate-l05'],
    category: 'Social',
    scenarioBrief: 'Compare weddings. "In my culture, weddings last three days." Use present simple for traditions, comparatives for contrasts. Push for vivid descriptions. Help them reflect on the meaning behind traditions.',
    targetGrammar: ['present-simple', 'passive-present', 'discourse-markers', 'comparatives'],
    targetVocab: ['weddings', 'ceremonies', 'traditions-extended', 'cultural-values'],
    difficulty: 'practice',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'travel-l07',
    title: 'Solo Travel vs Group Travel',
    blurb: 'Compare traveling alone versus with others.',
    level: 7, spiralGroup: 'travel-planning', spiralOrder: 3,
    prerequisites: ['travel-l05'],
    category: 'Travel',
    scenarioBrief: 'Compare solo vs group travel. "Solo travel is more liberating." "Group travel is safer." Use comparative structures and hedging. Push for detailed pros and cons. Ask about their preference with examples.',
    targetGrammar: ['comparatives', 'hedging', 'conditional-second', 'discourse-markers'],
    targetVocab: ['travel-styles', 'solo-travel', 'group-travel', 'adventure'],
    difficulty: 'core',
  },
  {
    id: 'nature-l07',
    title: 'Adventure Travel',
    blurb: 'Describe an adventurous trip or dream adventure.',
    level: 7, spiralGroup: 'nature', spiralOrder: 4,
    prerequisites: ['nature-l06'],
    category: 'Travel',
    scenarioBrief: 'Describe an adventure. "I trekked through the jungle for three days." Use narrative past tenses. Push for vivid sensory details and emotional journey. Inspire with your own made-up adventure story.',
    targetGrammar: ['past-simple', 'past-continuous', 'past-perfect', 'adjectives-extended'],
    targetVocab: ['adventure', 'trekking', 'wilderness', 'challenge', 'nature-complex'],
    difficulty: 'core',
  },
  {
    id: 'culture-l07',
    title: 'Culture Shock',
    blurb: 'Discuss experiences of culture shock and adaptation.',
    level: 7, spiralGroup: 'cultural-experiences', spiralOrder: 4,
    prerequisites: ['culture-l06'],
    category: 'Travel',
    scenarioBrief: 'Discuss culture shock. "At first, I was confused by the customs." "After a month, I started to understand." Use narrative past with time expressions. Push for specific examples and the adaptation journey.',
    targetGrammar: ['past-simple', 'past-continuous', 'used-to', 'discourse-markers'],
    targetVocab: ['culture-shock', 'adaptation', 'immersion', 'cultural-differences'],
    difficulty: 'practice',
  },
  {
    id: 'city-l07',
    title: 'Urban vs Rural Life',
    blurb: 'Compare living in the city versus the countryside.',
    level: 7, spiralGroup: 'city', spiralOrder: 4,
    prerequisites: ['city-l05'],
    category: 'Travel',
    scenarioBrief: 'Compare city vs rural life. "The city is more convenient but louder." "Countryside living is peaceful but isolated." Use comparatives and contrast connectors. Push for a detailed balanced comparison.',
    targetGrammar: ['comparatives', 'conjunctions', 'discourse-markers', 'conditional-second'],
    targetVocab: ['urban-life', 'rural-life', 'lifestyle-comparison', 'community'],
    difficulty: 'practice',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'restaurant-l07',
    title: 'Restaurant Critique',
    blurb: 'Give a detailed restaurant critique.',
    level: 7, spiralGroup: 'restaurant', spiralOrder: 5,
    prerequisites: ['restaurant-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Review a restaurant in detail. "The ambiance was elegant but the service was slow." Use varied adjectives and discourse markers. Push for structured critique covering all aspects. Sound like a food critic.',
    targetGrammar: ['past-simple', 'superlatives', 'discourse-markers', 'conjunctions'],
    targetVocab: ['restaurant-critique', 'ambiance', 'service', 'presentation', 'value'],
    difficulty: 'challenge',
  },
  {
    id: 'shopping-l07',
    title: 'Online vs In-Store Shopping',
    blurb: 'Compare online shopping with in-store experiences.',
    level: 7, spiralGroup: 'shopping', spiralOrder: 4,
    prerequisites: ['shopping-l05'],
    category: 'Daily Life',
    scenarioBrief: 'Compare shopping methods. "Online shopping is convenient but you can\'t try things." Use comparative structures. Push for a balanced argument with personal examples. Discuss future of retail.',
    targetGrammar: ['comparatives', 'discourse-markers', 'conditional-second', 'present-simple'],
    targetVocab: ['online-shopping', 'retail', 'ecommerce', 'consumer-habits'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'jobs-l07',
    title: 'Changing Careers',
    blurb: 'Discuss career changes and reinvention.',
    level: 7, spiralGroup: 'jobs', spiralOrder: 3,
    prerequisites: ['jobs-l05'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss career changes. "I\'m thinking about a career change." Use second conditional for hypotheticals. Push for reasons, fears, and plans. Supportive conversation about professional growth and courage.',
    targetGrammar: ['conditional-second', 'present-continuous', 'future-going-to', 'discourse-markers'],
    targetVocab: ['career-change', 'reinvention', 'professional-growth', 'risk-taking'],
    difficulty: 'core',
  },
  {
    id: 'skills-l07',
    title: 'Teaching Others',
    blurb: 'Discuss how you would teach a skill to someone else.',
    level: 7, spiralGroup: 'skills', spiralOrder: 3,
    prerequisites: ['skills-l06'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss teaching. "If I were teaching someone to cook, I\'d start with basics." Use second conditional for approach. Push for a structured teaching philosophy. What makes a good teacher?',
    targetGrammar: ['conditional-second', 'imperatives', 'discourse-markers', 'gerunds'],
    targetVocab: ['teaching', 'mentoring', 'pedagogy', 'patience', 'guidance'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'hypothetical-l07',
    title: 'What If...?',
    blurb: 'Explore hypothetical scenarios and their outcomes.',
    level: 7, spiralGroup: 'hypotheticals', spiralOrder: 2,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore hypotheticals. "If you could live anywhere in the world, where would it be?" Use second conditional consistently. Push for detailed answers with reasons. Keep it imaginative and fun.',
    targetGrammar: ['conditional-second', 'modals-would', 'discourse-markers', 'hedging'],
    targetVocab: ['hypotheticals', 'imagination', 'possibilities', 'preferences-extended'],
    difficulty: 'core',
  },
  {
    id: 'storytelling-l07',
    title: 'A Suspenseful Story',
    blurb: 'Tell a story with suspense and vivid detail.',
    level: 7, spiralGroup: 'storytelling', spiralOrder: 2,
    prerequisites: ['story-l06'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask for a suspenseful story. Push for narrative technique — build tension, use dialogue, vary sentence length. Coach them on dramatic language. Have them tell a 2-minute story. Engaged listener.',
    targetGrammar: ['past-simple', 'past-continuous', 'past-perfect', 'direct-speech'],
    targetVocab: ['suspense', 'narrative-technique', 'dramatic-language', 'story-structure'],
    difficulty: 'core',
  },
  {
    id: 'opinion-l07',
    title: 'Debate: Nature vs Nurture',
    blurb: 'Debate whether personality is born or made.',
    level: 7, spiralGroup: 'opinions', spiralOrder: 4,
    prerequisites: ['opinion-l05'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Light debate on nature vs nurture. "I believe personality is mostly shaped by environment." Use discourse markers for argumentation. Push for counter-arguments and concessions. Respectful debate tone.',
    targetGrammar: ['discourse-markers', 'hedging', 'reported-speech', 'passive-present'],
    targetVocab: ['debate', 'nature-nurture', 'personality', 'argumentation-extended'],
    difficulty: 'challenge',
  },
  {
    id: 'culture-l07deep',
    title: 'Cultural Values',
    blurb: 'Compare deep cultural values and beliefs.',
    level: 7, spiralGroup: 'cultural-comparison', spiralOrder: 2,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore deep cultural values. "In my culture, family comes first." "Individualism is valued in Western societies." Use abstract vocabulary and hedging. Push for thoughtful comparisons. Respectful and curious.',
    targetGrammar: ['present-simple', 'hedging', 'discourse-markers', 'passive-present'],
    targetVocab: ['cultural-values', 'beliefs', 'society', 'norms', 'philosophy-basic'],
    difficulty: 'core',
  },
  {
    id: 'register-l07',
    title: 'Formal vs Casual',
    blurb: 'Practice switching between formal and casual language.',
    level: 7, spiralGroup: 'register', spiralOrder: 1,
    prerequisites: [],
    category: 'Expression',
    scenarioBrief: 'Practice register changes. First, have a casual chat with a friend. Then, discuss the same topic formally with a boss. Help them notice differences in vocabulary, grammar, and tone. Coach on appropriateness.',
    targetGrammar: ['formal-informal-shift', 'passive-formality', 'discourse-markers', 'modal-politeness'],
    targetVocab: ['register', 'formality', 'politeness-extended', 'professional-language'],
    difficulty: 'core',
  },
]
