import type { ConversationSeed } from '../types'

/**
 * Level 8 — Advanced Talker
 * AI: 0% native, 100% target. Complex sentences, abstract discussion.
 * 25 seeds: Story (3), Daily (4), Social (3), Travel (2), Work (3), Ideas (6), Expression (4)
 */

export const SEEDS_L08: ConversationSeed[] = [
  // ── Story & Self ────────────────────────────────────────────────────────
  {
    id: 'story-l08',
    title: 'A Turning Point',
    blurb: 'Describe a moment that changed your life.',
    level: 8, spiralGroup: 'story', spiralOrder: 4,
    prerequisites: ['story-l06'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Ask about a life-changing moment. "Everything changed when I moved abroad." Use past perfect for background, past simple for events. Push for emotional depth and reflection. 8+ sentence narrative.',
    targetGrammar: ['past-perfect', 'past-simple', 'past-continuous', 'discourse-markers', 'narrative-tenses'],
    targetVocab: ['life-changing', 'transformation', 'reflection-complex', 'emotional-depth'],
    difficulty: 'core',
  },
  {
    id: 'health-l08',
    title: 'Alternative Medicine',
    blurb: 'Discuss traditional vs modern approaches to health.',
    level: 8, spiralGroup: 'health', spiralOrder: 6,
    prerequisites: ['health-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Compare traditional and modern medicine. "Acupuncture has been used for thousands of years." Use passive and present perfect. Push for balanced opinion. What role should traditional medicine play today?',
    targetGrammar: ['passive-present', 'present-perfect', 'discourse-markers', 'hedging'],
    targetVocab: ['medicine', 'alternative-health', 'traditions', 'science-vs-tradition'],
    difficulty: 'practice',
  },
  {
    id: 'tech-l08',
    title: 'Social Media & Society',
    blurb: 'Discuss social media\'s impact on society.',
    level: 8, spiralGroup: 'technology', spiralOrder: 5,
    prerequisites: ['tech-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss social media impact. "Social media has changed how we connect." Use present perfect for changes. Push for a balanced argument. Discuss both positive and negative effects. Thoughtful debate.',
    targetGrammar: ['present-perfect', 'passive-present', 'discourse-markers', 'reported-speech'],
    targetVocab: ['social-media-impact', 'mental-health', 'privacy', 'misinformation'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'money-l08',
    title: 'The Sharing Economy',
    blurb: 'Discuss services like Uber, Airbnb, and the gig economy.',
    level: 8, spiralGroup: 'money', spiralOrder: 4,
    prerequisites: ['money-l06'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss the sharing economy. "Uber has changed transportation forever." Use present perfect for changes, passive for processes. Push for balanced opinion with examples. Discuss pros and cons of gig work.',
    targetGrammar: ['present-perfect', 'passive-present', 'conditional-second', 'discourse-markers'],
    targetVocab: ['sharing-economy', 'gig-work', 'Uber', 'Airbnb', 'economic-change'],
    difficulty: 'practice',
  },
  {
    id: 'food-l08',
    title: 'Vegetarianism & Ethics',
    blurb: 'Discuss ethical eating and dietary choices.',
    level: 8, spiralGroup: 'food', spiralOrder: 7,
    prerequisites: ['food-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss ethical eating. "More people are choosing plant-based diets." Use present tenses. Push for a nuanced discussion on ethics, environment, health. Respect different viewpoints. Thoughtful exchange.',
    targetGrammar: ['present-continuous', 'conditional-second', 'discourse-markers', 'hedging'],
    targetVocab: ['diet-extended', 'ethics', 'vegetarianism', 'sustainability-extended', 'food-ethics'],
    difficulty: 'practice',
  },
  {
    id: 'routines-l08',
    title: 'Habits & Change',
    blurb: 'Discuss how to build good habits and break bad ones.',
    level: 8, spiralGroup: 'routines', spiralOrder: 7,
    prerequisites: ['routines-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss habit formation. "It takes 21 days to form a habit." Use zero and first conditionals. Push for personal strategies and experiences. What habits have they successfully built or broken? Supportive.',
    targetGrammar: ['conditional-zero', 'conditional-first', 'gerunds', 'discourse-markers'],
    targetVocab: ['habits', 'behavior-change', 'discipline', 'self-improvement-extended'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'friends-l08',
    title: 'Social Circles',
    blurb: 'Discuss how social circles change throughout life.',
    level: 8, spiralGroup: 'friendships', spiralOrder: 4,
    prerequisites: ['friends-l06'],
    category: 'Social',
    scenarioBrief: 'Discuss changing friendships. "My social circle changed after university." Use past tenses. Push for reflections on how friendships evolve. What makes friendships last? Honest and warm conversation.',
    targetGrammar: ['past-simple', 'present-perfect', 'used-to', 'discourse-markers'],
    targetVocab: ['social-circles', 'friendship-evolution', 'connection', 'community'],
    difficulty: 'core',
  },
  {
    id: 'relationships-l08',
    title: 'Family Dynamics',
    blurb: 'Discuss family relationships and dynamics.',
    level: 8, spiralGroup: 'relationships', spiralOrder: 4,
    prerequisites: ['relationships-l07'],
    category: 'Social',
    scenarioBrief: 'Discuss family dynamics. "My relationship with my parents has changed over time." Use present perfect for changes. Push for honest reflections. Respectful conversation about family complexities.',
    targetGrammar: ['present-perfect', 'past-simple', 'conditional-second', 'hedging'],
    targetVocab: ['family-dynamics', 'sibling-relationships', 'parent-child', 'generational'],
    difficulty: 'practice',
  },
  {
    id: 'communication-l08',
    title: 'Non-Verbal Communication',
    blurb: 'Discuss body language and non-verbal cues.',
    level: 8, spiralGroup: 'communication', spiralOrder: 4,
    prerequisites: ['communication-l06'],
    category: 'Social',
    scenarioBrief: 'Discuss body language. "Crossed arms can signal defensiveness." Use present simple for general truths. Push for cross-cultural comparison of gestures. Fun and informative discussion.',
    targetGrammar: ['present-simple', 'modals-can', 'conditional-zero', 'discourse-markers'],
    targetVocab: ['body-language', 'gestures', 'non-verbal', 'cultural-signals'],
    difficulty: 'practice',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'transport-l08',
    title: 'Future of Transport',
    blurb: 'Discuss how transportation will change in the future.',
    level: 8, spiralGroup: 'transport', spiralOrder: 4,
    prerequisites: ['transport-l06'],
    category: 'Travel',
    scenarioBrief: 'Discuss future transport. "Electric cars will dominate the roads." Use future tenses and speculation modals. Push for predictions. Discuss flying cars, hyperloop, space travel. Imaginative and informed.',
    targetGrammar: ['future-will', 'future-perfect', 'modal-speculation', 'conditional-first'],
    targetVocab: ['future-transport', 'electric-vehicles', 'innovation', 'smart-cities'],
    difficulty: 'core',
  },
  {
    id: 'hotel-l08',
    title: 'The Hospitality Industry',
    blurb: 'Discuss trends and changes in hospitality.',
    level: 8, spiralGroup: 'hotels', spiralOrder: 5,
    prerequisites: ['hotel-l06'],
    category: 'Travel',
    scenarioBrief: 'Discuss hospitality trends. "Hotels are becoming more eco-friendly." Use present continuous for trends, present perfect for recent changes. Push for opinions on what makes great hospitality. Professional perspective.',
    targetGrammar: ['present-continuous', 'present-perfect', 'passive-present', 'modals-should'],
    targetVocab: ['hospitality', 'eco-tourism', 'travel-trends', 'customer-service'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'business-l08',
    title: 'Entrepreneurship',
    blurb: 'Discuss starting a business and being an entrepreneur.',
    level: 8, spiralGroup: 'business', spiralOrder: 2,
    prerequisites: ['meetings-l06'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss entrepreneurship. "If I started a business, I\'d focus on sustainability." Use second conditional. Push for ideas, challenges, and motivations. Discuss qualities of successful entrepreneurs.',
    targetGrammar: ['conditional-second', 'discourse-markers', 'infinitives', 'modals-would'],
    targetVocab: ['entrepreneurship', 'startup', 'innovation', 'risk-management', 'vision'],
    difficulty: 'core',
  },
  {
    id: 'school-l08',
    title: 'The Purpose of Education',
    blurb: 'Discuss what education should really be about.',
    level: 8, spiralGroup: 'school', spiralOrder: 5,
    prerequisites: ['school-l06'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss education philosophy. "Education should teach critical thinking, not facts." Use modal verbs for opinions. Push for a nuanced argument. Compare traditional vs progressive education. Deep discussion.',
    targetGrammar: ['modals-should', 'conditional-second', 'passive-present', 'nominalization'],
    targetVocab: ['education-philosophy', 'critical-thinking', 'pedagogy-extended', 'learning-goals'],
    difficulty: 'challenge',
  },
  {
    id: 'academic-l08',
    title: 'Research & Discovery',
    blurb: 'Discuss scientific research and its impact on society.',
    level: 8, spiralGroup: 'academic', spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief: 'Discuss scientific research. "Recent studies have shown that..." Use passive for scientific language, present perfect for recent findings. Push for opinions on research ethics and funding priorities.',
    targetGrammar: ['passive-present', 'passive-past', 'present-perfect', 'discourse-markers'],
    targetVocab: ['research', 'science', 'discovery', 'methodology', 'ethics'],
    difficulty: 'core',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'memories-l08',
    title: 'Childhood Revisited',
    blurb: 'Reflect on childhood memories and their meaning.',
    level: 8, spiralGroup: 'memories', spiralOrder: 4,
    prerequisites: ['memories-l06'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Reflect on childhood. "I used to think the world was simple." Use used-to and would for past habits. Push for meaningful reflection on how childhood shaped them. Warm and nostalgic conversation.',
    targetGrammar: ['used-to', 'would-for-habits', 'past-simple', 'discourse-markers'],
    targetVocab: ['childhood-extended', 'innocence', 'growth', 'perspective'],
    difficulty: 'core',
  },
  {
    id: 'hypothetical-l08',
    title: 'Parallel Universes',
    blurb: 'Imagine alternative versions of your life.',
    level: 8, spiralGroup: 'hypotheticals', spiralOrder: 3,
    prerequisites: ['hypothetical-l07'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore parallel lives. "If I had studied art instead of business, my life would be different." Use third conditional. Push for detailed alternate scenarios. Creative, philosophical, and fun.',
    targetGrammar: ['conditional-third', 'modals-would-have', 'discourse-markers', 'hedging'],
    targetVocab: ['parallel-lives', 'regret', 'alternative-paths', 'imagination-extended'],
    difficulty: 'practice',
  },
  {
    id: 'storytelling-l08',
    title: 'Urban Legends',
    blurb: 'Tell a spooky or mysterious story from your culture.',
    level: 8, spiralGroup: 'storytelling', spiralOrder: 3,
    prerequisites: ['storytelling-l07'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Tell a spooky story. Use narrative techniques — building atmosphere, suspense, surprise ending. Coach on dramatic pacing and descriptive language. Share your own urban legend too. Fun and engaging.',
    targetGrammar: ['past-simple', 'past-continuous', 'reported-speech', 'discourse-markers'],
    targetVocab: ['storytelling-extended', 'suspense', 'atmosphere', 'folklore'],
    difficulty: 'practice',
  },
  {
    id: 'goals-l08',
    title: 'Bucket List',
    blurb: 'Discuss things you want to do before you die.',
    level: 8, spiralGroup: 'dreams-goals', spiralOrder: 4,
    prerequisites: ['goals-l06'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss bucket list items. "Before I die, I want to see the Northern Lights." Use future forms and "want to". Push for reasons and emotional significance. Share your own bucket list items. Inspiring conversation.',
    targetGrammar: ['future-will', 'want-to', 'conditional-second', 'discourse-markers'],
    targetVocab: ['bucket-list', 'dreams-extended', 'adventure-extended', 'life-goals'],
    difficulty: 'practice',
  },
  {
    id: 'advice-l08',
    title: 'Peer Counseling',
    blurb: 'Give thoughtful advice on complex personal issues.',
    level: 8, spiralGroup: 'advice', spiralOrder: 3,
    prerequisites: ['advice-l06'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Present complex personal dilemmas. "My friend is in a toxic relationship. What should I do?" Use second conditional and hedging. Push for nuanced, diplomatic advice. Consider multiple perspectives.',
    targetGrammar: ['conditional-second', 'modals-should', 'hedging', 'discourse-markers'],
    targetVocab: ['counseling', 'relationships-extended', 'wisdom', 'support-extended'],
    difficulty: 'challenge',
  },
  {
    id: 'culture-l08',
    title: 'Society & Issues',
    blurb: 'Discuss societal issues and potential solutions.',
    level: 8, spiralGroup: 'society', spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss societal issues. "Inequality is a growing concern in many countries." Use passive for objectivity, hedging for sensitivity. Push for balanced argument with evidence. Respectful and thoughtful debate.',
    targetGrammar: ['passive-present', 'hedging', 'discourse-markers', 'nominalization'],
    targetVocab: ['society-extended', 'inequality', 'justice', 'policy', 'civics'],
    difficulty: 'core',
  },

  // ── Expression ─────────────────────────────────────────────────────────
  {
    id: 'idioms-l08',
    title: 'Idioms in Depth',
    blurb: 'Master idioms and use them naturally in context.',
    level: 8, spiralGroup: 'idioms', spiralOrder: 2,
    prerequisites: ['ideals-l06'],
    category: 'Expression',
    scenarioBrief: 'Introduce 5-6 higher-level idioms — "bite the bullet", "hit the sack", "once in a blue moon", "piece of cake", "break the ice", "cost an arm and a leg". Use each in natural dialogue. Encourage re-use.',
    targetGrammar: ['idiomatic-expressions', 'phrasal-verbs', 'discourse-markers', 'colloquial-language'],
    targetVocab: ['idioms-extended', 'expressions-extended', 'colloquial', 'figurative'],
    difficulty: 'core',
  },
  {
    id: 'register-l08',
    title: 'Politeness Across Cultures',
    blurb: 'Discuss how politeness differs across cultures.',
    level: 8, spiralGroup: 'register', spiralOrder: 2,
    prerequisites: ['register-l07'],
    category: 'Expression',
    scenarioBrief: 'Explore cultural politeness. "In Japan, indirect refusal is polite." "In my culture, being direct is valued." Use comparative structures. Push for cross-cultural awareness. Educational and eye-opening.',
    targetGrammar: ['discourse-markers', 'hedging', 'passive-present', 'comparatives'],
    targetVocab: ['politeness-extended', 'cultural-norms', 'etiquette-extended', 'cross-cultural'],
    difficulty: 'practice',
  },
  {
    id: 'humor-l08',
    title: 'Understanding Humor',
    blurb: 'Discuss different types of humor and comedy styles.',
    level: 8, spiralGroup: 'humor', spiralOrder: 1,
    prerequisites: [],
    category: 'Expression',
    scenarioBrief: 'Explore humor types. "British humor is often sarcastic." "I love witty wordplay." Use present simple for generalizations. Push for personal preferences. Share a joke in the target language. Fun and engaging.',
    targetGrammar: ['present-simple', 'discourse-markers', 'comparatives', 'hedging'],
    targetVocab: ['humor-extended', 'comedy', 'sarcasm', 'wit', 'wordplay'],
    difficulty: 'core',
  },
  {
    id: 'idioms-l08b',
    title: 'Proverbs & Sayings',
    blurb: 'Learn common proverbs and their cultural meanings.',
    level: 8, spiralGroup: 'idioms', spiralOrder: 2,
    prerequisites: ['idioms-l08'],
    category: 'Expression',
    scenarioBrief: 'Introduce 4-5 common proverbs — "actions speak louder than words", "the early bird catches the worm". Discuss their meanings and when to use them. Ask the user to share proverbs from their culture.',
    targetGrammar: ['present-simple', 'conditional-zero', 'discourse-markers', 'relative-pronouns'],
    targetVocab: ['proverbs', 'sayings', 'cultural-wisdom', 'figurative-language'],
    difficulty: 'practice',
  },
]
