import type { ConversationSeed } from '../types'

/**
 * Level 9 — Almost Native
 * AI: 0% native, 100% target. Nuanced, abstract, sophisticated topics.
 * 25 seeds: Self (3), Daily (3), Social (2), Travel (2), Commerce (2), Work (2), Ideas (6), Culture (3), Expression (2)
 */

export const SEEDS_L09: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l09',
    title: 'My Philosophy of Life',
    blurb: 'Share your personal philosophy and what guides you.',
    level: 9, spiralGroup: 'identity', spiralOrder: 5,
    prerequisites: ['whoami-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss life philosophy. "I believe in living authentically." "My guiding principle is kindness." Use abstract vocabulary and complex structures. Push for deep reflection. Philosophical yet personal conversation.',
    targetGrammar: ['nominalization', 'hedging', 'discourse-markers', 'passive-present'],
    targetVocab: ['philosophy', 'values', 'life-principles', 'meaning', 'authenticity'],
    difficulty: 'core',
  },
  {
    id: 'home-l09',
    title: 'Home & Belonging',
    blurb: 'Discuss what "home" really means to you.',
    level: 9, spiralGroup: 'home', spiralOrder: 5,
    prerequisites: ['home-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Explore the concept of home. "Home isn\'t a place, it\'s a feeling." Use abstract nouns and metaphorical language. Push for emotional depth. Where do they feel they truly belong? Reflective conversation.',
    targetGrammar: ['nominalization', 'hedging', 'discourse-markers', 'figurative-language'],
    targetVocab: ['belonging', 'identity-home', 'roots', 'place-attachment', 'metaphor'],
    difficulty: 'core',
  },
  {
    id: 'feelings-l09',
    title: 'Emotional Resilience',
    blurb: 'Discuss building emotional strength and resilience.',
    level: 9, spiralGroup: 'feelings', spiralOrder: 5,
    prerequisites: ['feelings-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss resilience. "Resilience isn\'t about avoiding pain, but growing through it." Use sophisticated vocabulary and personal reflection. Push for strategies and insights. Supportive yet challenging conversation.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'hedging'],
    targetVocab: ['resilience', 'strength', 'adversity', 'growth-mindset-extended', 'coping-complex'],
    difficulty: 'practice',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'food-l09',
    title: 'Gastronomy & Art',
    blurb: 'Discuss cooking as an art form and cultural expression.',
    level: 9, spiralGroup: 'food', spiralOrder: 8,
    prerequisites: ['food-l08'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss gastronomy as art. "A great dish tells a story." Use sophisticated sensory language and metaphor. Push for a detailed description of a memorable meal. Think like a food critic. Evocative language.',
    targetGrammar: ['superlatives', 'figurative-language', 'discourse-markers', 'nominalization'],
    targetVocab: ['gastronomy', 'culinary-art', 'flavors-extended', 'presentation', 'food-criticism'],
    difficulty: 'practice',
  },
  {
    id: 'tech-l09',
    title: 'Privacy in the Digital Age',
    blurb: 'Discuss privacy concerns in the modern digital world.',
    level: 9, spiralGroup: 'technology', spiralOrder: 6,
    prerequisites: ['tech-l08'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss digital privacy. "Our data is being collected constantly." Use passive voice extensively. Push for opinions on surveillance, data rights, and personal responsibility. Informed discussion.',
    targetGrammar: ['passive-present', 'passive-perfect', 'hedging', 'discourse-markers'],
    targetVocab: ['privacy', 'surveillance', 'data-rights', 'encryption', 'digital-freedom'],
    difficulty: 'core',
  },
  {
    id: 'health-l09',
    title: 'Longevity & Wellness',
    blurb: 'Discuss the science of living a long, healthy life.',
    level: 9, spiralGroup: 'health', spiralOrder: 7,
    prerequisites: ['health-l08'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss longevity. "Blue zones show us how to live longer." Use passive and reported speech for scientific findings. Push for opinions on lifestyle choices. What would they do to live to 100?',
    targetGrammar: ['passive-present', 'reported-speech', 'discourse-markers', 'conditional-second'],
    targetVocab: ['longevity', 'wellness-complex', 'blue-zones', 'lifestyle-science', 'aging'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'meeting-l09',
    title: 'Authentic Connections',
    blurb: 'Discuss what makes social connections truly meaningful.',
    level: 9, spiralGroup: 'meeting-people', spiralOrder: 5,
    prerequisites: ['meeting-l07'],
    category: 'Social',
    scenarioBrief: 'Discuss authentic connection. "Superficial conversations leave me empty." Use abstract vocabulary and personal reflection. Push for what deep connection means to them. What makes a conversation truly meaningful?',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-second', 'hedging'],
    targetVocab: ['authenticity', 'connection-extended', 'depth', 'vulnerability', 'meaning'],
    difficulty: 'core',
  },
  {
    id: 'relationships-l09',
    title: 'Love Languages',
    blurb: 'Discuss different ways people express and receive love.',
    level: 9, spiralGroup: 'relationships', spiralOrder: 5,
    prerequisites: ['relationships-l08'],
    category: 'Social',
    scenarioBrief: 'Discuss love languages. "Words of affirmation matter most to me." Use present simple for personal preferences. Push for self-reflection. How do they show love? How do they prefer to receive it? Warm and personal.',
    targetGrammar: ['present-simple', 'conditional-second', 'discourse-markers', 'hedging'],
    targetVocab: ['love-languages', 'affection', 'connection-complex', 'emotional-needs'],
    difficulty: 'practice',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'travel-l09',
    title: 'Travel & Transformation',
    blurb: 'Discuss how travel can transform your perspective.',
    level: 9, spiralGroup: 'travel-planning', spiralOrder: 4,
    prerequisites: ['travel-l07'],
    category: 'Travel',
    scenarioBrief: 'Reflect on travel\'s transformative power. "Travel opens your mind to new possibilities." Use present perfect for experiences, abstract vocabulary for impact. Push for deep reflections on how travel changed them.',
    targetGrammar: ['present-perfect', 'discourse-markers', 'nominalization', 'conditional-second'],
    targetVocab: ['transformation', 'perspective', 'travel-impact', 'mindset', 'adventure-extended'],
    difficulty: 'core',
  },
  {
    id: 'culture-l09',
    title: 'Cultural Immersion',
    blurb: 'Discuss the experience of fully immersing in a new culture.',
    level: 9, spiralGroup: 'cultural-experiences', spiralOrder: 5,
    prerequisites: ['culture-l07'],
    category: 'Travel',
    scenarioBrief: 'Discuss deep cultural immersion. "Living abroad changed how I see the world." Use past tenses for narrative. Push for emotional and psychological journey. How did they change? What did they learn about themselves?',
    targetGrammar: ['past-perfect', 'narrative-tenses', 'discourse-markers', 'reported-speech'],
    targetVocab: ['immersion', 'transformation-extended', 'identity-shift', 'cultural-adaptation'],
    difficulty: 'practice',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'shopping-l09',
    title: 'Consumer Culture',
    blurb: 'Discuss consumerism and its impact on society.',
    level: 9, spiralGroup: 'shopping', spiralOrder: 5,
    prerequisites: ['shopping-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss consumer culture. "We buy things we don\'t need to impress people we don\'t like." Use passive and hedging. Push for critical analysis of consumerism and materialism. Philosophical discussion.',
    targetGrammar: ['passive-present', 'nominalization', 'discourse-markers', 'hedging'],
    targetVocab: ['consumerism', 'materialism', 'advertising', 'society-extended', 'values-extended'],
    difficulty: 'core',
  },
  {
    id: 'services-l09',
    title: 'The Service Industry',
    blurb: 'Discuss the quality and role of service in society.',
    level: 9, spiralGroup: 'services', spiralOrder: 3,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief: 'Discuss service industry. "Great service anticipates needs before they\'re expressed." Use passive and present tenses. Push for cross-cultural comparison. What makes excellent service? Share experiences.',
    targetGrammar: ['passive-present', 'conditional-zero', 'discourse-markers', 'comparatives'],
    targetVocab: ['service-industry', 'customer-care', 'hospitality-extended', 'professionalism'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'business-l09',
    title: 'Leadership & Vision',
    blurb: 'Discuss what makes a great leader.',
    level: 9, spiralGroup: 'business', spiralOrder: 3,
    prerequisites: ['business-l08'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss leadership. "A great leader inspires, not commands." Use abstract vocabulary and nominalization. Push for personal examples of good and bad leadership. Reflective and insightful conversation.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-second', 'hedging'],
    targetVocab: ['leadership', 'vision', 'inspiration', 'management', 'influence'],
    difficulty: 'core',
  },
  {
    id: 'jobs-l09',
    title: 'Finding Purpose at Work',
    blurb: 'Discuss finding meaning and purpose in your career.',
    level: 9, spiralGroup: 'jobs', spiralOrder: 4,
    prerequisites: ['jobs-l07'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss career purpose. "I want my work to make a difference." Use mixed conditionals and abstract vocabulary. Push for deep reflection on what meaningful work means. Supportive and thought-provoking.',
    targetGrammar: ['conditional-mixed', 'nominalization', 'discourse-markers', 'hedging'],
    targetVocab: ['purpose', 'meaningful-work', 'vocation', 'impact', 'fulfillment'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'hypothetical-l09',
    title: 'Moral Dilemmas',
    blurb: 'Explore complex moral dilemmas and justify your choices.',
    level: 9, spiralGroup: 'hypotheticals', spiralOrder: 4,
    prerequisites: ['hypothetical-l08'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Present moral dilemmas — the trolley problem, the lifeboat scenario. Use third and mixed conditionals. Push for reasoning and ethical framework. Discuss different philosophical perspectives. Deep debate.',
    targetGrammar: ['conditional-third', 'conditional-mixed', 'hedging', 'discourse-markers'],
    targetVocab: ['ethics-extended', 'morality', 'dilemma', 'consequences', 'philosophy-extended'],
    difficulty: 'core',
  },
  {
    id: 'storytelling-l09',
    title: 'Personal Myth',
    blurb: 'Tell a story that has become part of your personal myth.',
    level: 9, spiralGroup: 'storytelling', spiralOrder: 4,
    prerequisites: ['storytelling-l08'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Invite a story that defines them — a personal myth. "Tell me the story you tell yourself about who you are." Use sophisticated narrative techniques. Push for meaning and symbolism. Deep storytelling.',
    targetGrammar: ['narrative-tenses', 'past-perfect', 'discourse-markers', 'figurative-language'],
    targetVocab: ['personal-myth', 'identity-narrative', 'symbolism', 'meaning-extended'],
    difficulty: 'core',
  },
  {
    id: 'opinion-l09',
    title: 'Debate: Free Will',
    blurb: 'Debate whether humans have free will.',
    level: 9, spiralGroup: 'opinions', spiralOrder: 5,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief: 'Debate free will versus determinism. Use third conditionals, hedging, and sophisticated connectors. Push for structured argumentation with counter-points. Respectful philosophical debate. No right answer.',
    targetGrammar: ['conditional-third', 'conditional-mixed', 'hedging', 'discourse-markers', 'nominalization'],
    targetVocab: ['free-will', 'determinism', 'consciousness', 'philosophy-debate', 'argumentation-complex'],
    difficulty: 'challenge',
  },
  {
    id: 'memories-l09',
    title: 'The Stories We Tell',
    blurb: 'Discuss how we shape our memories into stories.',
    level: 9, spiralGroup: 'memories', spiralOrder: 5,
    prerequisites: ['memories-l08'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore memory as narrative. "We don\'t remember what happened; we remember the story we told ourselves." Use abstract language. Push for meta-cognitive reflection. How have they rewritten their own story?',
    targetGrammar: ['nominalization', 'discourse-markers', 'hedging', 'reported-speech'],
    targetVocab: ['memory-extended', 'narrative-identity', 'storytelling-complex', 'perception'],
    difficulty: 'practice',
  },
  {
    id: 'dreams-l09',
    title: 'Regrets & Lessons',
    blurb: 'Discuss regrets and what they\'ve taught you.',
    level: 9, spiralGroup: 'dreams-goals', spiralOrder: 5,
    prerequisites: ['goals-l08'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Reflect on regrets. "I regret not studying abroad, but I learned to seize opportunities." Use third conditional for regrets. Push for honest reflection with a positive framing. Warm and growth-oriented.',
    targetGrammar: ['conditional-third', 'wish-past', 'discourse-markers', 'hedging'],
    targetVocab: ['regret', 'lessons', 'growth', 'reflection-extended', 'wisdom-extended'],
    difficulty: 'practice',
  },
  {
    id: 'advice-l09',
    title: 'Mentorship & Guidance',
    blurb: 'Discuss the role of mentors in personal growth.',
    level: 9, spiralGroup: 'advice', spiralOrder: 4,
    prerequisites: ['advice-l08'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss mentorship. "A good mentor doesn\'t give answers; they ask better questions." Use abstract vocabulary. Push for personal experiences with mentors. How have others shaped their path? Reflective.',
    targetGrammar: ['discourse-markers', 'hedging', 'nominalization', 'conditional-second'],
    targetVocab: ['mentorship', 'guidance', 'role-models', 'growth-extended', 'influence'],
    difficulty: 'practice',
  },

  // ── Culture & Deep ────────────────────────────────────────────────────
  {
    id: 'culture-l09deep',
    title: 'Cultural Identity',
    blurb: 'Discuss how culture shapes who we are.',
    level: 9, spiralGroup: 'cultural-comparison', spiralOrder: 3,
    prerequisites: ['culture-l07deep'],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore cultural identity. "I\'m a product of two cultures." Use hedging for sensitivity and abstract vocabulary. Push for deep reflection on how culture shaped worldview. Personal and thoughtful.',
    targetGrammar: ['passive-present', 'discourse-markers', 'hedging', 'nominalization'],
    targetVocab: ['cultural-identity', 'bicultural', 'heritage', 'worldview', 'belonging-extended'],
    difficulty: 'core',
  },
  {
    id: 'arts-l09',
    title: 'Art Criticism',
    blurb: 'Analyze and critique a work of art or media.',
    level: 9, spiralGroup: 'arts', spiralOrder: 3,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'Critique a piece of art, film, or literature. "The director uses light and shadow to convey isolation." Use sophisticated descriptive language and discourse markers. Push for structured analysis. Think like a critic.',
    targetGrammar: ['present-simple', 'passive-present', 'discourse-markers', 'figurative-language'],
    targetVocab: ['art-criticism', 'aesthetics', 'analysis', 'interpretation', 'art-vocabulary'],
    difficulty: 'core',
  },
  {
    id: 'society-l09',
    title: 'Social Justice',
    blurb: 'Discuss social justice issues and equality.',
    level: 9, spiralGroup: 'society', spiralOrder: 2,
    prerequisites: ['culture-l08'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss social justice. "Equality means giving everyone what they need." Use passive and hedging. Push for nuanced discussion with real examples. Respectful debate on sensitive issues. Balanced perspective.',
    targetGrammar: ['passive-present', 'hedging', 'discourse-markers', 'conditional-second'],
    targetVocab: ['social-justice', 'equality', 'rights', 'fairness', 'activism'],
    difficulty: 'challenge',
  },

  // ── Expression ─────────────────────────────────────────────────────────
  {
    id: 'register-l09',
    title: 'Register Mastery',
    blurb: 'Master switching registers in complex situations.',
    level: 9, spiralGroup: 'register', spiralOrder: 3,
    prerequisites: ['register-l08'],
    category: 'Expression',
    scenarioBrief: 'Practice complex register shifts. Start formal (business proposal), shift to casual (friend catching up), then to emotional (comforting someone). Coach on appropriateness and naturalness. Advanced practice.',
    targetGrammar: ['formal-informal-shift', 'passive-formality', 'discourse-markers', 'modal-politeness'],
    targetVocab: ['register-complex', 'tone', 'appropriateness', 'emotional-language'],
    difficulty: 'core',
  },
  {
    id: 'figurative-l09',
    title: 'Metaphor & Meaning',
    blurb: 'Explore metaphor and figurative language in depth.',
    level: 9, spiralGroup: 'figurative', spiralOrder: 1,
    prerequisites: [],
    category: 'Expression',
    scenarioBrief: 'Explore metaphor. "Life is a journey." "Love is a battlefield." Discuss how metaphors shape thinking. Ask the user to create original metaphors. Push for creative and abstract thinking. Poetic conversation.',
    targetGrammar: ['figurative-language', 'simile', 'metaphor-structures', 'discourse-markers'],
    targetVocab: ['metaphor', 'figurative-extended', 'imagery', 'poetic-language', 'symbolism'],
    difficulty: 'core',
  },
]
