import type { ConversationSeed } from '../types'

/**
 * Level 10 — Expert Speaker
 * AI: 0% native, 100% target. Near-native expression, technical topics.
 * 25 seeds: Story (2), Daily (3), Social (1), Travel (2), Work (4), Ideas (6), Culture (4), Expression (3)
 */

export const SEEDS_L10: ConversationSeed[] = [
  // ── Story & Self ────────────────────────────────────────────────────────
  {
    id: 'story-l10',
    title: 'Overcoming Adversity',
    blurb: 'Tell a story of overcoming a significant challenge.',
    level: 10, spiralGroup: 'story', spiralOrder: 5,
    prerequisites: ['story-l08'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Narrative of overcoming adversity. Use sophisticated narrative tenses, vivid sensory details, emotional depth. Push for 10+ sentence story with clear arc. Coach on dramatic pacing and reflection. Inspiring.',
    targetGrammar: ['past-perfect', 'narrative-tenses', 'discourse-markers', 'emphasis', 'inversion'],
    targetVocab: ['adversity', 'triumph', 'determination', 'support-complex', 'emotional-journey'],
    difficulty: 'core',
  },
  {
    id: 'heritage-l10',
    title: 'Heritage & Roots',
    blurb: 'Discuss your heritage and ancestral roots.',
    level: 10, spiralGroup: 'identity', spiralOrder: 6,
    prerequisites: ['whoami-l09'],
    category: 'Daily Life',
    scenarioBrief: 'Explore heritage. "My grandmother came from a small village in..." Use past perfect for family history. Push for connection between past and present identity. How does heritage shape who they are today?',
    targetGrammar: ['past-perfect', 'passive-past', 'discourse-markers', 'hedging'],
    targetVocab: ['heritage', 'ancestry', 'roots-extended', 'family-history', 'legacy'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'routines-l10',
    title: 'High Performance Habits',
    blurb: 'Discuss habits of highly effective people.',
    level: 10, spiralGroup: 'routines', spiralOrder: 8,
    prerequisites: ['routines-l08'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss peak performance. "The most successful people wake up at 5 AM." Use reported speech and passive for research findings. Push for critical evaluation of advice. What actually works? Evidence-based discussion.',
    targetGrammar: ['reported-speech', 'passive-present', 'discourse-markers', 'conditional-zero'],
    targetVocab: ['performance', 'effectiveness', 'discipline-extended', 'optimization', 'routine-complex'],
    difficulty: 'practice',
  },
  {
    id: 'money-l10',
    title: 'Economic Systems',
    blurb: 'Discuss capitalism, socialism, and economic models.',
    level: 10, spiralGroup: 'money', spiralOrder: 5,
    prerequisites: ['money-l08'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss economic systems. "Capitalism drives innovation but increases inequality." Use passive and hedging. Push for balanced argument with specific examples. Respectful debate on complex economic ideas.',
    targetGrammar: ['passive-present', 'hedging', 'discourse-markers', 'nominalization'],
    targetVocab: ['economics', 'capitalism', 'socialism', 'inequality-extended', 'policy-extended'],
    difficulty: 'challenge',
  },
  {
    id: 'food-l10',
    title: 'The Future of Food',
    blurb: 'Discuss lab-grown meat, vertical farming, and food tech.',
    level: 10, spiralGroup: 'food', spiralOrder: 9,
    prerequisites: ['food-l09'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss food technology. "Lab-grown meat could solve many ethical and environmental issues." Use speculation modals and conditionals. Push for informed opinions. Discuss pros, cons, and future implications.',
    targetGrammar: ['modal-speculation', 'future-perfect', 'conditional-second', 'passive-present'],
    targetVocab: ['food-tech', 'lab-grown', 'vertical-farming', 'innovation-extended', 'food-future'],
    difficulty: 'practice',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'social-l10',
    title: 'Social Media & Identity',
    blurb: 'Discuss how social media shapes our sense of self.',
    level: 10, spiralGroup: 'social-situations', spiralOrder: 4,
    prerequisites: ['social-l06'],
    category: 'Social',
    scenarioBrief: 'Explore social media\'s effect on identity. "Our online persona is often different from who we really are." Use passive and abstract vocabulary. Push for critical analysis and personal reflection. Deep discussion.',
    targetGrammar: ['passive-present', 'nominalization', 'discourse-markers', 'hedging'],
    targetVocab: ['digital-identity', 'persona', 'self-extended', 'authenticity-extended', 'online-culture'],
    difficulty: 'core',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'travel-l10',
    title: 'Sustainable Tourism',
    blurb: 'Discuss responsible and sustainable travel.',
    level: 10, spiralGroup: 'travel-planning', spiralOrder: 5,
    prerequisites: ['travel-l09'],
    category: 'Travel',
    scenarioBrief: 'Discuss sustainable tourism. "Overtourism is destroying the places we love to visit." Use passive for impact, conditionals for solutions. Push for actionable ideas and personal responsibility. Informed discussion.',
    targetGrammar: ['passive-present', 'conditional-second', 'discourse-markers', 'hedging'],
    targetVocab: ['sustainable-tourism', 'overtourism', 'eco-friendly', 'responsible-travel', 'conservation'],
    difficulty: 'core',
  },
  {
    id: 'culture-l10',
    title: 'Globalization & Culture',
    blurb: 'Discuss how globalization affects local cultures.',
    level: 10, spiralGroup: 'cultural-experiences', spiralOrder: 6,
    prerequisites: ['culture-l09'],
    category: 'Travel',
    scenarioBrief: 'Discuss globalization. "Local traditions are disappearing due to globalization." Use passive extensively. Push for balanced analysis. What is lost? What is gained? Nuanced cultural discussion.',
    targetGrammar: ['passive-present', 'passive-past', 'discourse-markers', 'hedging'],
    targetVocab: ['globalization', 'cultural-loss', 'cultural-exchange', 'homogenization', 'preservation'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'business-l10',
    title: 'Negotiation Strategies',
    blurb: 'Discuss effective negotiation techniques.',
    level: 10, spiralGroup: 'business', spiralOrder: 4,
    prerequisites: ['business-l09'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss negotiation. "Win-win negotiation builds long-term relationships." Use second conditional for strategies. Roleplay a negotiation scenario. Coach on diplomatic language and tactical concession.',
    targetGrammar: ['conditional-second', 'discourse-markers', 'hedging', 'modals-would'],
    targetVocab: ['negotiation', 'diplomacy', 'compromise', 'strategy', 'win-win'],
    difficulty: 'core',
  },
  {
    id: 'academic-l10',
    title: 'Academic Argumentation',
    blurb: 'Present a structured academic argument on a topic.',
    level: 10, spiralGroup: 'academic', spiralOrder: 2,
    prerequisites: ['academic-l08'],
    category: 'Work & Study',
    scenarioBrief: 'Present an academic argument. "While some argue that X, evidence suggests Y." Use formal academic register, passive, hedging, and citation language. Push for structured thesis-antithesis-synthesis. Scholarly tone.',
    targetGrammar: ['passive-all-tenses', 'hedging', 'nominalization', 'discourse-markers', 'inversion'],
    targetVocab: ['academic-extended', 'argumentation-complex', 'evidence', 'analysis-extended', 'formal-language'],
    difficulty: 'challenge',
  },
  {
    id: 'skills-l10',
    title: 'Expertise & Mastery',
    blurb: 'Discuss the path to true expertise in any field.',
    level: 10, spiralGroup: 'skills', spiralOrder: 4,
    prerequisites: ['skills-l07'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss mastery. "It takes deliberate practice, not just time, to achieve mastery." Use abstract vocabulary. Push for understanding of the mastery process. What does it take to be truly expert?',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-zero', 'hedging'],
    targetVocab: ['expertise', 'mastery-complex', 'deliberate-practice', 'genius', 'talent-vs-work'],
    difficulty: 'practice',
  },
  {
    id: 'leadership-l10',
    title: 'Leading Change',
    blurb: 'Discuss how to lead organizational change.',
    level: 10, spiralGroup: 'business', spiralOrder: 4,
    prerequisites: ['business-l10'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss change management. "Change is hard because people fear the unknown." Use mixed conditionals. Push for strategies and real examples. How would they lead their team through a major change?',
    targetGrammar: ['conditional-mixed', 'discourse-markers', 'hedging', 'passive-present'],
    targetVocab: ['change-management', 'transformation-extended', 'adaptability', 'vision-extended', 'influence-extended'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'hypothetical-l10',
    title: 'Future Scenarios',
    blurb: 'Explore detailed future scenarios and their implications.',
    level: 10, spiralGroup: 'hypotheticals', spiralOrder: 5,
    prerequisites: ['hypothetical-l09'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore future scenarios. "If AI becomes more intelligent than humans..." Use mixed conditionals and future perfect. Push for detailed scenario analysis. Discuss implications across society, ethics, daily life.',
    targetGrammar: ['conditional-mixed', 'future-perfect', 'modal-speculation', 'discourse-markers'],
    targetVocab: ['future-scenarios', 'futurism', 'speculation', 'impact-analysis', 'possibilities-extended'],
    difficulty: 'core',
  },
  {
    id: 'storytelling-l10',
    title: 'Satire & Parody',
    blurb: 'Tell a satirical or humorous story with a message.',
    level: 10, spiralGroup: 'storytelling', spiralOrder: 5,
    prerequisites: ['storytelling-l09'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Create a satirical story. Use irony, exaggeration, and wit. Push for narrative with a social message. Coach on satirical techniques. Think like a comedian-writer. Clever and engaging.',
    targetGrammar: ['inversion', 'emphasis', 'discourse-markers', 'figurative-language'],
    targetVocab: ['satire', 'parody', 'irony', 'wit-extended', 'social-commentary'],
    difficulty: 'challenge',
  },
  {
    id: 'opinion-l10',
    title: 'The Greater Good',
    blurb: 'Debate utilitarian vs deontological ethics.',
    level: 10, spiralGroup: 'opinions', spiralOrder: 6,
    prerequisites: ['opinion-l09'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Debate ethical frameworks. "The greatest good for the greatest number." Use sophisticated conditional structures and hedging. Push for understanding of both sides. Philosophical depth. No simple answers.',
    targetGrammar: ['conditional-mixed', 'nominalization', 'hedging', 'discourse-markers'],
    targetVocab: ['ethics-complex', 'utilitarianism', 'deontology', 'moral-philosophy', 'consequences-extended'],
    difficulty: 'challenge',
  },
  {
    id: 'memories-l10',
    title: 'The Passage of Time',
    blurb: 'Reflect on how your perception of time has changed.',
    level: 10, spiralGroup: 'memories', spiralOrder: 6,
    prerequisites: ['memories-l09'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Reflect on time. "Time seems to move faster as we age." Use abstract vocabulary and mixed tenses. Push for philosophical reflection. How has their relationship with time changed? Poetic and thoughtful.',
    targetGrammar: ['present-perfect', 'used-to', 'discourse-markers', 'nominalization'],
    targetVocab: ['time-perception', 'aging', 'reflection-complex', 'temporality', 'awareness'],
    difficulty: 'practice',
  },
  {
    id: 'dreams-l10',
    title: 'Living Your Purpose',
    blurb: 'Discuss what it means to live a purposeful life.',
    level: 10, spiralGroup: 'dreams-goals', spiralOrder: 6,
    prerequisites: ['dreams-l09'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss purpose. "Living with purpose means waking up excited every day." Use abstract vocabulary and mixed conditionals. Push for deep reflection. What gives their life meaning? Existential but grounding conversation.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'hedging'],
    targetVocab: ['purpose-extended', 'meaning-complex', 'fulfillment-extended', 'vocation-extended', 'existential'],
    difficulty: 'core',
  },
  {
    id: 'advice-l10',
    title: 'Cross-Cultural Mediation',
    blurb: 'Mediate a conflict between people from different cultures.',
    level: 10, spiralGroup: 'advice', spiralOrder: 5,
    prerequisites: ['advice-l09'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Roleplay mediating a cross-cultural misunderstanding. Use diplomatic language, hedging, and indirectness. Coach on cultural sensitivity. Push for a win-win resolution. Professional and nuanced.',
    targetGrammar: ['hedging', 'indirect-questions', 'conditional-second', 'discourse-markers', 'diplomatic-language'],
    targetVocab: ['mediation', 'diplomacy-extended', 'conflict-resolution', 'cultural-bridge', 'understanding'],
    difficulty: 'challenge',
  },

  // ── Culture & Deep ────────────────────────────────────────────────────
  {
    id: 'arts-l10',
    title: 'Art & Social Change',
    blurb: 'Discuss how art can drive social and political change.',
    level: 10, spiralGroup: 'arts', spiralOrder: 4,
    prerequisites: ['arts-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss art as activism. "Art has the power to challenge the status quo." Use present perfect and passive. Push for specific examples. How has art changed society throughout history? Thoughtful discussion.',
    targetGrammar: ['present-perfect', 'passive-past', 'discourse-markers', 'nominalization'],
    targetVocab: ['art-activism', 'protest-art', 'social-change', 'expression-complex', 'cultural-impact'],
    difficulty: 'core',
  },
  {
    id: 'society-l10',
    title: 'The Role of Government',
    blurb: 'Discuss the proper role of government in society.',
    level: 10, spiralGroup: 'society', spiralOrder: 3,
    prerequisites: ['society-l09'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss governance. "The government should protect its citizens while respecting freedom." Use passive, hedging, and conditionals. Push for balanced argument with real-world examples. Respectful political discussion.',
    targetGrammar: ['passive-all-tenses', 'hedging', 'conditional-second', 'discourse-markers'],
    targetVocab: ['governance', 'politics', 'freedom', 'regulation', 'democracy'],
    difficulty: 'practice',
  },
  {
    id: 'abstract-l10',
    title: 'Consciousness & Self',
    blurb: 'Discuss the nature of consciousness and self-awareness.',
    level: 10, spiralGroup: 'abstract', spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss consciousness. "What does it mean to be conscious?" Use sophisticated language and third conditionals. Push for philosophical exploration. No right answers. Mind-expanding conversation.',
    targetGrammar: ['conditional-third', 'nominalization', 'hedging', 'discourse-markers', 'subjunctive'],
    targetVocab: ['consciousness', 'self-awareness', 'mind', 'philosophy-mind', 'existence'],
    difficulty: 'core',
  },
  {
    id: 'identity-l10',
    title: 'Intersectionality',
    blurb: 'Discuss how different aspects of identity intersect.',
    level: 10, spiralGroup: 'cultural-comparison', spiralOrder: 4,
    prerequisites: ['culture-l09deep'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss intersectional identity. "My identity is shaped by my race, gender, and class all at once." Use hedging for sensitivity. Push for nuanced understanding. How do different parts of identity interact? Deep.',
    targetGrammar: ['hedging', 'discourse-markers', 'passive-present', 'nominalization'],
    targetVocab: ['intersectionality', 'identity-complex', 'privilege', 'multiple-identities', 'social-layers'],
    difficulty: 'challenge',
  },

  // ── Expression ─────────────────────────────────────────────────────────
  {
    id: 'idioms-l10',
    title: 'Idioms Mastery',
    blurb: 'Master advanced idiomatic expressions naturally.',
    level: 10, spiralGroup: 'idioms', spiralOrder: 3,
    prerequisites: ['idioms-l08b'],
    category: 'Expression',
    scenarioBrief: 'Introduce 6-7 advanced idioms — "the ball is in your court", "barking up the wrong tree", "let the cat out of the bag", "burn the midnight oil", "hit the nail on the head", "once in a blue moon". Natural integration.',
    targetGrammar: ['idiomatic-expressions', 'phrasal-verbs-complex', 'discourse-markers', 'colloquial-complex'],
    targetVocab: ['idioms-advanced', 'expressions-complex', 'colloquial-advanced', 'figurative-advanced'],
    difficulty: 'core',
  },
  {
    id: 'humor-l10',
    title: 'Cultural Humor',
    blurb: 'Explore how humor differs across cultures.',
    level: 10, spiralGroup: 'humor', spiralOrder: 2,
    prerequisites: ['humor-l08'],
    category: 'Expression',
    scenarioBrief: 'Explore cultural humor differences. "British sarcasm doesn\'t always translate." Use hedging for generalizations. Push for specific examples of humor that doesn\'t cross borders. Compare comedy styles. Fun and educational.',
    targetGrammar: ['hedging', 'discourse-markers', 'comparatives', 'conditional-zero'],
    targetVocab: ['humor-extended', 'comedy-culture', 'sarcasm', 'cultural-humor', 'wordplay-extended'],
    difficulty: 'practice',
  },
  {
    id: 'figurative-l10',
    title: 'Poetic Expression',
    blurb: 'Create original poetic descriptions and imagery.',
    level: 10, spiralGroup: 'figurative', spiralOrder: 2,
    prerequisites: ['figurative-l09'],
    category: 'Expression',
    scenarioBrief: 'Create poetry or vivid imagery. Describe a sunset, a feeling, or a memory using metaphor and simile. Coach on poetic techniques. Push for originality and emotional resonance. Creative and expressive.',
    targetGrammar: ['figurative-language', 'inversion', 'emphasis', 'cleft-sentences'],
    targetVocab: ['poetry', 'imagery-extended', 'emotion-language', 'beauty', 'creative-expression'],
    difficulty: 'practice',
  },
]
