import type { ConversationSeed } from '../types'

/**
 * Level 11 — Precision Speaker
 * AI: 0% native, 100% target. Subtle nuance, register control, cultural depth.
 * 25 seeds: Self (2), Daily (2), Social (1), Travel (2), Commerce (1), Work (2), Ideas (6), Culture (5), Expression (4)
 */

export const SEEDS_L11: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l11',
    title: 'My Legacy',
    blurb: 'Discuss the legacy you want to leave behind.',
    level: 11, spiralGroup: 'identity', spiralOrder: 6,
    prerequisites: ['whoami-l09'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss legacy. "I want to be remembered for making a difference." Use future perfect and sophisticated vocabulary. Push for deep reflection. What mark do they want to leave on the world? Existential yet grounding.',
    targetGrammar: ['future-perfect', 'nominalization', 'discourse-markers', 'conditional-mixed'],
    targetVocab: ['legacy', 'impact-extended', 'remembrance', 'contribution', 'imprint'],
    difficulty: 'core',
  },
  {
    id: 'family-l11',
    title: 'Family Legacy',
    blurb: 'Discuss the legacy passed down through your family.',
    level: 11, spiralGroup: 'family', spiralOrder: 5,
    prerequisites: ['family-l07'],
    category: 'Daily Life',
    scenarioBrief: 'Explore family legacy. "My grandfather taught me the value of hard work." Use narrative past tenses. Push for emotional depth and gratitude. What has been passed down to them? What will they pass on?',
    targetGrammar: ['past-perfect', 'would-for-habits', 'discourse-markers', 'passive-past'],
    targetVocab: ['family-legacy', 'traditions-deep', 'heritage-complex', 'values-transmission'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'food-l11',
    title: 'Gastronomy Criticism',
    blurb: 'Write a sophisticated restaurant review.',
    level: 11, spiralGroup: 'food', spiralOrder: 10,
    prerequisites: ['food-l10'],
    category: 'Daily Life',
    scenarioBrief: 'Write a sophisticated review. Use elevated vocabulary, passive, and discourse markers. Push for structured critique covering concept, execution, service, atmosphere, value. Think Michelin inspector.',
    targetGrammar: ['passive-all-tenses', 'nominalization', 'discourse-markers', 'cleft-sentences'],
    targetVocab: ['gastronomy-advanced', 'wine-pairing', 'presentation-advanced', 'critique-sophisticated', 'culinary-vocabulary'],
    difficulty: 'practice',
  },
  {
    id: 'tech-l11',
    title: 'Technology & Humanity',
    blurb: 'Discuss the relationship between technology and humanity.',
    level: 11, spiralGroup: 'technology', spiralOrder: 7,
    prerequisites: ['tech-l09'],
    category: 'Daily Life',
    scenarioBrief: 'Explore tech\'s relationship with humanity. "Are we controlling technology, or is it controlling us?" Use abstract vocabulary and mixed conditionals. Push for philosophical depth. Thought-provoking debate.',
    targetGrammar: ['conditional-mixed', 'nominalization', 'hedging', 'discourse-markers', 'inversion'],
    targetVocab: ['technology-humanity', 'transhumanism', 'augmentation', 'ethics-advanced', 'future-extended'],
    difficulty: 'core',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'friends-l11',
    title: 'The Philosophy of Friendship',
    blurb: 'Discuss what friendship truly means on a deep level.',
    level: 11, spiralGroup: 'friendships', spiralOrder: 5,
    prerequisites: ['friends-l08'],
    category: 'Social',
    scenarioBrief: 'Explore friendship philosophically. "Aristotle said a friend is a single soul dwelling in two bodies." Use abstract vocabulary and philosophical references. Push for deep reflection on the nature of connection.',
    targetGrammar: ['reported-speech', 'nominalization', 'discourse-markers', 'conditional-mixed'],
    targetVocab: ['friendship-philosophy', 'soul', 'connection-deep', 'loyalty', 'companionship'],
    difficulty: 'core',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'travel-l11',
    title: 'Travel Philosophy',
    blurb: 'Discuss your personal philosophy of travel.',
    level: 11, spiralGroup: 'travel-planning', spiralOrder: 6,
    prerequisites: ['travel-l10'],
    category: 'Travel',
    scenarioBrief: 'Explore travel philosophy. "I travel to feel alive, not to check boxes." Use abstract vocabulary and personal reflection. Push for their travel manifesto. What kind of traveler are they? Deep and personal.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-second', 'hedging'],
    targetVocab: ['travel-philosophy', 'wanderlust', 'mindful-travel', 'exploration', 'curiosity'],
    difficulty: 'core',
  },
  {
    id: 'culture-l11',
    title: 'Cultural Hybridity',
    blurb: 'Discuss the beauty and challenges of mixed cultures.',
    level: 11, spiralGroup: 'cultural-experiences', spiralOrder: 7,
    prerequisites: ['culture-l10'],
    category: 'Travel',
    scenarioBrief: 'Discuss cultural hybridity. "I feel both and neither at the same time." Use abstract vocabulary and hedging. Push for personal experience of navigating multiple cultures. Poignant and reflective conversation.',
    targetGrammar: ['hedging', 'discourse-markers', 'nominalization', 'conditional-mixed'],
    targetVocab: ['hybridity', 'multicultural', 'third-culture', 'belonging-deep', 'identity-fluidity'],
    difficulty: 'practice',
  },

  // ── Commerce ───────────────────────────────────────────────────────────
  {
    id: 'services-l11',
    title: 'Ethics in Business',
    blurb: 'Discuss ethical dilemmas in the business world.',
    level: 11, spiralGroup: 'services', spiralOrder: 4,
    prerequisites: ['services-l09'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss business ethics. "Is it ethical to maximize profit at any cost?" Use passive and conditionals. Push for case study analysis. Present ethical dilemmas from real business scenarios. Thoughtful debate.',
    targetGrammar: ['conditional-third', 'passive-all-tenses', 'hedging', 'discourse-markers'],
    targetVocab: ['business-ethics', 'corporate-responsibility', 'sustainability-complex', 'fair-trade', 'accountability'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'academic-l11',
    title: 'Research Thesis',
    blurb: 'Present a mini thesis on a topic you care about.',
    level: 11, spiralGroup: 'academic', spiralOrder: 3,
    prerequisites: ['academic-l10'],
    category: 'Work & Study',
    scenarioBrief: 'Present a mini research thesis. Structure: introduction, literature review, argument, counter-argument, conclusion. Use formal academic register throughout. Coach on academic discourse markers. Scholarly.',
    targetGrammar: ['passive-all-tenses', 'nominalization', 'discourse-markers', 'inversion', 'hedging'],
    targetVocab: ['thesis', 'argumentation-academic', 'evidence-advanced', 'citation', 'discourse-academic'],
    difficulty: 'challenge',
  },
  {
    id: 'leadership-l11',
    title: 'Visionary Leadership',
    blurb: 'Discuss what it means to be a visionary leader.',
    level: 11, spiralGroup: 'business', spiralOrder: 5,
    prerequisites: ['leadership-l10'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss visionary leadership. "A visionary sees what others don\'t and convinces them to see it too." Use abstract vocabulary and mixed conditionals. Push for examples and personal philosophy of leadership.',
    targetGrammar: ['conditional-mixed', 'nominalization', 'discourse-markers', 'hedging'],
    targetVocab: ['visionary', 'transformation-advanced', 'inspiration-extended', 'movement', 'paradigm'],
    difficulty: 'practice',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'hypothetical-l11',
    title: 'Time Travel Ethics',
    blurb: 'Explore ethical paradoxes of time travel.',
    level: 11, spiralGroup: 'hypotheticals', spiralOrder: 6,
    prerequisites: ['hypothetical-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore time travel paradoxes. "If you go back in time and change one thing..." Use third and mixed conditionals expertly. Push for creative yet logically consistent scenarios. Fun and mind-bending.',
    targetGrammar: ['conditional-third', 'conditional-mixed', 'modal-speculation', 'discourse-markers'],
    targetVocab: ['time-travel', 'paradox', 'causality', 'butterfly-effect', 'quantum-possibilities'],
    difficulty: 'practice',
  },
  {
    id: 'storytelling-l11',
    title: 'A Story of Hope',
    blurb: 'Tell a deeply moving story of hope and resilience.',
    level: 11, spiralGroup: 'storytelling', spiralOrder: 6,
    prerequisites: ['storytelling-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Tell a deeply moving story. Use all narrative techniques — pacing, dialogue, sensory detail, emotional arc. Push for a story that inspires. Coach on emotional resonance and authenticity. Powerful storytelling.',
    targetGrammar: ['narrative-tenses', 'inversion', 'emphasis', 'cleft-sentences', 'figurative-language'],
    targetVocab: ['hope', 'resilience-extended', 'inspiration', 'emotional-mastery', 'story-mastery'],
    difficulty: 'core',
  },
  {
    id: 'opinion-l11',
    title: 'The Meaning of Life',
    blurb: 'Discuss different perspectives on life\'s meaning.',
    level: 11, spiralGroup: 'opinions', spiralOrder: 7,
    prerequisites: ['opinion-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Discuss life\'s meaning. "Camus said we must imagine Sisyphus happy." Use philosophical references and abstract vocabulary. Push for personal synthesis. What gives their life meaning? Profound conversation.',
    targetGrammar: ['nominalization', 'discourse-markers', 'hedging', 'conditional-mixed', 'subjunctive'],
    targetVocab: ['meaning-deep', 'existentialism', 'purpose-advanced', 'philosophy-life', 'transcendence'],
    difficulty: 'core',
  },
  {
    id: 'memories-l11',
    title: 'The Architecture of Memory',
    blurb: 'Discuss how memory works and shapes our reality.',
    level: 11, spiralGroup: 'memories', spiralOrder: 7,
    prerequisites: ['memories-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore memory scientifically and philosophically. "Memory is not a recording; it\'s a reconstruction." Use passive for scientific findings, abstract for philosophy. Push for understanding and personal insight.',
    targetGrammar: ['passive-present', 'nominalization', 'discourse-markers', 'hedging', 'reported-speech'],
    targetVocab: ['memory-science', 'neuroplasticity', 'recollection', 'perception-advanced', 'forgetting'],
    difficulty: 'practice',
  },
  {
    id: 'dreams-l11',
    title: 'Dreams vs Reality',
    blurb: 'Discuss the tension between dreams and practical reality.',
    level: 11, spiralGroup: 'dreams-goals', spiralOrder: 7,
    prerequisites: ['dreams-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore dreams vs reality. "I had to choose between my dream and financial security." Use mixed conditionals for reflection. Push for honest tension between aspiration and practicality. Deeply personal.',
    targetGrammar: ['conditional-mixed', 'discourse-markers', 'hedging', 'nominalization'],
    targetVocab: ['dreams-reality', 'sacrifice', 'ambition-extended', 'practicality', 'compromise-deep'],
    difficulty: 'core',
  },
  {
    id: 'advice-l11',
    title: 'Existential Coaching',
    blurb: 'Help someone navigate an existential crisis.',
    level: 11, spiralGroup: 'advice', spiralOrder: 6,
    prerequisites: ['advice-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Roleplay a life coach session. The user is navigating existential questions. Use empathetic language, powerful questions, and philosophical insight. Coach on finding meaning. Supportive yet challenging.',
    targetGrammar: ['conditional-second', 'hedging', 'discourse-markers', 'indirect-questions', 'empathetic-language'],
    targetVocab: ['coaching', 'existential', 'midlife-reflection', 'purpose-coaching', 'transformation-coaching'],
    difficulty: 'challenge',
  },

  // ── Culture & Deep ────────────────────────────────────────────────────
  {
    id: 'culture-l11deep',
    title: 'Cultural Paradigms',
    blurb: 'Compare deep cultural worldviews and paradigms.',
    level: 11, spiralGroup: 'cultural-comparison', spiralOrder: 5,
    prerequisites: ['identity-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'Compare worldviews. "Eastern philosophy emphasizes harmony, Western emphasizes individual achievement." Use abstract vocabulary and hedging. Push for deep understanding of how paradigms shape everything. Profound.',
    targetGrammar: ['discourse-markers', 'hedging', 'nominalization', 'passive-present'],
    targetVocab: ['paradigm', 'worldview', 'eastern-western', 'philosophy-compared', 'cultural-foundations'],
    difficulty: 'core',
  },
  {
    id: 'arts-l11',
    title: 'Art & the Sublime',
    blurb: 'Discuss the concept of the sublime in art and nature.',
    level: 11, spiralGroup: 'arts', spiralOrder: 5,
    prerequisites: ['arts-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore the sublime. "Great art makes us feel both awe and terror." Use sophisticated aesthetic vocabulary. Push for personal experiences of the sublime. What art or nature has left them speechless?',
    targetGrammar: ['nominalization', 'figurative-language', 'discourse-markers', 'inversion'],
    targetVocab: ['sublime', 'awe', 'beauty-advanced', 'transcendence-extended', 'aesthetics-complex'],
    difficulty: 'core',
  },
  {
    id: 'society-l11',
    title: 'Utopia & Dystopia',
    blurb: 'Discuss visions of ideal and nightmare societies.',
    level: 11, spiralGroup: 'society', spiralOrder: 4,
    prerequisites: ['society-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore utopia/dystopia. "Every utopia is someone\'s dystopia." Use abstract vocabulary and conditionals. Push for their vision of an ideal society. Discuss famous literary utopias and dystopias. Rich discussion.',
    targetGrammar: ['conditional-third', 'nominalization', 'discourse-markers', 'subjunctive'],
    targetVocab: ['utopia', 'dystopia', 'society-advanced', 'governance-advanced', 'ideal-society'],
    difficulty: 'practice',
  },
  {
    id: 'abstract-l11',
    title: 'The Nature of Time',
    blurb: 'Discuss philosophical and scientific views of time.',
    level: 11, spiralGroup: 'abstract', spiralOrder: 2,
    prerequisites: ['abstract-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore time. "Is time real, or is it a human construct?" Use sophisticated vocabulary and conditional structures. Push for understanding of different perspectives. Physics meets philosophy. Mind-expanding.',
    targetGrammar: ['conditional-third', 'nominalization', 'hedging', 'discourse-markers', 'subjunctive'],
    targetVocab: ['time-philosophy', 'eternity', 'temporality-advanced', 'physics-philosophy', 'perception-time'],
    difficulty: 'core',
  },
  {
    id: 'ethics-l11',
    title: 'AI & Ethics',
    blurb: 'Discuss the ethical implications of artificial intelligence.',
    level: 11, spiralGroup: 'society', spiralOrder: 4,
    prerequisites: ['abstract-l10'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss AI ethics. "If AI becomes conscious, does it have rights?" Use third and mixed conditionals. Push for nuanced argument across multiple ethical frameworks. Cutting-edge philosophical debate.',
    targetGrammar: ['conditional-mixed', 'subjunctive', 'nominalization', 'discourse-markers', 'hedging'],
    targetVocab: ['AI-ethics', 'consciousness-extended', 'machine-rights', 'singularity', 'ethics-complex'],
    difficulty: 'challenge',
  },

  // ── Expression ─────────────────────────────────────────────────────────
  {
    id: 'register-l11',
    title: 'Rhetorical Mastery',
    blurb: 'Master rhetorical devices for persuasion and impact.',
    level: 11, spiralGroup: 'register', spiralOrder: 4,
    prerequisites: ['register-l09'],
    category: 'Expression',
    scenarioBrief: 'Practice rhetorical devices — anaphora, tricolon, rhetorical questions, antithesis, chiasmus. Coach on using each device effectively. Push for a short persuasive speech. Think Cicero. Powerful oratory.',
    targetGrammar: ['inversion', 'emphasis', 'cleft-sentences', 'discourse-markers', 'rhetorical-devices'],
    targetVocab: ['rhetoric', 'persuasion-advanced', 'oratory', 'devices-rhetorical', 'impact-language'],
    difficulty: 'core',
  },
  {
    id: 'humor-l11',
    title: 'Wit & Wordplay',
    blurb: 'Master witty wordplay and clever linguistic humor.',
    level: 11, spiralGroup: 'humor', spiralOrder: 3,
    prerequisites: ['humor-l10'],
    category: 'Expression',
    scenarioBrief: 'Explore advanced wordplay. Puns, double entendres, malapropisms, spoonerisms. Discuss how wordplay reveals language mastery. Challenge the user to create original wordplay. Clever and fun.',
    targetGrammar: ['figurative-language', 'ambiguity', 'polysemy', 'puns', 'wordplay-advanced'],
    targetVocab: ['wordplay-mastery', 'puns-advanced', 'linguistic-humor', 'double-meanings', 'wit-mastery'],
    difficulty: 'practice',
  },
  {
    id: 'figurative-l11',
    title: 'Extended Metaphor',
    blurb: 'Create and sustain an extended metaphor in speech.',
    level: 11, spiralGroup: 'figurative', spiralOrder: 3,
    prerequisites: ['figurative-l10'],
    category: 'Expression',
    scenarioBrief: 'Create an extended metaphor. Choose a complex topic (love, time, life) and describe it through a single sustained metaphor for 2+ minutes. Coach on consistency and creativity. Poetic and impressive.',
    targetGrammar: ['figurative-language', 'metaphor-extended', 'discourse-markers', 'cleft-sentences'],
    targetVocab: ['extended-metaphor', 'allegory', 'imagery-mastery', 'conceit', 'poetic-mastery'],
    difficulty: 'core',
  },
  {
    id: 'sarcasm-l11',
    title: 'Sarcasm & Irony',
    blurb: 'Master sarcasm and verbal irony in conversation.',
    level: 11, spiralGroup: 'register', spiralOrder: 4,
    prerequisites: ['humor-l11'],
    category: 'Expression',
    scenarioBrief: 'Explore sarcasm and irony. "I love when the WiFi goes out during an important meeting." Discuss cultural differences in sarcasm. Practice using it appropriately. Coach on tone and context. Sophisticated humor.',
    targetGrammar: ['emphasis', 'inversion', 'discourse-markers', 'figurative-language'],
    targetVocab: ['sarcasm', 'irony-verbal', 'deadpan', 'tone-mastery', 'humor-sophisticated'],
    difficulty: 'challenge',
  },
]
