import type { ConversationSeed } from '../types'

/**
 * Level 12 — Mastery (Native-Level)
 * AI: 0% native, 100% target. Full native fluency, any topic, any register.
 * 25 seeds: Self (2), Daily (1), Social (1), Travel (1), Work (3), Ideas (6), Culture (6), Expression (5)
 */

export const SEEDS_L12: ConversationSeed[] = [
  // ── Self & Identity ──────────────────────────────────────────────────────
  {
    id: 'whoami-l12',
    title: 'The Complete Self',
    blurb: 'Integrate all aspects of your identity into a coherent whole.',
    level: 12, spiralGroup: 'identity', spiralOrder: 7,
    prerequisites: ['whoami-l11'],
    category: 'Daily Life',
    scenarioBrief: 'Synthesize identity. "I am the sum of my experiences, choices, and relationships." Use sophisticated language across all registers. Push for a holistic self-portrait in 10+ sentences. Profound self-reflection.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'cleft-sentences', 'inversion'],
    targetVocab: ['self-mastery', 'integration', 'wholeness', 'identity-synthesis', 'being'],
    difficulty: 'core',
  },
  {
    id: 'feelings-l12',
    title: 'Emotional Mastery',
    blurb: 'Discuss emotional mastery and self-regulation.',
    level: 12, spiralGroup: 'feelings', spiralOrder: 6,
    prerequisites: ['feelings-l09'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss emotional mastery. "I no longer react; I respond." Use sophisticated vocabulary and personal insight. Push for deep understanding of their emotional landscape. Coach on advanced emotional intelligence.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'hedging'],
    targetVocab: ['emotional-mastery', 'equanimity', 'self-regulation', 'wisdom-deep', 'presence'],
    difficulty: 'core',
  },

  // ── Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'routines-l12',
    title: 'The Art of Living',
    blurb: 'Discuss what it means to live a well-designed life.',
    level: 12, spiralGroup: 'routines', spiralOrder: 9,
    prerequisites: ['routines-l10'],
    category: 'Daily Life',
    scenarioBrief: 'Discuss the art of living. "Life is not a problem to be solved, but a reality to be experienced." Use philosophical vocabulary. Push for their philosophy of daily living. Profound and practical.',
    targetGrammar: ['nominalization', 'discourse-markers', 'figurative-language', 'inversion'],
    targetVocab: ['art-of-living', 'mindfulness', 'presence-extended', 'wisdom-practical', 'flourishing'],
    difficulty: 'core',
  },

  // ── Social ──────────────────────────────────────────────────────────────
  {
    id: 'relationships-l12',
    title: 'The Nature of Love',
    blurb: 'Explore philosophical perspectives on love.',
    level: 12, spiralGroup: 'relationships', spiralOrder: 6,
    prerequisites: ['relationships-l09'],
    category: 'Social',
    scenarioBrief: 'Explore love philosophically. "Love is the ability to see another person clearly and accept them fully." Use abstract vocabulary and literary references. Push for personal synthesis. Profound conversation.',
    targetGrammar: ['nominalization', 'figurative-language', 'discourse-markers', 'conditional-mixed', 'subjunctive'],
    targetVocab: ['love-philosophy', 'agape', 'eros', 'philia', 'connection-ultimate'],
    difficulty: 'core',
  },

  // ── Travel & Places ──────────────────────────────────────────────────
  {
    id: 'travel-l12',
    title: 'The World as Home',
    blurb: 'Discuss feeling at home anywhere in the world.',
    level: 12, spiralGroup: 'travel-planning', spiralOrder: 7,
    prerequisites: ['travel-l11'],
    category: 'Travel',
    scenarioBrief: 'Discuss global citizenship. "I carry my home wherever I go." Use abstract vocabulary and metaphor. Push for reflections on what it means to be a citizen of the world. Poetic and expansive conversation.',
    targetGrammar: ['figurative-language', 'nominalization', 'discourse-markers', 'cleft-sentences'],
    targetVocab: ['global-citizenship', 'rootlessness', 'freedom-extended', 'belonging-ultimate', 'world-home'],
    difficulty: 'practice',
  },

  // ── Work & Study ───────────────────────────────────────────────────────
  {
    id: 'leadership-l12',
    title: 'Leading with Wisdom',
    blurb: 'Discuss wise leadership and its role in the world.',
    level: 12, spiralGroup: 'business', spiralOrder: 6,
    prerequisites: ['leadership-l11'],
    category: 'Work & Study',
    scenarioBrief: 'Discuss wise leadership. "A wise leader serves, not rules." Use abstract vocabulary and philosophical references. Push for a personal leadership philosophy. What does wise leadership look like today?',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'subjunctive'],
    targetVocab: ['wisdom-leadership', 'stewardship', 'service', 'legacy-advanced', 'transcendence-leadership'],
    difficulty: 'practice',
  },
  {
    id: 'academic-l12',
    title: 'Interdisciplinary Synthesis',
    blurb: 'Synthesize ideas from multiple fields into a coherent vision.',
    level: 12, spiralGroup: 'academic', spiralOrder: 4,
    prerequisites: ['academic-l11'],
    category: 'Work & Study',
    scenarioBrief: 'Synthesize across disciplines. Connect science, art, philosophy, and personal experience into a coherent vision. Use sophisticated academic register. Push for original insights. Think polymath.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'inversion', 'cleft-sentences'],
    targetVocab: ['synthesis', 'interdisciplinary', 'polymath', 'integration-complex', 'original-insight'],
    difficulty: 'challenge',
  },
  {
    id: 'purpose-l12',
    title: 'Life\'s Calling',
    blurb: 'Articulate your life\'s calling with clarity and conviction.',
    level: 12, spiralGroup: 'dreams-goals', spiralOrder: 8,
    prerequisites: ['dreams-l11'],
    category: 'Work & Study',
    scenarioBrief: 'Articulate life\'s calling. "My purpose is to help others find their voice." Use powerful, authentic language. Push for clarity and conviction. Coach on expressing purpose compellingly. Inspiring and profound.',
    targetGrammar: ['cleft-sentences', 'emphasis', 'discourse-markers', 'nominalization', 'figurative-language'],
    targetVocab: ['calling', 'vocation-deep', 'dharma', 'mission', 'purpose-articulation'],
    difficulty: 'core',
  },

  // ── Ideas & Stories ───────────────────────────────────────────────────
  {
    id: 'story-l12',
    title: 'The Story of My Life',
    blurb: 'Tell your complete life story as a meaningful narrative.',
    level: 12, spiralGroup: 'story', spiralOrder: 6,
    prerequisites: ['story-l10'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Tell your life story as a cohesive narrative with theme, arc, and meaning. Use masterful storytelling techniques. Push for wisdom and insight. Share back what you heard. Profound and moving exchange.',
    targetGrammar: ['narrative-tenses', 'discourse-markers', 'inversion', 'figurative-language', 'cleft-sentences'],
    targetVocab: ['life-narrative', 'arc', 'theme-deep', 'wisdom-narrative', 'story-mastery'],
    difficulty: 'core',
  },
  {
    id: 'hypothetical-l12',
    title: 'Ultimate What If',
    blurb: 'Explore the ultimate hypothetical: the end of everything.',
    level: 12, spiralGroup: 'hypotheticals', spiralOrder: 7,
    prerequisites: ['hypothetical-l11'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Explore the ultimate hypothetical: the end of the universe, the last day on Earth. Use masterful command of conditionals. Push for poetic and philosophical reflection. Cosmic conversation.',
    targetGrammar: ['conditional-mixed', 'subjunctive', 'nominalization', 'figurative-language', 'inversion'],
    targetVocab: ['cosmic', 'entropy', 'mortality', 'infinity', 'meaning-ultimate'],
    difficulty: 'practice',
  },
  {
    id: 'storytelling-l12',
    title: 'Myth-Making',
    blurb: 'Create an original myth or legend.',
    level: 12, spiralGroup: 'storytelling', spiralOrder: 7,
    prerequisites: ['storytelling-l11'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Create an original myth. Use archetypal characters, symbolic settings, and timeless themes. Coach on mythic structure — call to adventure, trials, transformation, return. Creative and profound.',
    targetGrammar: ['narrative-tenses', 'figurative-language', 'discourse-markers', 'symbolism', 'allegory'],
    targetVocab: ['myth', 'archetype', 'symbolism-advanced', 'hero-journey', 'creation'],
    difficulty: 'challenge',
  },
  {
    id: 'opinion-l12',
    title: 'The Examined Life',
    blurb: 'Socrates said the unexamined life is not worth living. Discuss.',
    level: 12, spiralGroup: 'opinions', spiralOrder: 8,
    prerequisites: ['opinion-l11'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Engage with Socrates\' claim. Use philosophical depth, personal reflection, and rhetorical sophistication. Push for original thesis. Defend, challenge, or reinterpret. Philosophical mastery.',
    targetGrammar: ['nominalization', 'discourse-markers', 'conditional-mixed', 'rhetorical-devices', 'inversion'],
    targetVocab: ['socratic', 'examined-life', 'philosophy-mastery', 'contemplation', 'wisdom-ultimate'],
    difficulty: 'core',
  },
  {
    id: 'memories-l12',
    title: 'The River of Memory',
    blurb: 'Reflect on how memory flows and shapes identity.',
    level: 12, spiralGroup: 'memories', spiralOrder: 8,
    prerequisites: ['memories-l11'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Reflect on memory as a flowing river. Use poetic and metaphorical language. Push for understanding of how past, present, and future connect through memory. Deeply reflective and philosophical.',
    targetGrammar: ['figurative-language', 'nominalization', 'discourse-markers', 'conditional-mixed'],
    targetVocab: ['memory-river', 'time-flow', 'identity-memory', 'continuity', 'transience'],
    difficulty: 'practice',
  },
  {
    id: 'advice-l12',
    title: 'Wisdom Circle',
    blurb: 'Share your deepest wisdom with someone who needs it.',
    level: 12, spiralGroup: 'advice', spiralOrder: 7,
    prerequisites: ['advice-l11'],
    category: 'Ideas & Stories',
    scenarioBrief: 'Share life wisdom. "The best advice I ever received was..." Use metaphorical and philosophical language. Push for distilled wisdom from a lifetime of experience. Think elder sage. Profound and generous.',
    targetGrammar: ['nominalization', 'figurative-language', 'discourse-markers', 'conditional-mixed'],
    targetVocab: ['wisdom-sharing', 'elder-wisdom', 'life-teachings', 'legacy-words', 'generosity'],
    difficulty: 'core',
  },

  // ── Culture & Deep ────────────────────────────────────────────────────
  {
    id: 'culture-l12',
    title: 'Global Consciousness',
    blurb: 'Discuss global citizenship and shared humanity.',
    level: 12, spiralGroup: 'cultural-comparison', spiralOrder: 6,
    prerequisites: ['culture-l11deep'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss global consciousness. "We are more alike than different." Use inspiring, inclusive language. Push for a vision of shared humanity. What connects all people across cultures? Uplifting and profound.',
    targetGrammar: ['nominalization', 'discourse-markers', 'figurative-language', 'inversion'],
    targetVocab: ['global-consciousness', 'humanity', 'unity', 'compassion', 'interconnectedness'],
    difficulty: 'core',
  },
  {
    id: 'arts-l12',
    title: 'Art & Transcendence',
    blurb: 'Discuss art as a path to transcendence.',
    level: 12, spiralGroup: 'arts', spiralOrder: 6,
    prerequisites: ['arts-l11'],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore art as transcendence. Use sophisticated aesthetic vocabulary and personal experience. Push for moments when art transported them. What does transcendent art feel like? Deeply personal and aesthetic.',
    targetGrammar: ['figurative-language', 'nominalization', 'discourse-markers', 'inversion'],
    targetVocab: ['transcendence-art', 'aesthetics-mastery', 'sublime-experience', 'beauty-mastery', 'art-soul'],
    difficulty: 'core',
  },
  {
    id: 'society-l12',
    title: 'The Future of Humanity',
    blurb: 'Discuss the long-term future of human civilization.',
    level: 12, spiralGroup: 'society', spiralOrder: 5,
    prerequisites: ['society-l11'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss humanity\'s long-term future. Use sophisticated speculative language across all tenses and moods. Push for a coherent vision. What will humanity look like in 1000 years? Cosmic perspective.',
    targetGrammar: ['conditional-mixed', 'modal-speculation', 'future-perfect', 'nominalization'],
    targetVocab: ['civilization', 'humanity-future', 'evolution', 'cosmic-perspective', 'transcendence-humanity'],
    difficulty: 'challenge',
  },
  {
    id: 'abstract-l12',
    title: 'The Nature of Reality',
    blurb: 'Discuss philosophical and scientific views of reality.',
    level: 12, spiralGroup: 'abstract', spiralOrder: 3,
    prerequisites: ['abstract-l11'],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore the nature of reality. "Is the universe a simulation?" Use masterful command of all grammatical structures. Push for synthesis of scientific and philosophical perspectives. Mind-expanding conversation.',
    targetGrammar: ['conditional-mixed', 'subjunctive', 'nominalization', 'discourse-markers', 'inversion'],
    targetVocab: ['reality-nature', 'simulation', 'perception-ultimate', 'quantum-mind', 'ontology'],
    difficulty: 'core',
  },
  {
    id: 'ethics-l12',
    title: 'Global Ethics',
    blurb: 'Discuss ethical responsibilities to all of humanity.',
    level: 12, spiralGroup: 'society', spiralOrder: 5,
    prerequisites: ['ethics-l11'],
    category: 'Culture & Deep',
    scenarioBrief: 'Discuss global ethics. "Do we have a responsibility to future generations?" Use sophisticated ethical reasoning. Push for a personal ethical framework. What moral obligations do we share as humans?',
    targetGrammar: ['conditional-mixed', 'subjunctive', 'nominalization', 'discourse-markers'],
    targetVocab: ['global-ethics', 'future-generations', 'moral-framework', 'responsibility-global', 'ethics-mastery'],
    difficulty: 'practice',
  },
  {
    id: 'wisdom-l12',
    title: 'Ancient Wisdom',
    blurb: 'Discuss timeless wisdom from ancient philosophies.',
    level: 12, spiralGroup: 'abstract', spiralOrder: 3,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief: 'Explore ancient wisdom traditions. Discuss Stoicism, Buddhism, Taoism, or other philosophies. Use reported speech for ancient teachings. Push for personal application. What ancient wisdom speaks to them?',
    targetGrammar: ['reported-speech', 'nominalization', 'discourse-markers', 'conditional-mixed'],
    targetVocab: ['stoicism', 'buddhism', 'taoism', 'ancient-wisdom', 'philosophy-applied'],
    difficulty: 'core',
  },

  // ── Expression ─────────────────────────────────────────────────────────
  {
    id: 'idioms-l12',
    title: 'Native Expression',
    blurb: 'Master native-level idiomatic expression in any context.',
    level: 12, spiralGroup: 'idioms', spiralOrder: 4,
    prerequisites: ['idioms-l10'],
    category: 'Expression',
    scenarioBrief: 'Weave 6-8 advanced idioms naturally. "The proof is in the pudding", "put all your eggs in one basket", "the best of both worlds", "a blessing in disguise". Full native integration. Encourage spontaneous use.',
    targetGrammar: ['idiomatic-expressions', 'phrasal-verbs-mastery', 'colloquial-mastery', 'discourse-markers'],
    targetVocab: ['idioms-mastery', 'expressions-native', 'colloquial-native', 'figurative-mastery'],
    difficulty: 'core',
  },
  {
    id: 'register-l12',
    title: 'Code-Switching Mastery',
    blurb: 'Master seamless code-switching between registers.',
    level: 12, spiralGroup: 'register', spiralOrder: 5,
    prerequisites: ['register-l11'],
    category: 'Expression',
    scenarioBrief: 'Practice seamless code-switching. Start formal academic discussion, shift to casual banter, then emotional intimacy, then professional, then poetic. Coach on natural transitions. Ultimate register control.',
    targetGrammar: ['register-mastery', 'formal-informal-seamless', 'discourse-markers', 'modal-politeness'],
    targetVocab: ['code-switching', 'register-mastery', 'tone-perfect', 'appropriateness-mastery'],
    difficulty: 'challenge',
  },
  {
    id: 'humor-l12',
    title: 'Comic Timing',
    blurb: 'Master the art of comic timing and delivery.',
    level: 12, spiralGroup: 'humor', spiralOrder: 4,
    prerequisites: ['humor-l11'],
    category: 'Expression',
    scenarioBrief: 'Master comic timing. Tell a joke or funny story with perfect pacing, pause, and punchline. Coach on delivery techniques — deadpan, exaggeration, misdirection, callback. Think stand-up comedian.',
    targetGrammar: ['emphasis', 'discourse-markers', 'rhetorical-devices', 'inversion'],
    targetVocab: ['comic-timing', 'delivery', 'pacing', 'punchline', 'callback'],
    difficulty: 'practice',
  },
  {
    id: 'figurative-l12',
    title: 'Poetic Mastery',
    blurb: 'Create original poetry or poetic prose spontaneously.',
    level: 12, spiralGroup: 'figurative', spiralOrder: 4,
    prerequisites: ['figurative-l11'],
    category: 'Expression',
    scenarioBrief: 'Create original poetry or poetic prose on a given theme. Use all poetic devices — metaphor, simile, alliteration, assonance, rhythm. Coach on poetic craft. Think spoken word artist. Creative and expressive.',
    targetGrammar: ['figurative-language', 'inversion', 'emphasis', 'cleft-sentences', 'wordplay-advanced'],
    targetVocab: ['poetry-mastery', 'verse', 'rhythm', 'sound-devices', 'poetic-craft'],
    difficulty: 'challenge',
  },
  {
    id: 'sarcasm-l12',
    title: 'Verbal Fencing',
    blurb: 'Master witty repartee and verbal sparring.',
    level: 12, spiralGroup: 'register', spiralOrder: 5,
    prerequisites: ['sarcasm-l11'],
    category: 'Expression',
    scenarioBrief: 'Practice witty verbal sparring. Quick responses, clever comebacks, playful teasing, intellectual banter. Coach on timing and tone. Think Oscar Wilde or Shakespearean wit. Fun and sophisticated.',
    targetGrammar: ['emphasis', 'inversion', 'discourse-markers', 'figurative-language', 'wordplay-advanced'],
    targetVocab: ['repartee', 'banter', 'wit-mastery', 'comeback', 'verbal-fencing'],
    difficulty: 'practice',
  },
]
