/**
 * Cultural scenario seeds for Levantine Arabic (ar-LB)
 * Covers cafés, mezze culture, neighborhood life, celebrations, and social customs.
 */
import type { ConversationSeed } from '../types'

export const arLBCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'ar-lb-food-l01',
    title: 'Manouche Morning',
    blurb: 'Order a fresh manouche from the neighborhood bakery',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'Early morning at the furn. The baker pulls fresh manouche from the oven. You order zaatar and cheese, and chat briefly about the day ahead.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['manouche', 'zaatar', 'jibneh', 'furn', 'sabah'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'food', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-social-l01',
    title: 'Ahwe in the Hara',
    blurb: 'Greet neighbors at the local coffee shop',
    level: 1,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You sit at the neighborhood ahwe where the owner knows everyone. You exchange greetings with regulars and order a small Turkish coffee.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['ahwe', 'marhaba', 'hara', 'finjan', 'sahteen'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'social', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-market-l02',
    title: 'Souk el Tayeb Shopping',
    blurb: 'Browse a farmers market for fresh produce and specialties',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'At Souk el Tayeb, small producers sell olives, labneh, and honey. You taste samples and ask about the origin of each product.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['souk', 'zaytoun', 'labneh', '3asal', 'baladi'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'market', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-food-l03',
    title: 'Mezze Spread',
    blurb: 'Share a mezze meal and discuss favorite dishes',
    level: 3,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['ar-lb-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'Friends gather for a long lunch with dozens of mezze plates. You pass dishes, comment on flavors, and debate which hummus recipe is best.',
    targetGrammar: ['comparatives', 'like-gerund'],
    targetVocab: ['mezze', 'hummus', 'tabbouleh', 'fattoush', 'kibbeh'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'food', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-family-l04',
    title: 'Sunday Family Lunch',
    blurb: 'Gather with extended family for the weekly lunch tradition',
    level: 4,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'Every Sunday, the family meets at teta\'s house. The table is full of stuffed grape leaves, grilled meat, and arak. Conversations are loud and warm.',
    targetGrammar: ['present-continuous', 'have-has'],
    targetVocab: ['teta', 'wara2-3inab', 'arak', 'ahad', '3eile'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'family', dialectConstraint: 'ar-LB' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'ar-lb-celebration-l05',
    title: 'Eid Morning Visits',
    blurb: 'Visit neighbors and exchange Eid greetings',
    level: 5,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'On Eid morning, you make the rounds visiting neighbors. Each home offers sweets and coffee. You exchange warm wishes and catch up on family news.',
    targetGrammar: ['present-perfect', 'future-going-to'],
    targetVocab: ['3id', 'mabrouk', 'maamoul', 'ziyara', 'jiran'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'celebration', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-social-l06',
    title: 'Hamra Café Culture',
    blurb: 'Discuss art and politics at a Beirut café',
    level: 6,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['ar-lb-social-l01'],
    category: 'Social',
    scenarioBrief:
      'At a Hamra Street café, friends gather to discuss the latest art exhibition and local news. You share your perspective over a leisurely coffee.',
    targetGrammar: ['present-perfect', 'connectors'],
    targetVocab: ['maqha', 'fann', 'ma3rad', 'ra2y', 'naqqash'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'social', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-food-l07',
    title: 'Preparing Kibbeh Nayyeh',
    blurb: 'Learn to prepare traditional raw kibbeh with family',
    level: 7,
    spiralGroup: 'food-culture',
    spiralOrder: 3,
    prerequisites: ['ar-lb-food-l03'],
    category: 'Daily Life',
    scenarioBrief:
      'Your aunt teaches you to prepare kibbeh nayyeh — pounding the meat, mixing the bulgur, and getting the spice balance right. She shares family secrets.',
    targetGrammar: ['modals-should', 'conditional-first'],
    targetVocab: ['kibbeh', 'lahmeh', 'burghol', 'daqq', 'baharat'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'food', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-business-l07',
    title: 'Design Studio Meeting',
    blurb: 'Discuss a creative project at a Beirut design studio',
    level: 7,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'At a small design studio in Mar Mikhael, the team discusses a branding project for a local restaurant. You pitch creative ideas mixing Arabic calligraphy with modern design.',
    targetGrammar: ['conditional-first', 'gerunds'],
    targetVocab: ['tasmeem', 'mashrou3', 'fikra', 'khatt', 'ibda3'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'business', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-social-l08',
    title: 'Dabke at a Wedding',
    blurb: 'Join the dabke dance and discuss traditions',
    level: 8,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['ar-lb-celebration-l05'],
    category: 'Social',
    scenarioBrief:
      'At a cousin\'s wedding in the village, the dabke line forms. You join in, learn steps from an expert, and discuss how each region has its own style.',
    targetGrammar: ['present-perfect-continuous', 'comparatives'],
    targetVocab: ['dabke', '3irs', 'lawwih', 'tabla', 'raqis'],
    difficulty: 'challenge',
    culturalContext: { region: 'LB', category: 'celebration', dialectConstraint: 'ar-LB' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'ar-lb-social-l09',
    title: 'Literary Salon Discussion',
    blurb: 'Participate in a Beirut literary salon debate',
    level: 9,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'At a literary salon in Gemmayzeh, writers discuss contemporary Arabic literature. You share views on diaspora writing and the role of language in identity.',
    targetGrammar: ['discourse-markers', 'hedging'],
    targetVocab: ['adab', 'riwaya', 'shi3r', 'mahjar', 'hawiya'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'social', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-business-l10',
    title: 'NGO Community Project',
    blurb: 'Plan a community project with an NGO team',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 2,
    prerequisites: ['ar-lb-business-l07'],
    category: 'Work & Study',
    scenarioBrief:
      'You work with an NGO team to plan a neighborhood revitalization project. The discussion covers budgets, community needs, and local partnerships.',
    targetGrammar: ['passive-present', 'conditional-second'],
    targetVocab: ['mujtama3', 'mashrou3', 'tamweel', 'sharakeh', 'ihtiyajat'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'business', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-culture-l10',
    title: 'Fairuz and Lebanese Identity',
    blurb: 'Discuss Fairuz\'s legacy and her role in national identity',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 2,
    prerequisites: ['ar-lb-social-l09'],
    category: 'Culture & Deep',
    scenarioBrief:
      'Friends debate why Fairuz transcends political divisions. You discuss how her music became a morning ritual and a symbol of Lebanese resilience.',
    targetGrammar: ['subjunctive', 'nominalization'],
    targetVocab: ['Fairuz', 'musiqa', 'watan', 'sumoud', 'turath'],
    difficulty: 'challenge',
    culturalContext: { region: 'LB', category: 'social', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-family-l11',
    title: 'Diaspora and Belonging',
    blurb: 'Discuss emigration and identity with family members',
    level: 11,
    spiralGroup: 'family-culture',
    spiralOrder: 2,
    prerequisites: ['ar-lb-family-l04'],
    category: 'Ideas & Stories',
    scenarioBrief:
      'A cousin returns from abroad for a visit. Over dinner, the family discusses immigration, nostalgia, and what it means to be Lebanese from far away.',
    targetGrammar: ['reported-speech', 'conditional-mixed'],
    targetVocab: ['ghurba', 'ightrab', 'watan', 'haneen', '3awda'],
    difficulty: 'core',
    culturalContext: { region: 'LB', category: 'family', dialectConstraint: 'ar-LB' },
  },
  {
    id: 'ar-lb-celebration-l12',
    title: 'Mountain Village Traditions',
    blurb: 'Discuss endangered mountain traditions and preservation',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 3,
    prerequisites: ['ar-lb-social-l08'],
    category: 'Culture & Deep',
    scenarioBrief:
      'In a Mount Lebanon village, elders discuss how traditions are fading. You engage in complex debate about cultural preservation, authenticity, and modernization.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['day3a', 'jabal', 'taqaleed', 'hifaz', 'asala'],
    difficulty: 'challenge',
    culturalContext: { region: 'LB', category: 'celebration', dialectConstraint: 'ar-LB' },
  },
]
