/**
 * Cultural scenario seeds for Persian/Farsi (Iran)
 * Covers Nowruz, tea houses, poetry, bazaars, and social customs.
 */
import type { ConversationSeed } from '../types'

export const faCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'fa-food-l01',
    title: 'Tea at a Chaikhane',
    blurb: 'Order tea and sweets at a traditional tea house',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You enter a quiet chaikhane in Isfahan. The owner welcomes you and offers a menu of teas and pastries. You make your choice politely.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['chai', 'chaikhane', 'ghand', 'shirini', 'befarmayid'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'food' },
  },
  {
    id: 'fa-social-l01',
    title: 'Taarof Greetings',
    blurb: 'Practice polite greetings using taarof customs',
    level: 1,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You meet a neighbor on the street. They insist you come in for tea — you politely decline, they insist again, following the taarof dance of courtesy.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['salam', 'taarof', 'befarmayid', 'khahesh', 'lotf'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'social' },
  },
  {
    id: 'fa-market-l02',
    title: 'Grand Bazaar Shopping',
    blurb: 'Ask about prices and quality in a bustling bazaar',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You wander through the grand bazaar of Tehran looking for saffron and pistachios. Merchants display their goods and you inquire about freshness and price.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['bazaar', 'zaferan', 'peste', 'gheymat', 'tazeh'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'market' },
  },
  {
    id: 'fa-family-l03',
    title: 'Family Dinner Conversation',
    blurb: 'Chat with family over a home-cooked Persian meal',
    level: 3,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'Your aunt has prepared ghormeh sabzi and rice. The family sits together, passing dishes and catching up on the week. You compliment the food and share your news.',
    targetGrammar: ['past-simple', 'adjectives-basic'],
    targetVocab: ['ghormeh-sabzi', 'berenj', 'sofreh', 'noush-e-jan', 'khoshmazeh'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'family' },
  },
  {
    id: 'fa-celebration-l04',
    title: 'Nowruz Haft-Sin Setup',
    blurb: 'Help set up the traditional Nowruz table',
    level: 4,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'It is the days before Nowruz. Your family sets up the Haft-Sin table together, discussing the meaning of each item and sharing memories of past new years.',
    targetGrammar: ['present-continuous', 'there-is-are'],
    targetVocab: ['Nowruz', 'haft-sin', 'sabzeh', 'senjed', 'sombol'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'celebration' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'fa-social-l05',
    title: 'Poetry Night with Friends',
    blurb: 'Recite and discuss Hafez poetry with friends',
    level: 5,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'Friends gather for a Faal-e Hafez session. Someone opens the book at random and reads a verse. The group discusses its interpretation and relevance to their lives.',
    targetGrammar: ['present-perfect', 'connectors'],
    targetVocab: ['Hafez', 'ghazal', 'faal', 'sher', 'maani'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'social' },
  },
  {
    id: 'fa-food-l06',
    title: 'Cooking Tahdig Together',
    blurb: 'Learn to make perfect tahdig with an experienced cook',
    level: 6,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['fa-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'Your grandmother teaches you her tahdig technique. She explains the timing, oil amount, and heat level while you attempt to replicate her golden crust.',
    targetGrammar: ['imperatives', 'modals-should'],
    targetVocab: ['tahdig', 'roghan', 'deeg', 'barge', 'dame'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'food' },
  },
  {
    id: 'fa-business-l07',
    title: 'Carpet Shop Negotiation',
    blurb: 'Negotiate a carpet purchase with an experienced merchant',
    level: 7,
    spiralGroup: 'market-culture',
    spiralOrder: 2,
    prerequisites: ['fa-market-l02'],
    category: 'Daily Life',
    scenarioBrief:
      'In a carpet shop, the merchant unfurls handwoven pieces and explains their origins. You discuss quality, patterns, and negotiate a fair price with mutual respect.',
    targetGrammar: ['conditional-first', 'comparatives'],
    targetVocab: ['farsh', 'ghali', 'dastbaf', 'tarh', 'abrisham'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'market' },
  },
  {
    id: 'fa-celebration-l07',
    title: 'Chahar-Shanbe Suri Night',
    blurb: 'Celebrate the fire-jumping festival with neighbors',
    level: 7,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['fa-celebration-l04'],
    category: 'Culture & Deep',
    scenarioBrief:
      'On Chahar-Shanbe Suri eve, neighbors gather around bonfires. You jump over flames chanting the traditional phrase and share food with those celebrating nearby.',
    targetGrammar: ['past-continuous', 'gerunds'],
    targetVocab: ['atash', 'chahar-shanbe-suri', 'ajil', 'zardi', 'sorkhi'],
    difficulty: 'practice',
    culturalContext: { region: 'IR', category: 'celebration' },
  },
  {
    id: 'fa-family-l08',
    title: 'Sizdah Bedar Picnic',
    blurb: 'Spend the 13th day of Nowruz outdoors with extended family',
    level: 8,
    spiralGroup: 'family-culture',
    spiralOrder: 2,
    prerequisites: ['fa-family-l03'],
    category: 'Social',
    scenarioBrief:
      'On Sizdah Bedar, the whole family heads to the park. Aunts set up elaborate picnics, uncles play backgammon, and cousins tie grass knots for wishes.',
    targetGrammar: ['present-perfect-continuous', 'relative-clauses'],
    targetVocab: ['sizdah-bedar', 'sabzeh', 'park', 'takhteh-nard', 'doaa'],
    difficulty: 'challenge',
    culturalContext: { region: 'IR', category: 'family' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'fa-social-l09',
    title: 'Philosophical Debate on Fate',
    blurb: 'Discuss concepts of destiny and free will in Persian thought',
    level: 9,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'Over tea, a friend raises the concept of taqdeer versus free will. You explore the philosophical traditions of Rumi and Khayyam, debating gently.',
    targetGrammar: ['hedging', 'discourse-markers'],
    targetVocab: ['taqdeer', 'eradeh', 'falsafeh', 'hasti', 'marg'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'social' },
  },
  {
    id: 'fa-business-l10',
    title: 'Import-Export Meeting',
    blurb: 'Discuss trade logistics with a business partner',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'You meet with a trade partner to discuss importing dried fruits. Topics include shipping timelines, tariffs, and quality standards — all conducted with formal Persian courtesy.',
    targetGrammar: ['passive-present', 'conditional-second'],
    targetVocab: ['saderat', 'varedat', 'gomrok', 'keyfiat', 'gharardad'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'business' },
  },
  {
    id: 'fa-culture-l10',
    title: 'Rumi Interpretation Circle',
    blurb: 'Lead a deep discussion on Rumi\'s Masnavi verses',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 2,
    prerequisites: ['fa-social-l05'],
    category: 'Culture & Deep',
    scenarioBrief:
      'In a literary circle, members take turns interpreting passages from the Masnavi. You present your reading of a complex allegory about spiritual transformation.',
    targetGrammar: ['subjunctive', 'inversion'],
    targetVocab: ['Masnavi', 'erfan', 'tamsal', 'rooh', 'seyr-o-soluk'],
    difficulty: 'challenge',
    culturalContext: { region: 'IR', category: 'social' },
  },
  {
    id: 'fa-social-l11',
    title: 'Generational Perspectives',
    blurb: 'Navigate a conversation between generations about tradition',
    level: 11,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['fa-social-l09'],
    category: 'Ideas & Stories',
    scenarioBrief:
      'At a family dinner, older relatives discuss how traditions have changed. Younger members share different perspectives. You mediate between viewpoints thoughtfully.',
    targetGrammar: ['reported-speech', 'conditional-mixed'],
    targetVocab: ['sonnat', 'nasl', 'tagheer', 'arzesh', 'tajrobeh'],
    difficulty: 'core',
    culturalContext: { region: 'IR', category: 'family' },
  },
  {
    id: 'fa-celebration-l12',
    title: 'Yalda Night Storytelling',
    blurb: 'Tell and discuss stories on the longest night of the year',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 3,
    prerequisites: ['fa-celebration-l07'],
    category: 'Culture & Deep',
    scenarioBrief:
      'On Shab-e Yalda, the family gathers with pomegranates and poetry. Elders tell ancient stories while you weave in complex narrative structures and metaphors.',
    targetGrammar: ['cleft-sentences', 'nominalization'],
    targetVocab: ['Yalda', 'anar', 'gheseh', 'Shahnameh', 'ostooreh'],
    difficulty: 'challenge',
    culturalContext: { region: 'IR', category: 'celebration' },
  },
]
