/**
 * Cultural scenario seeds for Punjabi (India/Pakistan)
 * Covers dhabas, weddings, farm life, festivals, and community.
 */
import type { ConversationSeed } from '../types'

export const paCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'pa-food-l01',
    title: 'Lassi at the Dhaba',
    blurb: 'Order lassi and paranthas at a highway dhaba',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You stop at a highway dhaba known for its thick lassi and stuffed paranthas. The owner greets you loudly and asks what you want to eat.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['lassi', 'parantha', 'dhaba', 'makhan', 'dahi'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'food' },
  },
  {
    id: 'pa-family-l01',
    title: 'Morning with Biji',
    blurb: 'Greet your grandmother and help with morning chores',
    level: 1,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'Early morning at the family home. Biji is already up making chai. You greet her respectfully and she asks if you slept well.',
    targetGrammar: ['present-simple', 'questions-yesno'],
    targetVocab: ['sat-sri-akal', 'biji', 'chai', 'neend', 'subah'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
  },
  {
    id: 'pa-market-l02',
    title: 'Mandi Sabzi Shopping',
    blurb: 'Buy fresh vegetables at the local mandi',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You go to the sabzi mandi with your mother. Vendors call out prices for fresh produce. You help pick vegetables and negotiate a better rate.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['mandi', 'sabzi', 'aaloo', 'bhaji', 'mol'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'market' },
  },
  {
    id: 'pa-social-l03',
    title: 'Gurdwara Visit',
    blurb: 'Visit the gurdwara and interact with the community',
    level: 3,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'You visit the local gurdwara for Sunday prayers. After the kirtan, you sit in the langar hall and share a meal with the sangat.',
    targetGrammar: ['present-continuous', 'prepositions-place'],
    targetVocab: ['gurdwara', 'langar', 'sangat', 'kirtan', 'ardas'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
  },
  {
    id: 'pa-social-l04',
    title: 'Cricket in the Gali',
    blurb: 'Organize a street cricket match with neighborhood friends',
    level: 4,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['pa-social-l03'],
    category: 'Social',
    scenarioBrief:
      'Afternoon in the gali, friends gather for cricket. You pick teams, argue about rules, and celebrate boundaries hit over parked cars.',
    targetGrammar: ['future-going-to', 'modals-can'],
    targetVocab: ['cricket', 'gali', 'batting', 'wicket', 'team'],
    difficulty: 'practice',
    culturalContext: { region: 'IN', category: 'social' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'pa-celebration-l05',
    title: 'Lohri Bonfire Night',
    blurb: 'Celebrate Lohri festival with songs around the bonfire',
    level: 5,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'The neighborhood gathers around a bonfire for Lohri. People throw rewri and popcorn into the fire, sing traditional songs, and congratulate new parents.',
    targetGrammar: ['present-perfect', 'conjunctions'],
    targetVocab: ['Lohri', 'agg', 'rewri', 'moongphali', 'gidda'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
  },
  {
    id: 'pa-food-l06',
    title: 'Amritsari Kulcha Stop',
    blurb: 'Enjoy Amritsari kulcha and discuss food traditions',
    level: 6,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['pa-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'At a famous Amritsari kulcha shop, you order chole kulche. The owner shares how his family has run the shop for generations. You discuss regional food pride.',
    targetGrammar: ['present-perfect', 'past-simple'],
    targetVocab: ['kulcha', 'chole', 'tandoor', 'purana', 'swad'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'food' },
  },
  {
    id: 'pa-family-l07',
    title: 'Wedding Sangeet Night',
    blurb: 'Participate in sangeet preparations and dancing',
    level: 7,
    spiralGroup: 'family-culture',
    spiralOrder: 2,
    prerequisites: ['pa-family-l01'],
    category: 'Social',
    scenarioBrief:
      'The sangeet night is approaching. Family members rehearse dance numbers, argue about song choices, and tease the bride and groom.',
    targetGrammar: ['modals-should', 'conditional-first'],
    targetVocab: ['sangeet', 'bhangra', 'gidda', 'gaana', 'viah'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'celebration' },
  },
  {
    id: 'pa-business-l07',
    title: 'Farm Harvest Discussion',
    blurb: 'Discuss crop prices and harvest with neighboring farmers',
    level: 7,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'Harvest season arrives and farmers gather at the arhtiya. You discuss wheat prices, weather impact, and whether to hold stock or sell immediately.',
    targetGrammar: ['conditional-first', 'comparatives'],
    targetVocab: ['fasal', 'kanak', 'arhtiya', 'bhaa', 'mausam'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'business' },
  },
  {
    id: 'pa-celebration-l08',
    title: 'Vaisakhi Mela',
    blurb: 'Enjoy the Vaisakhi fair with competitions and food',
    level: 8,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['pa-celebration-l05'],
    category: 'Culture & Deep',
    scenarioBrief:
      'At the Vaisakhi mela, there are wrestling matches, bhangra competitions, and food stalls everywhere. You navigate the crowd and cheer competitors.',
    targetGrammar: ['present-perfect-continuous', 'gerunds'],
    targetVocab: ['Vaisakhi', 'mela', 'kushti', 'pehlwan', 'jhoomer'],
    difficulty: 'challenge',
    culturalContext: { region: 'IN', category: 'celebration' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'pa-social-l09',
    title: 'Panchayat Debate',
    blurb: 'Participate in a village panchayat discussion',
    level: 9,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'The village panchayat convenes to settle a land dispute. Elders speak in turns. You present your perspective using respectful but firm language.',
    targetGrammar: ['discourse-markers', 'hedging'],
    targetVocab: ['panchayat', 'sarpanch', 'zameen', 'faisla', 'insaaf'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'social' },
  },
  {
    id: 'pa-business-l10',
    title: 'Transport Business Expansion',
    blurb: 'Discuss expanding a family transport business',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 2,
    prerequisites: ['pa-business-l07'],
    category: 'Work & Study',
    scenarioBrief:
      'Your family runs trucks on the GT Road. You propose buying a new vehicle and discuss routes, financing, and competition with your father.',
    targetGrammar: ['conditional-second', 'passive-present'],
    targetVocab: ['truck', 'sadak', 'karja', 'route', 'karobar'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'business' },
  },
  {
    id: 'pa-culture-l10',
    title: 'Waris Shah Poetry Night',
    blurb: 'Discuss Heer Ranjha and Punjabi literary tradition',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'At a literary gathering, someone recites from Waris Shah. The group discusses themes of love, rebellion, and social commentary in Punjabi poetry.',
    targetGrammar: ['subjunctive', 'relative-clauses'],
    targetVocab: ['Heer', 'qissa', 'ishq', 'kavita', 'virodh'],
    difficulty: 'challenge',
    culturalContext: { region: 'IN', category: 'social' },
  },
  {
    id: 'pa-family-l11',
    title: 'Joint Family Decisions',
    blurb: 'Navigate a complex family decision about education',
    level: 11,
    spiralGroup: 'family-culture',
    spiralOrder: 3,
    prerequisites: ['pa-family-l07'],
    category: 'Social',
    scenarioBrief:
      'Your younger sibling wants to study abroad. The joint family has differing opinions about sending them so far. You mediate between modern aspirations and tradition.',
    targetGrammar: ['reported-speech', 'conditional-mixed'],
    targetVocab: ['parhai', 'bahar', 'parivar', 'faisla', 'bhavishya'],
    difficulty: 'core',
    culturalContext: { region: 'IN', category: 'family' },
  },
  {
    id: 'pa-celebration-l12',
    title: 'Sikh Heritage and Identity',
    blurb: 'Discuss Sikh history and its relevance today',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 3,
    prerequisites: ['pa-celebration-l08'],
    category: 'Ideas & Stories',
    scenarioBrief:
      'On Gurpurab, elders discuss Guru Nanak\'s teachings and how Sikh values of equality and service apply to modern challenges. You engage with complex philosophical ideas.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['Gurpurab', 'Guru', 'sewa', 'barabari', 'khalsa'],
    difficulty: 'challenge',
    culturalContext: { region: 'IN', category: 'celebration' },
  },
]
