/**
 * Cultural scenario seeds for Brazilian Portuguese (Brazil)
 * Covers churrascaria, carnaval, lanchonete, beach culture, and music.
 */
import type { ConversationSeed } from '../types'

export const ptBRCulturalSeeds: ConversationSeed[] = [
  // ── Beginner (Levels 1–4) ─────────────────────────────────────────────────
  {
    id: 'pt-br-food-l01',
    title: 'Lanchonete Lunch',
    blurb: 'Order a prato feito at a neighborhood lanchonete',
    level: 1,
    spiralGroup: 'food-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'You walk into a bustling lanchonete for lunch. The attendant points to the daily specials written on a board. You order a prato feito with rice, beans, and meat.',
    targetGrammar: ['present-simple-to-be', 'imperatives'],
    targetVocab: ['lanchonete', 'prato-feito', 'arroz', 'feijao', 'suco'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'food' },
  },
  {
    id: 'pt-br-social-l02',
    title: 'Beach Day at Copacabana',
    blurb: 'Chat with locals while enjoying the beach',
    level: 2,
    spiralGroup: 'social-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'You spend a Sunday at Copacabana beach. A vendor walks by selling mate and biscoito. You chat with a friendly local about the waves and weather.',
    targetGrammar: ['present-simple', 'adjectives-basic'],
    targetVocab: ['praia', 'mate', 'biscoito', 'onda', 'sol'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'social' },
  },
  {
    id: 'pt-br-market-l02',
    title: 'Feira Livre Shopping',
    blurb: 'Buy fresh produce at an open-air farmers market',
    level: 2,
    spiralGroup: 'market-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Daily Life',
    scenarioBrief:
      'Saturday morning at the feira livre. Farmers shout out deals on tropical fruits. You ask about prices for mango, papaya, and passion fruit.',
    targetGrammar: ['questions-wh', 'numbers-time'],
    targetVocab: ['feira', 'manga', 'mamao', 'maracuja', 'quilo'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'market' },
  },
  {
    id: 'pt-br-social-l03',
    title: 'Futebol Pelada',
    blurb: 'Join a casual football game at the local campo',
    level: 3,
    spiralGroup: 'social-culture',
    spiralOrder: 2,
    prerequisites: ['pt-br-social-l02'],
    category: 'Social',
    scenarioBrief:
      'Friends gather for a pelada on Sunday. You are invited to play and join in the banter about skills, fouls, and which team needs more players.',
    targetGrammar: ['present-continuous', 'modals-can'],
    targetVocab: ['pelada', 'gol', 'time', 'campo', 'bola'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'social' },
  },
  {
    id: 'pt-br-food-l04',
    title: 'Churrascaria Experience',
    blurb: 'Navigate a rodizio-style churrascaria dinner',
    level: 4,
    spiralGroup: 'food-culture',
    spiralOrder: 2,
    prerequisites: ['pt-br-food-l01'],
    category: 'Daily Life',
    scenarioBrief:
      'At a churrascaria, waiters circulate with skewers of meat. You use the green/red card system and discuss cuts with the passador while enjoying the salad bar.',
    targetGrammar: ['quantifiers', 'like-gerund'],
    targetVocab: ['churrasco', 'picanha', 'rodizio', 'passador', 'cartao'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'food' },
  },

  // ── Intermediate (Levels 5–8) ─────────────────────────────────────────────
  {
    id: 'pt-br-celebration-l05',
    title: 'Carnaval Bloco',
    blurb: 'Join a street bloco during Carnaval season',
    level: 5,
    spiralGroup: 'celebration-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'You follow a bloco through the streets during Carnaval. Friends explain the samba rhythm, the fantasia theme, and where the group is heading next.',
    targetGrammar: ['present-perfect', 'future-going-to'],
    targetVocab: ['bloco', 'samba', 'fantasia', 'marchinha', 'confete'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'celebration' },
  },
  {
    id: 'pt-br-social-l06',
    title: 'Boteco Happy Hour',
    blurb: 'Enjoy petiscos and conversation at a neighborhood bar',
    level: 6,
    spiralGroup: 'social-culture',
    spiralOrder: 3,
    prerequisites: ['pt-br-social-l03'],
    category: 'Social',
    scenarioBrief:
      'After work, friends gather at the boteco for chopp and pasteis. The conversation flows between weekend plans, novela episodes, and football results.',
    targetGrammar: ['past-simple', 'connectors'],
    targetVocab: ['boteco', 'chopp', 'pastel', 'petisco', 'conta'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'social' },
  },
  {
    id: 'pt-br-business-l07',
    title: 'Startup Pitch in Sao Paulo',
    blurb: 'Present a business idea at a co-working space',
    level: 7,
    spiralGroup: 'business-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Work & Study',
    scenarioBrief:
      'At a Sao Paulo co-working space, you pitch your app idea to potential investors. The conversation mixes Portuguese business language with English tech terms.',
    targetGrammar: ['conditional-first', 'modals-should'],
    targetVocab: ['startup', 'investidor', 'app', 'mercado', 'faturamento'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'business' },
  },
  {
    id: 'pt-br-celebration-l07',
    title: 'Festa Junina Night',
    blurb: 'Enjoy a traditional June festival with dancing and food',
    level: 7,
    spiralGroup: 'celebration-culture',
    spiralOrder: 2,
    prerequisites: ['pt-br-celebration-l05'],
    category: 'Culture & Deep',
    scenarioBrief:
      'At the neighborhood festa junina, there is forró dancing, quadrilha, and stands selling canjica and quentão. You participate in the festivities.',
    targetGrammar: ['past-continuous', 'gerunds'],
    targetVocab: ['festa-junina', 'forro', 'quadrilha', 'canjica', 'quentao'],
    difficulty: 'practice',
    culturalContext: { region: 'BR', category: 'celebration' },
  },
  {
    id: 'pt-br-family-l08',
    title: 'Sunday Almoço de Família',
    blurb: 'Participate in a big family Sunday lunch gathering',
    level: 8,
    spiralGroup: 'family-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Social',
    scenarioBrief:
      'Every Sunday, the extended family gathers at grandma\'s house for feijoada. Conversations overlap — politics, gossip, weekend plans — all while plates are passed around.',
    targetGrammar: ['present-perfect-continuous', 'relative-clauses'],
    targetVocab: ['feijoada', 'familia', 'almoco', 'vovo', 'sobremesa'],
    difficulty: 'challenge',
    culturalContext: { region: 'BR', category: 'family' },
  },

  // ── Advanced (Levels 9–12) ────────────────────────────────────────────────
  {
    id: 'pt-br-social-l09',
    title: 'Samba de Roda Circle',
    blurb: 'Discuss samba heritage and its African roots',
    level: 9,
    spiralGroup: 'arts-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Culture & Deep',
    scenarioBrief:
      'At a community samba de roda, musicians discuss the African origins of samba, the role of music in resistance, and how traditions evolve in modern Brazil.',
    targetGrammar: ['discourse-markers', 'hedging'],
    targetVocab: ['samba', 'roda', 'ancestralidade', 'resistencia', 'raiz'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'social' },
  },
  {
    id: 'pt-br-business-l10',
    title: 'Sustainability Project Proposal',
    blurb: 'Present an Amazon sustainability initiative to stakeholders',
    level: 10,
    spiralGroup: 'business-culture',
    spiralOrder: 2,
    prerequisites: ['pt-br-business-l07'],
    category: 'Work & Study',
    scenarioBrief:
      'You present a reforestation project to NGO partners and local communities. The discussion involves environmental data, indigenous rights, and funding models.',
    targetGrammar: ['passive-present', 'conditional-second'],
    targetVocab: ['sustentabilidade', 'reflorestamento', 'comunidade', 'recurso', 'parceria'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'business' },
  },
  {
    id: 'pt-br-culture-l10',
    title: 'Capoeira Philosophy',
    blurb: 'Discuss the philosophy and history of capoeira',
    level: 10,
    spiralGroup: 'arts-culture',
    spiralOrder: 2,
    prerequisites: ['pt-br-social-l09'],
    category: 'Ideas & Stories',
    scenarioBrief:
      'After a capoeira roda, the mestre discusses mandinga, the spiritual side of capoeira, and how the art form preserves Afro-Brazilian identity.',
    targetGrammar: ['subjunctive', 'nominalization'],
    targetVocab: ['capoeira', 'mandinga', 'mestre', 'ginga', 'axe'],
    difficulty: 'challenge',
    culturalContext: { region: 'BR', category: 'social' },
  },
  {
    id: 'pt-br-social-l11',
    title: 'Regional Identity Debate',
    blurb: 'Discuss cultural differences between Brazilian regions',
    level: 11,
    spiralGroup: 'discourse-culture',
    spiralOrder: 1,
    prerequisites: [],
    category: 'Ideas & Stories',
    scenarioBrief:
      'Friends from different states discuss regional stereotypes, food traditions, and accents. The conversation navigates identity with humor and depth.',
    targetGrammar: ['reported-speech', 'conditional-mixed'],
    targetVocab: ['nordeste', 'sotaque', 'cultura', 'preconceito', 'diversidade'],
    difficulty: 'core',
    culturalContext: { region: 'BR', category: 'social' },
  },
  {
    id: 'pt-br-celebration-l12',
    title: 'Escola de Samba Enredo',
    blurb: 'Analyze the narrative and politics of a samba school theme',
    level: 12,
    spiralGroup: 'celebration-culture',
    spiralOrder: 3,
    prerequisites: ['pt-br-celebration-l07'],
    category: 'Culture & Deep',
    scenarioBrief:
      'Carnival insiders discuss this year\'s samba school enredo — its political commentary, visual symbolism, and how it challenges mainstream narratives about Brazilian history.',
    targetGrammar: ['inversion', 'cleft-sentences'],
    targetVocab: ['enredo', 'escola-de-samba', 'alegoria', 'critica', 'desfile'],
    difficulty: 'challenge',
    culturalContext: { region: 'BR', category: 'celebration' },
  },
]
