/**
 * Property test — Property 8: Single enabled-source-of-truth.
 *
 * **Validates: Requirements 3.7**
 *
 * `config`, `recommend-provider`, and `checkout` must always agree on whether a
 * provider is enabled, because all three derive enablement from the registry,
 * which delegates to each provider's `isEnabled()`. There must be no env-var
 * divergence between the three resolution surfaces.
 *
 * The three surfaces are modeled exactly as the routes resolve them:
 *  - `config`            → `providerConfig()`            ({ stripeEnabled, dodoEnabled })
 *  - `recommend-provider`→ `enabledProviders()`          (registry list membership)
 *  - `checkout`          → `getProvider(id)`             (enabled iff it does not
 *                                                          throw a not-configured error)
 *
 * Credential-presence combinations are generated by manipulating `process.env`
 * (set/unset the required vars, including the Dodo `DODOPAYMENTS_*` /
 * `DODO_PAYMENTS_*` alias spellings). Because the env proxies in
 * `src/lib/stripe/env.ts` and `src/lib/dodopayments/env.ts` cache the resolved
 * credentials on first access, each case calls `vi.resetModules()` and then
 * dynamically re-imports the registry so a fresh read of `process.env` occurs.
 */

import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest'
import * as fc from 'fast-check'

// ── Env keys touched by enablement resolution ───────────────────────────────
const STRIPE_KEYS = [
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'STRIPE_PRICE_TRIAL',
  'STRIPE_PRICE_MONTHLY',
  'STRIPE_PRICE_YEARLY',
] as const

type StripeKey = (typeof STRIPE_KEYS)[number]

// Each Dodo credential has two accepted spellings (canonical + legacy alias).
const DODO_GROUPS = [
  { field: 'apiKey', canonical: 'DODOPAYMENTS_API_KEY', alias: 'DODO_PAYMENTS_API_KEY' },
  { field: 'webhookSecret', canonical: 'DODOPAYMENTS_WEBHOOK_SECRET', alias: 'DODO_PAYMENTS_WEBHOOK_SECRET' },
  { field: 'productMonthly', canonical: 'DODOPAYMENTS_PRODUCT_MONTHLY', alias: 'DODO_PAYMENTS_PRODUCT_MONTHLY' },
  { field: 'productYearly', canonical: 'DODOPAYMENTS_PRODUCT_YEARLY', alias: 'DODO_PAYMENTS_PRODUCT_YEARLY' },
] as const

type DodoField = (typeof DODO_GROUPS)[number]['field']

const ALL_KEYS = [
  ...STRIPE_KEYS,
  ...DODO_GROUPS.flatMap((g) => [g.canonical, g.alias]),
]

// Snapshot any pre-existing env values so the real environment is restored
// after the suite (these tests fully own these keys while running).
const ORIGINAL_ENV: Record<string, string | undefined> = {}
for (const k of ALL_KEYS) ORIGINAL_ENV[k] = process.env[k]

function clearAllKeys(): void {
  for (const k of ALL_KEYS) delete process.env[k]
}

function restoreAllKeys(): void {
  for (const k of ALL_KEYS) {
    const original = ORIGINAL_ENV[k]
    if (original === undefined) delete process.env[k]
    else process.env[k] = original
  }
}

// A non-placeholder, non-empty value. The env validators reject values that are
// empty, start with `your_`, contain `xxx`, or start with `sk_test_replace`.
function validValue(key: string): string {
  return `valid_${key}_value`
}

// ── Generated credential-presence combination ───────────────────────────────
type Spelling = 'canonical' | 'alias' | 'both'

interface DodoGroupSel {
  present: boolean
  spelling: Spelling
}

interface Combo {
  stripe: Record<StripeKey, boolean>
  dodo: Record<DodoField, DodoGroupSel>
}

const stripeArb = fc.record({
  STRIPE_SECRET_KEY: fc.boolean(),
  STRIPE_WEBHOOK_SECRET: fc.boolean(),
  STRIPE_PRICE_TRIAL: fc.boolean(),
  STRIPE_PRICE_MONTHLY: fc.boolean(),
  STRIPE_PRICE_YEARLY: fc.boolean(),
}) as fc.Arbitrary<Record<StripeKey, boolean>>

const dodoGroupArb: fc.Arbitrary<DodoGroupSel> = fc.record({
  present: fc.boolean(),
  spelling: fc.constantFrom<Spelling>('canonical', 'alias', 'both'),
})

const dodoArb = fc.record({
  apiKey: dodoGroupArb,
  webhookSecret: dodoGroupArb,
  productMonthly: dodoGroupArb,
  productYearly: dodoGroupArb,
}) as fc.Arbitrary<Record<DodoField, DodoGroupSel>>

const comboArb: fc.Arbitrary<Combo> = fc.record({ stripe: stripeArb, dodo: dodoArb })

function applyCombo(combo: Combo): void {
  clearAllKeys()

  for (const key of STRIPE_KEYS) {
    if (combo.stripe[key]) process.env[key] = validValue(key)
  }

  for (const group of DODO_GROUPS) {
    const sel = combo.dodo[group.field]
    if (!sel.present) continue
    if (sel.spelling === 'canonical' || sel.spelling === 'both') {
      process.env[group.canonical] = validValue(group.canonical)
    }
    if (sel.spelling === 'alias' || sel.spelling === 'both') {
      process.env[group.alias] = validValue(group.alias)
    }
  }
}

type Enablement = { stripeEnabled: boolean; dodoEnabled: boolean }

function checkoutEnabled(
  getProvider: (id: string) => unknown,
  id: 'stripe' | 'dodopayments',
): boolean {
  try {
    getProvider(id)
    return true
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    // A "not configured" error is the registry reporting the provider disabled.
    // Any other error (e.g. unknown/invalid id) is unexpected here and should
    // surface as a test failure rather than be swallowed.
    if (/not configured/i.test(message)) return false
    throw err
  }
}

/** Resolve enablement through all three route surfaces from one source. */
async function resolveSurfaces(): Promise<{
  config: Enablement
  recommend: Enablement
  checkout: Enablement
}> {
  vi.resetModules()
  const { providerConfig, enabledProviders, getProvider } = await import(
    '@/lib/payments/registry'
  )

  // config route
  const config = providerConfig()

  // recommend-provider route (registry list membership)
  const enabledIds = enabledProviders().map((p) => p.id)
  const recommend: Enablement = {
    stripeEnabled: enabledIds.includes('stripe'),
    dodoEnabled: enabledIds.includes('dodopayments'),
  }

  // checkout route (getProvider throws "not configured" when disabled)
  const checkout: Enablement = {
    stripeEnabled: checkoutEnabled(getProvider, 'stripe'),
    dodoEnabled: checkoutEnabled(getProvider, 'dodopayments'),
  }

  return { config, recommend, checkout }
}

describe('Property 8: Single enabled-source-of-truth', () => {
  beforeEach(() => {
    clearAllKeys()
  })

  afterAll(() => {
    restoreAllKeys()
  })

  it('config, recommend-provider, and checkout always agree on provider enablement', async () => {
    /**Validates: Requirements 3.7*/
    await fc.assert(
      fc.asyncProperty(comboArb, async (combo) => {
        applyCombo(combo)
        const { config, recommend, checkout } = await resolveSurfaces()

        // All three surfaces must agree for Stripe.
        expect(recommend.stripeEnabled).toBe(config.stripeEnabled)
        expect(checkout.stripeEnabled).toBe(config.stripeEnabled)

        // All three surfaces must agree for DodoPayments.
        expect(recommend.dodoEnabled).toBe(config.dodoEnabled)
        expect(checkout.dodoEnabled).toBe(config.dodoEnabled)
      }),
      { numRuns: 200 },
    )
  })
})
