/**
 * Appwrite storage service — minimal, focused on user preferences only.
 *
 * Learning system preferences are stored in user_preferences. Profile memory
 * was removed during a simplification pass.
 *
 * This file only handles user_preferences (onboarding state, persona, languages).
 */

import { databases } from '../api/appwrite'
import { Query, Permission, Role } from 'appwrite'
import { APPWRITE_DB_ID, COLLECTION_IDS } from '../appwrite-schema'
import type {
  UserPreferences,
  PersonaId,
  TargetLanguage,
  LearningGoal,
  DialectVariant,
} from '@talkingo/shared/types'

// ─── Appwrite Configuration ──────────────────────────────────────────────────
const DATABASE_ID = APPWRITE_DB_ID
const PREFERENCES_COLLECTION = COLLECTION_IDS.USER_PREFERENCES

// ─── Retry Helper ────────────────────────────────────────────────────────────

interface RetryOptions {
  maxAttempts?: number
  baseDelayMs?: number
  label?: string
  userId?: string
}

async function withRetry<T>(
  fn: () => Promise<T>,
  options: RetryOptions = {}
): Promise<T | null> {
  const { maxAttempts = 3, baseDelayMs = 300, label = 'appwrite', userId } = options

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn()
    } catch (error: any) {
      const isLast = attempt === maxAttempts
      const statusCode = error?.code ?? error?.status ?? 0
      const isClientError = statusCode >= 400 && statusCode < 500
      if (isClientError || isLast) {
        console.error(
          `[Appwrite] ${label} failed after ${attempt} attempt(s)`,
          { userId, statusCode, error }
        )
        return null
      }
      const delay = baseDelayMs * Math.pow(3, attempt - 1)
      console.warn(
        `[Appwrite] ${label} attempt ${attempt} failed, retrying in ${delay}ms…`,
        { userId, statusCode }
      )
      await new Promise(resolve => setTimeout(resolve, delay))
    }
  }
  return null
}

// ─── User Preferences Service ────────────────────────────────────────────────

export interface UserPreferencesDoc {
  userId: string
  userName?: string
  level: 'beginner' | 'intermediate' | 'advanced'
  talkingoLevel?: number
  topic: string
  correctionStyle: 'direct' | 'silent'
  persona: PersonaId
  targetLanguage?: TargetLanguage
  nativeLanguage?: string
  learningGoal?: LearningGoal
  onboardingComplete?: boolean
  currentUnitId?: string
  preferredScript?: 'native' | 'latin' | 'both'
  learnerGender?: 'masculine' | 'feminine'
  dialect?: DialectVariant
  heritageMode?: boolean
  uiLanguage?: string
  createdAt: number
  updatedAt: number
  /** Cross-session AI memory paragraph — auto-generated by Gemini. */
  memoryLifeline?: string
  /** User-written note (~500 chars max). */
  userNote?: string
}

function ownerPermissions(userId: string): string[] {
  return [
    Permission.read(Role.user(userId)),
    Permission.update(Role.user(userId)),
    Permission.delete(Role.user(userId)),
  ]
}

function docIdForUser(userId: string): string {
  return userId
}

export async function saveUserPreferences(
  userId: string,
  preferences: UserPreferences
): Promise<void> {
  const docId = docIdForUser(userId)
  const raw: Record<string, unknown> = {
    userId,
    userName: preferences.userName || undefined,
    level: preferences.level,
    talkingoLevel: preferences.talkingoLevel,
    topic: preferences.topic,
    correctionStyle: preferences.correctionStyle,
    persona: preferences.persona || 'eli',
    targetLanguage: preferences.targetLanguage,
    nativeLanguage: preferences.nativeLanguage,
    learnerGender: preferences.learnerGender,
    preferredScript: preferences.preferredScript,
    dialect: preferences.dialect,
    heritageMode: preferences.heritageMode,
    uiLanguage: preferences.uiLanguage,
    learningGoal: preferences.learningGoal,
    onboardingComplete: preferences.onboardingComplete ?? true,
    currentUnitId: preferences.currentUnitId,
    updatedAt: Date.now(),
  }
  // Strip undefined values — Appwrite rejects unknown/undefined fields
  const doc = Object.fromEntries(
    Object.entries(raw).filter(([, v]) => v !== undefined)
  )

  try {
    await databases.updateDocument(DATABASE_ID, PREFERENCES_COLLECTION, docId, doc)
    return
  } catch (error: any) {
    const code = error?.code ?? error?.status ?? 0
    if (code !== 404) {
      console.error('[Appwrite] updateDocument(preferences) failed:', error)
      throw error
    }
  }

  try {
    await databases.createDocument(
      DATABASE_ID,
      PREFERENCES_COLLECTION,
      docId,
      { ...doc, createdAt: Date.now() },
      ownerPermissions(userId),
    )
  } catch (error: any) {
    const code = error?.code ?? error?.status ?? 0
    if (code === 409) {
      await databases.updateDocument(DATABASE_ID, PREFERENCES_COLLECTION, docId, doc)
      return
    }
    console.error('[Appwrite] createDocument(preferences) failed:', error)
    throw error
  }
}

export async function getUserPreferences(userId: string): Promise<UserPreferencesDoc | null> {
  return withRetry(async () => {
    try {
      const doc = await databases.getDocument(DATABASE_ID, PREFERENCES_COLLECTION, docIdForUser(userId))
      return doc as unknown as UserPreferencesDoc
    } catch (error: any) {
      const code = error?.code ?? error?.status ?? 0
      if (code !== 404) throw error
    }

    const response = await databases.listDocuments(DATABASE_ID, PREFERENCES_COLLECTION, [
      Query.equal('userId', userId),
      Query.limit(1),
    ])
    if (response.documents.length === 0) return null
    return response.documents[0] as unknown as UserPreferencesDoc
  }, { label: 'getUserPreferences', userId })
}
